Repository watertap-org/watertap, pull requests merged in 2021-05, with the labels that each got.

#79 Created initial test case for seawater alkalinity
  proteuslib/tests/test_seawater_alkalinity.py
Labels: Priority:Normal

#80 Add spacer geometry and update pressure drop and mass transfer coeff calculations
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
Labels: Priority:Normal, enhancement

#89 First GHA workflow
  .gitignore
Labels: Priority:High

#96 updated initial values in seawater and NaCl packages
  proteuslib/property_models/NaCl_prop_pack.py
  proteuslib/property_models/seawater_prop_pack.py
Labels: Priority:Normal

#85 Ph update01
  proteuslib/tests/test_pure_water_pH.py
Labels: Priority:Low
