Repository watertap-org/watertap, pull requests merged in 2021-08, with the labels that each got.

#190 Minor tweak of check_solve
  proteuslib/util/initialization.py
Labels: model dev team

#188 Add docs section on using pip to update existing dev environments
  docs/getting_started/install.rst
Labels: documentation, enhancement, software admin

#191 Reduce Test Time
  proteuslib/unit_models/reverse_osmosis_1D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal, model dev team

#194 Chemistry test reformation
  proteuslib/tests/test_chlorination.py
  proteuslib/tests/test_enrtl_water_pH.py
  proteuslib/tests/test_phosphorus_removal.py
  proteuslib/tests/test_pure_water_pH.py
  proteuslib/tests/test_recarbonation_process.py
  proteuslib/tests/test_remineralization.py
  proteuslib/tests/test_seawater_alkalinity.py
Labels: bug, Priority:High, chem team

#195 Add diffusivity to Seawater Property Model
  docs/technical_reference/property_models/seawater.rst
  proteuslib/property_models/seawater_prop_pack.py
  proteuslib/property_models/tests/test_seawater_prop_pack.py
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/reverse_osmosis_1D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_1D.py
Labels: model dev team

#178 Calculate state method
  proteuslib/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  proteuslib/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_monte_carlo_sampling_RO_ERD.py
  proteuslib/property_models/NaCl_prop_pack.py
  proteuslib/property_models/seawater_prop_pack.py
  proteuslib/property_models/tests/property_test_harness.py
  proteuslib/property_models/tests/test_NaCl_prop_pack.py
  proteuslib/property_models/tests/test_seawater_prop_pack.py
Labels: Priority:High, model dev team

#201 Add README badges for Codecov and repo activity metrics
  README.md
Labels: enhancement, Priority:Low

#202 Update installation docs
  docs/getting_started/install.rst
Labels: documentation, Priority:Normal

#198 Chemistry Scaling Docs
  docs/how_to_guides/how_to_scale_chemical_reactions.rst
  docs/how_to_guides/how_to_scale_chemical_species.rst
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/how_to_guides/how_to_use_inherent_reactions.rst
  docs/how_to_guides/index.rst
Labels: documentation, Priority:Normal, chem team
