Repository watertap-org/watertap, pull requests merged in 2021-06, with the labels that each got.

#87 Making parameter sweep tests cleanup after themselves
  .github/workflows/mpi4py-test.yml
  proteuslib/tools/parameter_sweep.py
  proteuslib/tools/tests/test_parameter_sweep.py
Labels: Priority:Normal

#100 update RO with energy recovery flowsheet
  proteuslib/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
Labels: Priority:Normal

#84 Added variables and improved initialization for 0D RO model
  README.md
  proteuslib/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  proteuslib/property_models/NaCl_prop_pack.py
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
Labels: Priority:Normal

#101 Update chemical process tests
  proteuslib/tests/test_pure_water_pH.py
  proteuslib/tests/test_recarbonation_process.py
  proteuslib/tests/test_seawater_alkalinity.py
Labels: Priority:Low

#97 Chlorination process tests
  proteuslib/tests/test_chlorination.py
Labels: Priority:Normal

#103 Fix readthedocs build errors and 1st draft of RO model documentation
  .readthedocs.yaml
  docs/conf.py
  docs/unit_models/0D_nanofiltration.rst
  docs/unit_models/index.rst
  docs/unit_models/reverse_osmosis_0D.rst
  proteuslib/unit_models/reverse_osmosis_0D.py
  setup.py
Labels: Priority:High, WIP, documentation

#107 Restructure docs at high-level
  docs/background/index.rst
  docs/getting_started/index.rst
  docs/how_to/index.rst
  docs/index.rst
  docs/technical_reference/index.rst
  docs/technical_reference/property_models/NaCl.rst
  docs/technical_reference/property_models/index.rst
  docs/technical_reference/property_models/seawater.rst
  docs/technical_reference/unit_models/0D_nanofiltration.rst
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/nanofiltration_1.png
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
Labels: Priority:High, documentation

#108 Test of Remineralization Process
  proteuslib/tests/test_remineralization.py
Labels: Priority:Normal

#109 Revising RO documentation
  docs/how_to/how_to_setup_RO_config_options.rst
  docs/how_to/how_to_setup_simple_RO.rst
  docs/how_to/index.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  proteuslib/unit_models/reverse_osmosis_0D.py
Labels: Priority:High, documentation

#110 Param sweep technical documenation
  docs/technical_reference/index.rst
  docs/technical_reference/tools/index.rst
  docs/technical_reference/tools/parameter_sweep.rst
  proteuslib/tools/parameter_sweep.py
  proteuslib/tools/tests/test_parameter_sweep.py
Labels: Priority:High, documentation

#111 Complete draft of RO technical reference
  docs/how_to/how_to_setup_RO_config_options.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  proteuslib/unit_models/reverse_osmosis_0D.py
Labels: Priority:High, documentation

#115 Fix chlorination
  proteuslib/tests/test_chlorination.py
Labels: Priority:High, bug

#117 Adding reverse osmosis tutorial
  docs/index.rst
  docs/tutorials/index.rst
  proteuslib/tests/test_tutorials.py
  setup.py
  tutorials/README.md
  tutorials/reverse_osmosis_0D.ipynb
Labels: Priority:High, documentation

#119 Documentation: How to scale a model
  docs/how_to/how_to_scale_a_model.rst
  docs/how_to/index.rst
Labels: documentation

#120 correct minor error in NaCl property package documentation
  docs/technical_reference/property_models/NaCl.rst
Labels: documentation

#124 What is proteuslib documentation
  docs/background/index.rst
  docs/background/what_is_proteuslib.rst
Labels: documentation

#127 Welcome documentation
  docs/how_to_guides/how_to_scale_a_model.rst
  docs/how_to_guides/how_to_setup_RO_config_options.rst
  docs/how_to_guides/how_to_setup_simple_RO.rst
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/index.rst
  docs/index.rst
Labels: documentation

#122 Doctest
  .github/workflows/python-package.yml
  docs/how_to_guides/how_to_scale_a_model.rst
  docs/how_to_guides/how_to_setup_RO_config_options.rst
  docs/how_to_guides/how_to_setup_simple_RO.rst
  docs/technical_reference/property_models/NaCl.rst
  docs/technical_reference/property_models/seawater.rst
  setup.py
Labels: Priority:Normal, documentation

#128 Adding doctests for parameter sweep tool using RO w/ energy recovery flowsheet
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  proteuslib/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  proteuslib/tools/parameter_sweep.py
Labels: documentation

#129 Chem how to doc
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/index.rst
Labels: Priority:High, documentation

#138 Implement scheme for managing special dependencies in setup.py
  .github/workflows/mpi4py-test.yml
  .github/workflows/python-package.yml
  setup.py
Labels: Priority:High, software admin

#130 Update permeate properties for 0D RO
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  proteuslib/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
Labels: Priority:High

#139 Update technical reference
  .github/workflows/python-package.yml
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/nanofiltration_0D.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
Labels: Priority:Normal, documentation, model dev team

#77 Generate IDAES configs from electrolyte database data
  .readthedocs.yaml
  docs/Makefile
  docs/conf.py
  docs/edb/concepts.md
  docs/edb/examples.rst
  docs/edb/index.rst
  docs/edb/installation.rst
  docs/edb/reference.rst
  docs/edb/schemas/component.html
  docs/edb/schemas/component.json
  docs/edb/schemas/reaction.html
  docs/edb/schemas/reaction.json
  docs/edb/schemas/schema_doc.css
  docs/edb/schemas/schema_doc.min.js
  docs/index.rst
  docs/make.bat
  docs/schemas/component.html
  docs/schemas/component.json
  docs/schemas/reaction.html
  docs/schemas/reaction.json
  examples/edb/carbonic_acid_example.py
  proteuslib/__init__.py
  proteuslib/edb/__init__.py
  proteuslib/edb/commands.py
  proteuslib/edb/data.json
  proteuslib/edb/data/base.json
  proteuslib/edb/data/component.json
  proteuslib/edb/data/reaction.json
  proteuslib/edb/data_model.py
  proteuslib/edb/db_api.py
  proteuslib/edb/error.py
  proteuslib/edb/schemas.py
  proteuslib/edb/tests/data.py
  proteuslib/edb/tests/test_data_model.py
  proteuslib/edb/tests/test_db_api.py
  proteuslib/edb/tests/test_recarbonation_process_edb.py
  proteuslib/edb/tests/test_validate.py
  proteuslib/edb/validate.py
  proteuslib/tests/test_recarbonation_process.py
  setup.py
Labels: Priority:Normal, chem team

#144 Add first draft of installation guide
  docs/getting_started/index.rst
  docs/getting_started/install.rst
  docs/how_to_guides/how_to_contribute_development.rst
  docs/how_to_guides/index.rst
Labels: Priority:High, documentation, software admin
