Repository watertap-org/watertap, pull requests merged in 2021-11, with the labels that each got.

#244 EDB documentation and examples
  .github/workflows/checks.yml
  README.md
  docs/conf.py
  docs/examples/edb/edb_example.ipynb
  docs/how_to_guides/edb_cli.rst
  docs/how_to_guides/how_to_use_EDB.rst
  setup.py
  watertap/edb/commands.py
  watertap/edb/data_model.py
  watertap/edb/db_api.py
  watertap/tests/test_notebooks.py
Labels: Priority:Normal

#240 Adding true precipitation tests to chemical processes
  watertap/tests/test_pH_dependent_solubility.py
  watertap/tests/test_solids.py
Labels: Priority:Normal

#253 Add instructions on how to install pandoc
  docs/getting_started/install.rst
Labels: documentation, Priority:Normal, software admin

#256 Fixing confusing or out-dated records in data base json files
  docs/examples/edb/edb_example.ipynb
  docs/how_to_guides/edb_cli.rst
  watertap/edb/data/base.json
  watertap/edb/data/component.json
  watertap/edb/data/reaction.json
  watertap/edb/data_model.py
  watertap/edb/db_api.py
  watertap/examples/chemistry/tests/test_enrtl_water_pH_edb.py
  watertap/examples/chemistry/tests/test_pure_water_pH.py
Labels: Priority:Normal

#263 Documentation for why we want EDB
  docs/background/index.rst
  docs/background/why_use_edb.rst
  docs/how_to_guides/how_to_use_EDB.rst
Labels: Priority:High

#261 Adding base classes for WT3 functionality
  docs/technical_reference/core/index.rst
  docs/technical_reference/core/water_props.rst
  docs/technical_reference/core/zero_order_unit.rst
  docs/technical_reference/index.rst
  watertap/core/tests/test_zero_order_properties.py
  watertap/core/tests/test_zero_order_unit.py
  watertap/core/zero_order_properties.py
  watertap/core/zero_order_unit.py
Labels: Priority:Normal, model dev team, nawi

#265 Failing RO initialization fails tests
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal
