Repository watertap-org/watertap, pull requests merged in 2021-09, with the labels that each got.

#213 Stoich reactor
  proteuslib/tests/test_water_softening.py
  proteuslib/tests/test_water_softening_Ca.py
  proteuslib/tests/test_water_softening_Mg.py
Labels: Priority:Normal, chem team

#204 Fix EDB handling of ions
  proteuslib/edb/commands.py
  proteuslib/edb/data/base.json
  proteuslib/edb/data/component.json
  proteuslib/edb/data/reaction.json
  proteuslib/edb/data_model.py
  proteuslib/edb/db_api.py
  proteuslib/edb/schemas.py
  proteuslib/edb/tests/data.py
  proteuslib/edb/tests/test_db_api.py
  proteuslib/edb/tests/test_recarbonation_process_edb.py
  proteuslib/edb/tests/util.py
  proteuslib/tests/test_enrtl_water_pH_edb.py
  proteuslib/tests/test_pure_water_pH.py
  proteuslib/tests/test_pure_water_pH_edb.py
Labels: Priority:High

#214 Reporter for pressure_exchanger and call report in RO tutorial
  proteuslib/unit_models/pressure_exchanger.py
  proteuslib/unit_models/tests/test_pressure_exchanger.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_1D.py
  tutorials/reverse_osmosis_0D.ipynb
Labels: Priority:Normal, model dev team

#218 Address KeyError in os.environ when testing locally (#217)
  proteuslib/tests/test_pure_water_pH_edb.py
Labels: bug, Priority:High

#220 0DRO permeate scaling
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
Labels: bug, Priority:High, model dev team

#212 Enable MongoDB in CI checks
  .github/workflows/checks.yml
Labels: Priority:High, software admin

#222 Improve documentation for ElectrolyteDB installation
  docs/_static/mongodb-compass-electrolytedb.png
  docs/_static/mongodb-compass-initial.png
  docs/_static/mongodb-download-page.png
  docs/getting_started/index.rst
  docs/getting_started/install.rst
  docs/how_to_guides/how_to_use_EDB.rst
Labels: Priority:Normal

#215 Adding sampling method from PySMO
  proteuslib/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_monte_carlo_sampling_RO_ERD.py
  proteuslib/tools/parameter_sweep.py
Labels: Priority:Normal, analysis team

#224 Adding option to fill infeasible points with interpolated values
  proteuslib/tools/parameter_sweep.py
  proteuslib/tools/tests/test_parameter_sweep.py
  setup.py
Labels: Priority:Normal, analysis team

#221 Add apidoc
  docs/apidoc.bat
  docs/apidoc.sh
  docs/apidoc/modules.rst
  docs/apidoc/proteuslib.edb.rst
  docs/apidoc/proteuslib.flowsheets.RO_with_energy_recovery.rst
  docs/apidoc/proteuslib.flowsheets.rst
  docs/apidoc/proteuslib.property_models.rst
  docs/apidoc/proteuslib.rst
  docs/apidoc/proteuslib.unit_models.rst
  docs/getting_started/install.rst
  docs/index.rst
  docs/technical_reference/index.rst
  docs/technical_reference/tools/parameter_sweep.rst
  docs/technical_reference/unit_models/pressure_exchanger.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/reverse_osmosis_1D.rst
  proteuslib/tests/test_docs.py
Labels: documentation, Priority:Normal

#223 Enable running pytest suite in "user mode" (non-dev) installation
  .github/workflows/checks.yml
  docs/getting_started/install.rst
  proteuslib/conftest.py
  pytest.ini
  setup.py
Labels: Priority:Normal
