Repository watertap-org/watertap, pull requests merged in 2021-12, with the labels that each got.

#266 Set reaction order properly
  docs/apidoc/modules.rst
  docs/apidoc/watertap.core.rst
  docs/apidoc/watertap.core.util.rst
  docs/apidoc/watertap.data.rst
  docs/apidoc/watertap.edb.rst
  docs/apidoc/watertap.examples.case_studies.rst
  docs/apidoc/watertap.examples.chemistry.rst
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.analysis.rst
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.flowsheet_components.chemistry.rst
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.flowsheet_components.examples.rst
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.flowsheet_components.rst
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.model_components.eNRTL.rst
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.model_components.rst
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.rst
  docs/apidoc/watertap.examples.flowsheets.lsrro.rst
  docs/apidoc/watertap.examples.flowsheets.rst
  docs/apidoc/watertap.examples.rst
  docs/apidoc/watertap.property_models.rst
  docs/apidoc/watertap.rst
  docs/apidoc/watertap.tools.rst
  docs/apidoc/watertap.ui.rst
  docs/apidoc/watertap.unit_models.rst
  docs/apidoc/watertap.unit_models.zero_order.rst
  docs/how_to_guides/edb_api.rst
  docs/how_to_guides/how_to_use_EDB.rst
  watertap/edb/data_model.py
  watertap/edb/db_api.py
  watertap/edb/schemas.py
  watertap/edb/tests/data.py
  watertap/edb/tests/test_data_model.py
  watertap/edb/tests/test_schemas.py
  watertap/examples/chemistry/tests/test_pure_water_pH.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/SepRO_plus_Chlorination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/ZeroDRO_plus_Chlorination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/pretreatment_stoich_softening_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/costing.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/desalination.py
Labels: Priority:High

#271 Renaming outlets in zero order model base class
  docs/technical_reference/core/zero_order_unit.rst
  watertap/core/tests/test_zero_order_sito.py
  watertap/core/zero_order_sito.py
Labels: enhancement, Priority:Normal

#273 More EDB examples
  examples/edb/carbonic_acid_example.py
  watertap/edb/db_api.py
  watertap/edb/tests/test_db_api.py
  watertap/examples/edb/__init__.py
  watertap/examples/edb/simple_acid.py
  watertap/examples/edb/tests/__init__.py
  watertap/examples/edb/tests/conftest.py
  watertap/examples/edb/tests/test__fixtures.py
  watertap/examples/edb/tests/test_edb_examples.py
  watertap/examples/edb/the_basics.py
Labels: Priority:Normal, chem team

#260 Changes for connecting to cloud mongodb server
  .github/workflows/checks.yml
  watertap/conftest.py
  watertap/edb/commands.py
  watertap/edb/db_api.py
  watertap/edb/tests/test_edb.py
  watertap/tests/conftest.py
  watertap/tests/test_notebooks.py
Labels: Priority:Normal

#276 How-To Guide for Parallel, Random Parameter Sweeps
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  docs/how_to_guides/index.rst
Labels: Priority:Normal
