Repository watertap-org/watertap, pull requests merged in 2021-07, with the labels that each got.

#142 Reorganize Electrolyte Database Documentation
  .gitignore
  docs/edb/concepts.md
  docs/edb/examples.rst
  docs/edb/index.rst
  docs/edb/installation.rst
  docs/how_to_guides/how_to_use_EDB.rst
  docs/how_to_guides/index.rst
  docs/index.rst
  docs/technical_reference/edb/index.rst
  docs/technical_reference/edb/schemas/component.html
  docs/technical_reference/edb/schemas/component.json
  docs/technical_reference/edb/schemas/reaction.html
  docs/technical_reference/edb/schemas/reaction.json
  docs/technical_reference/edb/schemas/schema_doc.css
  docs/technical_reference/edb/schemas/schema_doc.min.js
  docs/technical_reference/index.rst
  proteuslib/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  proteuslib/unit_models/nanofiltration_0D.py
  proteuslib/unit_models/pressure_exchanger.py
Labels: Priority:Normal, chem team, documentation, model dev team

#147 Update README to point to installation guide in RTD docs
  README.md
Labels: Priority:High

#148 Pressure Exchanger Documentation
  docs/_static/unit_models/energy_recovery_system.png
  docs/_static/unit_models/nanofiltration.png
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/nanofiltration_0D.rst
  docs/technical_reference/unit_models/pressure_exchanger.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
Labels: Priority:High, documentation, model dev team

#151 Extend GitHub Actions checks to include Windows
  .github/workflows/checks.yml
  .github/workflows/python-package.yml
  README.md
  setup.py
Labels: software admin

#135 Validation Test for ENRLT Model
  proteuslib/tests/test_enrtl_water_pH.py
  setup.py
Labels: Priority:Normal, chem team

#157 Update pip install target to PyPI package
  docs/getting_started/install.rst
Labels: Priority:High, documentation, software admin

#155 Fix JSON errors for EDB load
  proteuslib/edb/commands.py
  proteuslib/edb/data/component.json
  proteuslib/edb/data_model.py
  proteuslib/edb/db_api.py
  proteuslib/edb/tests/test_data_model.py
  proteuslib/edb/tests/test_edb.py
  proteuslib/edb/validate.py
  setup.py
Labels: Priority:Normal, bug, chem team

#154 Phosphorus removal test
  proteuslib/tests/test_phosphorus_removal.py
Labels: Priority:Normal, chem team

#160 Fix APIDOC warnings
  docs/Makefile
  docs/index.rst
  docs/make.bat
Labels: Priority:Low, documentation, software admin

#146 updated parameter_sweep tool to allow for random sampling
  proteuslib/tools/parameter_sweep.py
  proteuslib/tools/tests/test_parameter_sweep.py
Labels: Priority:Normal, analysis team, enhancement

#137 First draft of 1DRO unit model
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/reverse_osmosis_1D.rst
  proteuslib/property_models/NaCl_prop_pack.py
  proteuslib/unit_models/reverse_osmosis_1D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:High, WIP, model dev team

#167 Cleaning Chem Tests
  proteuslib/tests/test_chlorination.py
  proteuslib/tests/test_enrtl_water_pH.py
  proteuslib/tests/test_phosphorus_removal.py
  proteuslib/tests/test_pure_water_pH.py
  proteuslib/tests/test_recarbonation_process.py
  proteuslib/tests/test_remineralization.py
  proteuslib/tests/test_seawater_alkalinity.py
Labels: Priority:Low, chem team

#95 Property test harness
  proteuslib/property_models/seawater_prop_pack.py
  proteuslib/property_models/tests/property_test_harness.py
  proteuslib/property_models/tests/test_NaCl_prop_pack.py
  proteuslib/property_models/tests/test_seawater_prop_pack.py
Labels: Priority:Normal, model dev team

#170 Add reporting to 0DRO
  proteuslib/unit_models/reverse_osmosis_0D.py
Labels: Priority:Normal, enhancement, model dev team

#173 Add DOF = 0 assertion to initialization methods in 0D and 1DRO
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/reverse_osmosis_1D.py
Labels: Priority:Normal, model dev team

#161 Updating parameter sweep docs
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/technical_reference/tools/parameter_sweep.rst
  proteuslib/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  proteuslib/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
Labels: Priority:Normal, analysis team, documentation

#162 1DRO Unit Model
  proteuslib/tests/test_tutorials.py
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/reverse_osmosis_1D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:High, model dev team

#185 Investigate CI build errors on Windows (#184)
  .github/workflows/checks.yml
  docs/getting_started/install.rst
  setup.py
Labels: Priority:High, software admin

#175 Update idaes-pse to latest tag on nawi-hub fork
  proteuslib/tests/test_chlorination.py
  proteuslib/tests/test_enrtl_water_pH.py
  proteuslib/tests/test_phosphorus_removal.py
  proteuslib/tests/test_recarbonation_process.py
  proteuslib/tests/test_remineralization.py
  proteuslib/tests/test_seawater_alkalinity.py
  setup.py
Labels: Priority:High

#180 Replace solvent_list and solute_list in RO models
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/reverse_osmosis_1D.py
Labels: Priority:Normal

#186 Fixing issue with values iterator in parameter_sweep
  proteuslib/tools/parameter_sweep.py
Labels: Priority:Normal, analysis team

#179 Fail on warning functionality in initialize method
  proteuslib/unit_models/reverse_osmosis_0D.py
  proteuslib/unit_models/reverse_osmosis_1D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_0D.py
  proteuslib/unit_models/tests/test_reverse_osmosis_1D.py
  proteuslib/util/initialization.py
  proteuslib/util/tests/test_initialization.py
Labels: Priority:Normal, enhancement, model dev team
