Repository watertap-org/watertap, pull requests merged in 2022-09, with the labels that each got.

#686 Lazy flow costing in WaterTAP Costing Package
  watertap/costing/tests/test_watertap_costing_package.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/costing.py
Labels: Priority:High

#707 Update microbial battery groundwater treatment spreadsheet (AMO 1679)
  watertap/core/zero_order_costing.py
  watertap/examples/flowsheets/case_studies/groundwater_treatment/groundwater_treatment.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_case_study.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/tests/__int__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/tests/test_groundwater_treatment.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/tests/test_groundwater_treatment_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/wastewater_default_case_study.yaml
  watertap/unit_models/zero_order/tests/test_microbial_battery_zo.py
Labels: amo

#708 Revise operating costing parameters for AMO 1614
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/tests/test_supercritical_sludge_to_gas.py
Labels: amo

#679 Membrane channel refactor
  watertap/core/__init__.py
  watertap/core/membrane_channel0d.py
  watertap/core/membrane_channel1d.py
  watertap/core/membrane_channel_base.py
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  watertap/examples/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/unit_models/_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:High, model dev team, nawi

#711 electrodialysis flowsheet improvement
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
Labels: Priority:High

#698 Metab GUI connection
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:High

#728 Re-export flowsheet after solve
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: ui

#726 Convert units between model and displayed values on UI
  setup.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: ui

#552 Evaporator Refinement
  watertap/unit_models/mvc/components/complete_condenser.py
  watertap/unit_models/mvc/components/compressor.py
  watertap/unit_models/mvc/components/evaporator.py
  watertap/unit_models/mvc/components/tests/test_complete_condenser.py
  watertap/unit_models/mvc/components/tests/test_evaporator.py
  watertap/unit_models/mvc/tests/test_mvc.py
Labels: Priority:High, model dev team

#734 Revise suboxic ASM report
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_activated_sludge_process.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_activated_sludge_process_global.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/tests/test_suboxic_activated_sludge_process.py
Labels: Priority:Normal, amo

#735 AMO 1575 - add PAA files from Box
  docs/how_to_guides/how_to_scale_a_model.rst
  setup.py
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/peracetic_acid_disinfection.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_case_study.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/tests/test_peracetic_acid_disinfection.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/tests/test_peracetic_acid_disinfection_sweep.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/paa_disinfection_zo.py
  watertap/unit_models/zero_order/tests/test_peracetic_acid_disinfection_zo.py
Labels: Priority:High, amo

#699 DSPMDE ion property refinement
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
  watertap/unit_models/tests/test_boron_removal.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
  watertap/unit_models/tests/test_gac.py
Labels: Priority:High

#705 Objective in RO with Energy Recovery Flowsheet
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  watertap/examples/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
Labels: Priority:Low

#704 Add has_aop configuration for UV model
  docs/technical_reference/unit_models/uv_aop.rst
  watertap/unit_models/tests/test_uv_aop.py
  watertap/unit_models/uv_aop.py
Labels: Priority:Normal, nawi

#732 Adjust Metab rounding for UI
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.py
Labels: Priority:High

#736 Electronp report
  watertap/core/zero_order_costing.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/case_1617.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal.py
Labels: Priority:Normal

#743 AMO 1575 : Applications 1 & 4
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/centrifuge.yaml
  watertap/data/techno_economic/clarifier.yaml
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/hrcs.yaml
  watertap/data/techno_economic/magprex.yaml
  watertap/data/techno_economic/struvite_classifier.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_case_1575.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/tests/test_hrcs.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/tests/test_multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_case_1575.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/tests/test_magprex.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/tests/test_multi_sweep.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/centrifuge_zo.py
  watertap/unit_models/zero_order/clarifier_zo.py
  watertap/unit_models/zero_order/hrcs_zo.py
  watertap/unit_models/zero_order/magprex_zo.py
  watertap/unit_models/zero_order/struvite_classifier_zo.py
  watertap/unit_models/zero_order/tests/test_centrifuge_zo.py
  watertap/unit_models/zero_order/tests/test_clarifier_zo.py
  watertap/unit_models/zero_order/tests/test_hrcs_zo.py
  watertap/unit_models/zero_order/tests/test_magprex_zo.py
  watertap/unit_models/zero_order/tests/test_struvite_classifier_zo.py
Labels: Priority:High, amo

#757 Add GUI for suboxic ASM process
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_ASM_ui.py
Labels: amo

#752 Add GUI for biomembrane filtration process
  watertap/data/techno_economic/dmbr.yaml
  watertap/data/techno_economic/mabr.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/tests/test_biomembrane_filtration.py
  watertap/unit_models/zero_order/tests/test_dmbr_zo.py
Labels: amo, ui

#684 Ion exchange 0D single component model
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/__init__.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:High, model dev team

#675 Parameter Sweep Classs
  .github/workflows/mpi4py-test.yml
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/analysis/multi_sweep.py
  watertap/tools/MPI/__init__.py
  watertap/tools/MPI/dummy_mpi.py
  watertap/tools/MPI/tests/__init__.py
  watertap/tools/MPI/tests/test_dummy_mpi.py
  watertap/tools/parameter_sweep.py
  watertap/tools/parameter_sweep/__init__.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_functions.py
  watertap/tools/parameter_sweep/parameter_sweep_reader.py
  watertap/tools/parameter_sweep/parameter_sweep_writer.py
  watertap/tools/parameter_sweep/sampling_types.py
  watertap/tools/parameter_sweep/tests/__init__.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_reader.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_writer.py
  watertap/tools/parameter_sweep/tests/test_recursive_parameter_sweep.py
  watertap/tools/parameter_sweep_input_parser.py
  watertap/tools/recursive_parameter_sweep.py
Labels: Priority:Normal

#759 Add GUI for AMO 1575 Magprex
  watertap/data/techno_economic/struvite_classifier.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.py
Labels: amo, ui

#764 Extend tests for registered flowsheet interfaces
  setup.py
  watertap/ui/tests/test_flowsheet_interfaces.py
Labels: Priority:High, ui

#766 AMO 1690 flowsheet
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_case_study.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/tests/test_amo_1690.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/tests/test_amo_1690_sweep.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/anaerobic_digestion_reactive_zo.py
  watertap/unit_models/zero_order/feed_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_digestion_reactive_zo.py
Labels: amo

#763 Add GUI for CANDOP
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_ui.py
Labels: amo, ui

#756 Report solver failures and change ModelExport keys
  watertap/ui/fsapi.py
  watertap/ui/tests/test_flowsheet_interfaces.py
  watertap/ui/tests/test_fsapi.py
Labels: ui

#765 Add GUI for supercritical sludge to gas process
  watertap/core/zero_order_costing.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/tests/test_supercritical_sludge_to_gas.py
  watertap/unit_models/zero_order/autothermal_hydrothermal_liquefaction_zo.py
  watertap/unit_models/zero_order/hydrothermal_gasification_zo.py
  watertap/unit_models/zero_order/tests/test_autothermal_hydrothermal_liquefaction_zo.py
  watertap/unit_models/zero_order/tests/test_hydrothermal_gasification_zo.py
Labels: amo, ui

#771 Add GUI for swine wastewater treatment
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_ui.py
Labels: amo, ui

#767 Add GUI for Groundwater Treatment
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/tests/test_groundwater_treatment.py
Labels: amo, ui

#769 Add GUI for HRCS
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/tests/test_hrcs.py
  watertap/unit_models/zero_order/hrcs_zo.py
  watertap/unit_models/zero_order/tests/test_hrcs_zo.py
Labels: amo, ui

#772 Add GUI for AMO 1690
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_ui.py
Labels: Priority:High, amo, ui

#775 Add GUI for PAA
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_ui.py
Labels: Priority:High, amo, ui

#776 Add GUI for 1611- Dye desal
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
Labels: Priority:High, amo, ui

#778 Minor costing updates for AMO flowsheets - PAA and 1690
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection.py
Labels: Priority:Low, amo, ui

#722 Feed (ZO)
  docs/technical_reference/unit_models/zero_order_unit_models/automate_rst_file_wt3.py
  docs/technical_reference/unit_models/zero_order_unit_models/feed_zo.rst
  watertap/unit_models/zero_order/feed_zo.py
Labels: documentation, Priority:Normal, wt3 migration

#783 Diagrams for UI flowsheets
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_ASM_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_ui.png
Labels: Priority:High, amo, ui

#785 Passing initialize options through zero order initialize
  watertap/core/zero_order_base.py
Labels: Priority:High

#780 Register all of the recently merged flowsheet UI modules
  setup.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/tests/test_amo_1690.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/tests/test_amo_1690_sweep.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_flowsheet_interfaces.py
Labels: Priority:High, ui
