Repository watertap-org/watertap, pull requests merged in 2022-05, with the labels that each got.

#506 Add AMO electrochemical nutrient recovery model
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/electrochemical_nutrient_removal.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/case_1617.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/electrochemical_nutrient_removal_zo.py
  watertap/unit_models/zero_order/mabr_zo.py
  watertap/unit_models/zero_order/tests/test_electrochemical_nutrient_removal_zo.py
Labels: Priority:Normal, amo

#505 Metab analysis
  watertap/core/tests/test_zero_order_sido_reactive.py
  watertap/core/zero_order_sido_reactive.py
  watertap/data/techno_economic/metab.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/test_metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/test_multi_sweep.py
  watertap/unit_models/zero_order/tests/test_metab_zo.py
Labels: Priority:High, amo

#519 Enable recursive parameter sweep to attempt to provide a guaranteed number of solutions
  watertap/tools/parameter_sweep.py
  watertap/tools/recursive_parameter_sweep.py
  watertap/tools/tests/test_recursive_parameter_sweep.py
Labels: Priority:High

#413 API for the WaterTAP UI
  docs/apidoc/watertap.core.plugins.rst
  docs/apidoc/watertap.core.rst
  docs/apidoc/watertap.costing.rst
  docs/apidoc/watertap.data.rst
  docs/apidoc/watertap.data.techno_economic.rst
  docs/apidoc/watertap.examples.chemistry.rst
  docs/apidoc/watertap.examples.edb.rst
  docs/apidoc/watertap.examples.flowsheets.case_studies.municipal_treatment.rst
  docs/apidoc/watertap.examples.flowsheets.case_studies.rst
  docs/apidoc/watertap.examples.flowsheets.case_studies.seawater_RO_desalination.rst
  docs/apidoc/watertap.examples.flowsheets.case_studies.wastewater_resource_recovery.rst
  docs/apidoc/watertap.examples.flowsheets.lsrro.rst
  docs/apidoc/watertap.examples.flowsheets.rst
  docs/apidoc/watertap.examples.rst
  docs/apidoc/watertap.property_models.activated_sludge.rst
  docs/apidoc/watertap.property_models.rst
  docs/apidoc/watertap.rst
  docs/apidoc/watertap.tools.rst
  docs/apidoc/watertap.ui.rst
  docs/apidoc/watertap.unit_models.mvc.components.rst
  docs/apidoc/watertap.unit_models.mvc.rst
  docs/apidoc/watertap.unit_models.rst
  docs/apidoc/watertap.unit_models.zero_order.rst
  docs/technical_reference/index.rst
  docs/technical_reference/ui/index.rst
  watertap/costing/watertap_costing_package.py
  watertap/examples/edb/simple_acid.py
  watertap/examples/edb/solid_precipitation_reactions.py
  watertap/examples/edb/vapor_liquid_equilibrium.py
  watertap/ui/api.py
  watertap/ui/api_util.py
  watertap/ui/tests/test_api.py
  watertap/unit_models/mvc/components/evaporator.py
  watertap/unit_models/zero_order/gas_sparged_membrane_zo.py
Labels: Priority:Normal

#530 Modify MABR model for AMO project
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/mabr.yaml
  watertap/unit_models/zero_order/mabr_zo.py
  watertap/unit_models/zero_order/tests/test_mabr_zo.py
Labels: Priority:Normal, amo

#509 Preliminary Documentation for ASM1 Property Model
  docs/technical_reference/property_models/activated_sludge_model.rst
  docs/technical_reference/property_models/index.rst
Labels: documentation, Priority:Normal, WIP, amo, property_model

#523 Electrodialysis 0 d
  watertap/unit_models/electrodialysis_0d.py
  watertap/unit_models/tests/test_coag_floc_model.py
  watertap/unit_models/tests/test_electrodialysis_0d.py
Labels: Priority:Normal, chem team

#535 biomembrane filtration flowsheet
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/tests/test_biomembrane_filtration.py
Labels: Priority:High, amo

#520 Update idaes-pse requirement to 2.0.0.dev0.watertap.2022.05.18 tag
  .github/workflows/checks.yml
  setup.py
  watertap/core/tests/test_zero_order_base.py
  watertap/edb/tests/test_data_model.py
  watertap/examples/chemistry/tests/test_recarbonation_process.py
Labels: Priority:High

#537 Ed0 d doc
  docs/_static/unit_models/EDdiagram.png
  docs/technical_reference/unit_models/electrodialysis_0D.rst
  docs/technical_reference/unit_models/index.rst
Labels: documentation, Priority:Normal, chem team

#534 ZO Costing Doc Placeholder
  docs/technical_reference/core/index.rst
  docs/technical_reference/core/zero_order_costing.rst
  watertap/core/zero_order_costing.py
Labels: Priority:Normal

#536 Boron removal documentation
  docs/_static/unit_models/BoronRemovalDiagram.png
  docs/technical_reference/unit_models/boron_removal.rst
  docs/technical_reference/unit_models/coag_floc_model.rst
  docs/technical_reference/unit_models/index.rst
Labels: documentation, Priority:Normal, chem team

#531 Boron removal model
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
  watertap/unit_models/boron_removal.py
  watertap/unit_models/tests/test_boron_removal.py
Labels: Priority:Normal, chem team
