Repository watertap-org/watertap, pull requests merged in 2022-06, with the labels that each got.

#546 Dye desalination
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/nanofiltration.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_sweep.py
Labels: Priority:Normal

#561 ZO validation - add to _column_to_component_map dict
  watertap/unit_models/zero_order/validation/unit_validator.py
Labels: wt3 migration

#562 Develop unit models for supercritical sludge to gas process
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/autothermal_hydrothermal_liquefaction.yaml
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/hydrothermal_gasification.yaml
  watertap/data/techno_economic/supercritical_salt_precipitation.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_global_costing.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/autothermal_hydrothermal_liquefaction_zo.py
  watertap/unit_models/zero_order/hydrothermal_gasification_zo.py
  watertap/unit_models/zero_order/supercritical_salt_precipitation_zo.py
  watertap/unit_models/zero_order/tests/test_autothermal_hydrothermal_liquefaction_zo.py
  watertap/unit_models/zero_order/tests/test_hydrothermal_gasification_zo.py
  watertap/unit_models/zero_order/tests/test_supercritical_salt_precipitation_zo.py
Labels: Priority:Normal, amo

#565 Add sensitivity analysis for biomembrane filtration flowsheet
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/tests/test_multi_sweep.py
Labels: Priority:Normal, amo

#567 Dye desalination with Reverse Osmosis
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
Labels: Priority:Normal

#572 Add partial support for parallel unit costing
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/zero_order_costing.py
Labels: Priority:Normal

#268 Updating pressure exchanger model to include mass transfer option
  watertap/unit_models/pressure_exchanger.py
  watertap/unit_models/tests/test_pressure_exchanger.py
Labels: enhancement, Priority:Normal, model dev team, analysis team, nawi

#563 Sphinx code docs reorg
  docs/conf.py
  docs/getting_started/install.rst
  docs/how_to_guides/how_to_contribute_development.rst
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  docs/technical_reference/core/diso_methods.rst
  docs/technical_reference/core/electricity_methods.rst
  docs/technical_reference/core/pt_methods.rst
  docs/technical_reference/core/sido_methods.rst
  docs/technical_reference/core/sidor_methods.rst
  docs/technical_reference/core/siso_methods.rst
  docs/technical_reference/core/water_props.rst
  docs/technical_reference/core/zero_order_costing.rst
  docs/technical_reference/core/zero_order_unit.rst
  docs/technical_reference/tools/parameter_sweep.rst
  docs/technical_reference/ui/index.rst
  docs/technical_reference/unit_models/crystallizer_0D.rst
  docs/technical_reference/unit_models/nanofiltration_ZO.rst
  docs/technical_reference/unit_models/pressure_exchanger.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
Labels: Priority:High

#527 New module to test UI API against metab example flowsheet
  docs/_static/menu-icon.png
  docs/_static/search-icon.png
  docs/_static/terminal-icon.png
  docs/conf.py
  docs/how_to_guides/how_to_use_ui_api.rst
  docs/how_to_guides/index.rst
  docs/technical_reference/ui/index.rst
  pytest.ini
  setup.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_api.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/flowsheets.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/test_metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/test_metab_api.py
  watertap/ui/api.py
  watertap/ui/api_model.py
  watertap/ui/api_util.py
  watertap/ui/tests/test_api.py
  watertap/unit_models/zero_order/feed_zo.py
  watertap/unit_models/zero_order/metab_zo.py
Labels: Priority:Normal

#587 Update Workshop Notebook
  tutorials/aeesp_workshop_tutorial.ipynb
  tutorials/pyomo_solution.png
Labels: nawi

#590 Evaporation Pond ZO model update
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/evaporation_pond.yaml
  watertap/unit_models/zero_order/evaporation_pond_zo.py
  watertap/unit_models/zero_order/tests/test_evaporation_pond_zo.py
Labels: Priority:Normal, wt3 migration

#589 Storage Tank ZO model update
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/storage_tank.yaml
  watertap/unit_models/zero_order/storage_tank_zo.py
  watertap/unit_models/zero_order/tests/test_storage_tank_zo.py
Labels: Priority:High, wt3 migration

#582 Adding costing to ED model v2
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/__init__.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:High, chem team, costing

#591 fix a few typos and change costing params in yamls
  watertap/data/techno_economic/aeration_basin.yaml
  watertap/data/techno_economic/anaerobic_digestion_oxidation.yaml
  watertap/data/techno_economic/backwash_solids_handling.yaml
  watertap/data/techno_economic/coag_and_floc.yaml
  watertap/data/techno_economic/conventional_activated_sludge.yaml
  watertap/data/techno_economic/dual_media_filtration.yaml
  watertap/data/techno_economic/fixed_bed.yaml
  watertap/data/techno_economic/mbr.yaml
  watertap/data/techno_economic/ozonation.yaml
  watertap/data/techno_economic/ozone_aop.yaml
  watertap/data/techno_economic/settling_pond.yaml
  watertap/data/techno_economic/static_mixer.yaml
  watertap/data/techno_economic/sw_onshore_intake.yaml
  watertap/data/techno_economic/walnut_shell_filter.yaml
  watertap/examples/flowsheets/case_studies/municipal_treatment/tests/test_municipal_treatment.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/tests/test_seawater_RO_desalination.py
  watertap/unit_models/zero_order/tests/test_walnut_shell_filter_zo.py
Labels: Priority:Normal, wt3 migration

#554 UV Model
  watertap/property_models/NDMA_prop_pack.py
  watertap/property_models/tests/test_NDMA_prop_pack.py
  watertap/unit_models/__init__.py
  watertap/unit_models/tests/test_ultraviolet.py
  watertap/unit_models/ultraviolet.py
Labels: Priority:High, nawi

#576 AMO 1595 initial flowsheet
  watertap/data/techno_economic/CANDO_P.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_case_study.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/tests/test_amo_1595.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/tests/test_amo_1595_sweep.py
  watertap/unit_models/zero_order/tests/test_CANDOP_zo.py
Labels: Priority:High

#594 Optimize operational variables for dye desalination example
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_sweep.py
Labels: amo

#566 Add crystallizer operating cost
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/crystallization/sim_simple_crystallizer.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/tests/test_crystallizer.py
Labels: Priority:High, nawi, costing

#585 Custom ZO Docs
  docs/technical_reference/unit_models/zero_order_unit_models/CANDOP_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/WT3_unit_classification_for_doc.xlsx
  docs/technical_reference/unit_models/zero_order_unit_models/anaerobic_mbr_mec_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/automate_rst_file_wt3.py
  docs/technical_reference/unit_models/zero_order_unit_models/brine_concentrator_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/chemical_addition_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/chlorination_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/co2_addition_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/coag_and_floc_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/cooling_tower_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/deep_well_injection_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/dmbr_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/dummy_sidor_data.yaml
  docs/technical_reference/unit_models/zero_order_unit_models/electrodialysis_reversal_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/evaporation_pond_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/filter_press_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/fixed_bed_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/gac_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/ion_exchange_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/iron_and_manganese_removal_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/mabr_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/mbr_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/metab_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/municipal_wwtp_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/nanofiltration_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/ozone_aop_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/ozone_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/pump_electricity_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/secondary_treatment_wwtp_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/sedimentation_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/storage_tank_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/surface_discharge_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/sw_onshore_intake_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/uv_aop_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/uv_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/vfa_recovery_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/waiv_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/water_pumping_station_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/well_field_zo.rst
  watertap/unit_models/zero_order/CANDOP_zo.py
  watertap/unit_models/zero_order/gac_zo.py
  watertap/unit_models/zero_order/ozone_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_aop_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_zo.py
Labels: documentation, Priority:Normal, WIP, amo, nawi, wt3 migration

#600 Change UV model to UV AOP model
  watertap/unit_models/__init__.py
  watertap/unit_models/tests/test_uv_aop.py
  watertap/unit_models/uv_aop.py
Labels: Priority:High, nawi

#596 Add documentation for UV
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/uv_aop.rst
Labels: documentation, nawi

#601 Include utilization factor in zero-order total variable operating cost calculation
  watertap/core/zero_order_costing.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/tests/test_amo_1595.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/tests/test_biomembrane_filtration.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/tests/test_electrochemical_nutrient_removal.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/tests/test_supercritical_sludge_to_gas.py
Labels: Priority:High
