Repository watertap-org/watertap, pull requests merged in 2022-03, with the labels that each got.

#365 Migrating WT3 decarbonator model
  watertap/data/techno_economic/buffer_tank.yaml
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/decarbonator.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/decarbonator_zo.py
  watertap/unit_models/zero_order/tests/test_decarbonator_zo.py
Labels: Priority:Normal, wt3 migration

#366 Migrating WT3 ultra filtration model
  watertap/data/techno_economic/ultra_filtration.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_ultra_filtration_zo.py
  watertap/unit_models/zero_order/ultra_filtration_zo.py
Labels: Priority:Normal, wt3 migration

#368 Fix multi-sweep analysis within full_treatment_train
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF_no_bypass.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_single_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_softening.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_softening_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/util.py
  watertap/tools/parameter_sweep.py
Labels: bug

#371 Migrating WT3 media filtration model
  watertap/data/techno_economic/media_filtration.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_media_filtration_zo.py
Labels: Priority:High, wt3 migration

#367 Migrating WT3 cartridge filtration model
  watertap/data/techno_economic/cartridge_filtration.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/cartridge_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py
Labels: Priority:Normal, wt3 migration

#370 Migrating WT3 feed water tank
  watertap/data/techno_economic/feed_water_tank.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/feed_water_tank_zo.py
  watertap/unit_models/zero_order/tests/test_feed_water_tank_zo.py
Labels: Priority:Normal, wt3 migration

#375 Migrating WT3 landfill model
  watertap/data/techno_economic/landfill.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/landfill_zo.py
  watertap/unit_models/zero_order/tests/test_landfill_zo.py
Labels: Priority:High, wt3 migration

#364 Anaerobic MBR-MEC
  watertap/data/techno_economic/anaerobic_mbr_mec.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/anaerobic_mbr_mec_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_mbr_mec_zo.py
Labels: Priority:High, amo

#363 Migrating WT3 cooling supply unit
  watertap/data/techno_economic/cooling_supply.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/cooling_supply_zo.py
  watertap/unit_models/zero_order/tests/test_cooling_supply_zo.py
Labels: Priority:Normal, wt3 migration

#373 Use user-provided output name when applicable
  watertap/tools/parameter_sweep.py
  watertap/tools/tests/test_parameter_sweep.py
Labels: Priority:Normal

#377 Migrating WT3 buffer tank unit
  watertap/data/techno_economic/buffer_tank.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/buffer_tank_zo.py
  watertap/unit_models/zero_order/tests/test_buffer_tank_zo.py
Labels: Priority:High, wt3 migration

#372 WT3 backwash solids handling
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/backwash_solids_handling_zo.py
  watertap/unit_models/zero_order/tests/test_backwash_solids_handling_zo.py
Labels: Priority:High, wt3 migration

#374 WT3 municipal drinking unit
  watertap/data/techno_economic/municipal_drinking.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/municipal_drinking_zo.py
  watertap/unit_models/zero_order/tests/test_municipal_drinking_zo.py
Labels: Priority:High, wt3 migration

#376 WT3 Seawater onshore intake
  watertap/data/techno_economic/sw_onshore_intake.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/sw_onshore_intake_zo.py
  watertap/unit_models/zero_order/tests/test_sw_onshore_intake_zo.py
Labels: Priority:High, wt3 migration

#319 RO refactor
  docs/how_to_guides/how_to_scale_a_model.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  tutorials/reverse_osmosis_0D.ipynb
  watertap/conftest.py
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  watertap/examples/flowsheets/RO_with_energy_recovery/default_configuration.yaml
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_single_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/desalination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/examples/full_example.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/gypsum_saturation_index.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_0DRO.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/examples/flowsheets/lsrro/tests/test_lsrro.py
  watertap/unit_models/_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal, model dev team

#378 Migrate sludge_tank WT3 unit operation
  watertap/data/techno_economic/sludge_tank.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/sludge_tank_zo.py
  watertap/unit_models/zero_order/tests/test_sludge_tank_zo.py
Labels: wt3 migration

#380 Migrate WT3 co2_addition unit
  watertap/data/techno_economic/co2_addition.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/co2_addition_zo.py
  watertap/unit_models/zero_order/tests/test_co2_addition_zo.py
Labels: wt3 migration

#382 Migrate WT3 static_mixer model
  watertap/data/techno_economic/static_mixer.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/static_mixer_zo.py
  watertap/unit_models/zero_order/tests/test_static_mixer_zo.py
Labels: wt3 migration

#383 Migrating WT3 dissolved air flotation
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/dissolved_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_dissolved_air_flotation_zo.py
Labels: Priority:Normal, wt3 migration

#338 some simple docs for cloud EDB
  docs/how_to_guides/edb_api.rst
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/how_to_guides/how_to_use_EDB.rst
  docs/how_to_guides/how_to_use_apparent_and_true_chemical_species.rst
  docs/technical_reference/edb/index.rst
Labels: Priority:Normal

#389 Migrating WT3 microfiltration model
  watertap/data/techno_economic/microfiltration.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/microfiltration_zo.py
  watertap/unit_models/zero_order/tests/test_microfiltration_zo.py
Labels: Priority:Normal, wt3 migration

#385 Migrating WT3 landfill zld model
  watertap/data/techno_economic/landfill_zld.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/landfill_zld_zo.py
  watertap/unit_models/zero_order/tests/test_landfill_zld_zo.py
Labels: Priority:Normal, wt3 migration

#358 Initial Zero-order Coagulation-Flocculation Unit Model
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/tests/test_coag_prop_pack.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/tests/test_coag_floc_model.py
Labels: Priority:High, chem team

#388 add build_mass_conc function and modify generic prop config dict for …
  watertap/examples/flowsheets/full_treatment_train/analysis/oli_case_generation.py
  watertap/examples/flowsheets/full_treatment_train/model_components/eNRTL/entrl_config_FpcTP.py
Labels: enhancement, oli

#396 Migrating WT3 settling pond model
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/settling_pond_zo.py
  watertap/unit_models/zero_order/tests/test_settling_pond_zo.py
Labels: Priority:Normal, wt3 migration

#399 Migrating WT3 tramp oil tank
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/tramp_oil_tank.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_tramp_oil_tank_zo.py
  watertap/unit_models/zero_order/tramp_oil_tank_zo.py
Labels: Priority:Normal, wt3 migration

#386 Costing package for Zero Order models
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/tests/test_zero_order_electricity.py
  watertap/core/zero_order_base.py
  watertap/core/zero_order_costing.py
  watertap/core/zero_order_electricity.py
  watertap/data/techno_economic/catalyst_chemicals.csv
  watertap/data/techno_economic/chemical_addition.csv
  watertap/data/techno_economic/chemical_addition.yaml
  watertap/data/techno_economic/default_case_study.yaml
  watertap/data/techno_economic/nanofiltration.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/tests/test_aeration_basin_zo.py
  watertap/unit_models/zero_order/tests/test_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_digestion_oxidation_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_mbr_mec_zo.py
  watertap/unit_models/zero_order/tests/test_backwash_solids_handling_zo.py
  watertap/unit_models/zero_order/tests/test_bioreactor_zo.py
  watertap/unit_models/zero_order/tests/test_buffer_tank_zo.py
  watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_chemical_addition_zo.py
  watertap/unit_models/zero_order/tests/test_chlorination_zo.py
  watertap/unit_models/zero_order/tests/test_clarifier_zo.py
  watertap/unit_models/zero_order/tests/test_co2_addition_zo.py
  watertap/unit_models/zero_order/tests/test_cooling_supply_zo.py
  watertap/unit_models/zero_order/tests/test_decarbonator_zo.py
  watertap/unit_models/zero_order/tests/test_dissolved_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_dual_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_feed_water_tank_zo.py
  watertap/unit_models/zero_order/tests/test_fixed_bed_zo.py
  watertap/unit_models/zero_order/tests/test_gac_zo.py
  watertap/unit_models/zero_order/tests/test_ion_exchange_zo.py
  watertap/unit_models/zero_order/tests/test_landfill_zld_zo.py
  watertap/unit_models/zero_order/tests/test_landfill_zo.py
  watertap/unit_models/zero_order/tests/test_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_microfiltration_zo.py
  watertap/unit_models/zero_order/tests/test_microscreen_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_municipal_drinking_zo.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
  watertap/unit_models/zero_order/tests/test_primary_separator_zo.py
  watertap/unit_models/zero_order/tests/test_pump_zo.py
  watertap/unit_models/zero_order/tests/test_sedimentation_zo.py
  watertap/unit_models/zero_order/tests/test_settling_pond_zo.py
  watertap/unit_models/zero_order/tests/test_sludge_tank_zo.py
  watertap/unit_models/zero_order/tests/test_static_mixer_zo.py
  watertap/unit_models/zero_order/tests/test_sw_onshore_intake_zo.py
  watertap/unit_models/zero_order/tests/test_tramp_oil_tank_zo.py
  watertap/unit_models/zero_order/tests/test_tri_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_ultra_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_uv_aop_zo.py
  watertap/unit_models/zero_order/tests/test_uv_zo.py
  watertap/unit_models/zero_order/tests/test_vfa_recovery_zo.py
Labels: Priority:High, model dev team, nawi, wt3 migration

#404 First WT3 costing examples
  watertap/data/techno_economic/aeration_basin.yaml
  watertap/data/techno_economic/air_flotation.yaml
  watertap/data/techno_economic/anaerobic_digestion_oxidation.yaml
  watertap/data/techno_economic/backwash_solids_handling.yaml
  watertap/data/techno_economic/bioreactor.yaml
  watertap/unit_models/zero_order/aeration_basin_zo.py
  watertap/unit_models/zero_order/tests/test_aeration_basin_zo.py
  watertap/unit_models/zero_order/tests/test_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_digestion_oxidation_zo.py
  watertap/unit_models/zero_order/tests/test_backwash_solids_handling_zo.py
  watertap/unit_models/zero_order/tests/test_bioreactor_zo.py
  watertap/unit_models/zero_order/tests/test_chemical_addition_zo.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
Labels: Priority:High, nawi, wt3 migration

#405 Adding costing for models required for Santa Barbara case study
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/co2_addition.yaml
  watertap/data/techno_economic/pump.yaml
  watertap/data/techno_economic/static_mixer.yaml
  watertap/data/techno_economic/storage_tank.yaml
  watertap/data/techno_economic/sw_onshore_intake.yaml
  watertap/unit_models/zero_order/tests/test_bioreactor_zo.py
  watertap/unit_models/zero_order/tests/test_co2_addition_zo.py
  watertap/unit_models/zero_order/tests/test_pump_zo.py
  watertap/unit_models/zero_order/tests/test_static_mixer_zo.py
  watertap/unit_models/zero_order/tests/test_storage_tank_zo.py
  watertap/unit_models/zero_order/tests/test_sw_onshore_intake_zo.py
Labels: Priority:High, wt3 migration, costing

#409 Costing for WT3 chlorination unit
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/chlorination.yaml
  watertap/data/techno_economic/default_case_study.yaml
  watertap/unit_models/zero_order/chlorination_zo.py
  watertap/unit_models/zero_order/tests/test_chlorination_zo.py
Labels: Priority:High, nawi, wt3 migration, costing

#410 Migrating WT3 bio active filtration model
  watertap/data/techno_economic/bio_active_filtration.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/bio_active_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_bio_active_filtration_zo.py
Labels: Priority:Normal, wt3 migration, costing

#403 Add WT3 crystallizer as a subtype of brine concentrator
  watertap/data/techno_economic/brine_concentrator.yaml
  watertap/data/techno_economic/crystallizer.yaml
  watertap/unit_models/zero_order/brine_concentrator_zo.py
  watertap/unit_models/zero_order/tests/test_brine_concentrator_zo.py
Labels: Priority:Normal, wt3 migration

#411 Migrating WT3 blending reservoir model
  watertap/data/techno_economic/blending_reservoir.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/blending_reservoir_zo.py
  watertap/unit_models/zero_order/tests/test_blending_reservoir_zo.py
Labels: Priority:Normal, wt3 migration, costing

#415 Cleaning up ZO brine concentrator and adding costing
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/brine_concentrator.yaml
  watertap/unit_models/zero_order/brine_concentrator_zo.py
  watertap/unit_models/zero_order/tests/test_brine_concentrator_zo.py
Labels: Priority:High, nawi, wt3 migration, costing

#412 Migrating WT3 energy recovery model
  watertap/data/techno_economic/energy_recovery.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/energy_recovery_zo.py
  watertap/unit_models/zero_order/tests/test_energy_recovery_zo.py
Labels: Priority:Normal, wt3 migration, costing

#418 Migrating WT3 mbr model
  watertap/data/techno_economic/mbr.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/mbr_zo.py
  watertap/unit_models/zero_order/tests/test_mbr_zo.py
Labels: Priority:Normal, wt3 migration, costing

#416 More costing for zero order units
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/sedimentation.yaml
  watertap/data/techno_economic/settling_pond.yaml
  watertap/data/techno_economic/sludge_tank.yaml
  watertap/unit_models/zero_order/sedimentation_zo.py
  watertap/unit_models/zero_order/tests/test_sedimentation_zo.py
  watertap/unit_models/zero_order/tests/test_settling_pond_zo.py
  watertap/unit_models/zero_order/tests/test_sludge_tank_zo.py
Labels: Priority:High, nawi, wt3 migration, costing

#414 WT3 UV/UVAOP & Ozone/OzoneAOP Costing
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/default_case_study.yaml
  watertap/data/techno_economic/ozonation.yaml
  watertap/data/techno_economic/ozone_aop.yaml
  watertap/data/techno_economic/uv.yaml
  watertap/data/techno_economic/uv_aop.yaml
  watertap/unit_models/zero_order/ozone_aop_zo.py
  watertap/unit_models/zero_order/ozone_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_aop_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_zo.py
  watertap/unit_models/zero_order/tests/test_uv_aop_zo.py
  watertap/unit_models/zero_order/tests/test_uv_zo.py
Labels: Priority:High, wt3 migration, costing

#423 Migrating WT3 smp model
  watertap/data/techno_economic/smp.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/smp_zo.py
  watertap/unit_models/zero_order/tests/test_smp_zo.py
Labels: Priority:Normal, wt3 migration, costing

#420 Add costing model for primary separator
  watertap/data/techno_economic/primary_separator.yaml
  watertap/unit_models/zero_order/tests/test_primary_separator_zo.py
Labels: Priority:Normal, wt3 migration, costing

#392 WT3 Santa Barbara case
  watertap/examples/case_studies/seawater_RO_desalination/__init__.py
  watertap/examples/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/case_studies/seawater_RO_desalination/tests/__init__.py
  watertap/examples/case_studies/seawater_RO_desalination/tests/test_seawater_RO_desalination.py
Labels: Priority:High, wt3 migration

#417 Wt3 well field
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/well_field.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_well_field_zo.py
  watertap/unit_models/zero_order/well_field_zo.py
Labels: wt3 migration, costing

#421 Migrating WT3 screen model
  watertap/data/techno_economic/screen.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/screen_zo.py
  watertap/unit_models/zero_order/tests/test_screen_zo.py
Labels: Priority:Normal, wt3 migration, costing

#425 Migrating WT3 wind-aided intensified evaporation model
  watertap/data/techno_economic/waiv.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_waiv_zo.py
  watertap/unit_models/zero_order/waiv_zo.py
Labels: Priority:Normal, wt3 migration, costing

#430 Add costing model for WT3 landfill unit
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/landfill.yaml
  watertap/data/techno_economic/landfill_zld.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/landfill_zld_zo.py
  watertap/unit_models/zero_order/tests/test_landfill_zld_zo.py
  watertap/unit_models/zero_order/tests/test_landfill_zo.py
Labels: Priority:High, wt3 migration, costing

#407 Add costing model for WT3 unit models
  watertap/data/techno_economic/buffer_tank.yaml
  watertap/data/techno_economic/cartridge_filtration.yaml
  watertap/data/techno_economic/dissolved_air_flotation.yaml
  watertap/data/techno_economic/dual_media_filtration.yaml
  watertap/data/techno_economic/feed_water_tank.yaml
  watertap/data/techno_economic/media_filtration.yaml
  watertap/data/techno_economic/microscreen_filtration.yaml
  watertap/data/techno_economic/tri_media_filtration.yaml
  watertap/data/techno_economic/ultra_filtration.yaml
  watertap/unit_models/zero_order/tests/test_buffer_tank_zo.py
  watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_dissolved_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_dual_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_feed_water_tank_zo.py
  watertap/unit_models/zero_order/tests/test_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_microscreen_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_tri_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_ultra_filtration_zo.py
Labels: Priority:High, wt3 migration, costing

#432 Add some basic costing models
  watertap/data/techno_economic/clarifier.yaml
  watertap/data/techno_economic/cooling_supply.yaml
  watertap/data/techno_economic/decarbonator.yaml
  watertap/data/techno_economic/tramp_oil_tank.yaml
  watertap/unit_models/zero_order/tests/test_clarifier_zo.py
  watertap/unit_models/zero_order/tests/test_cooling_supply_zo.py
  watertap/unit_models/zero_order/tests/test_decarbonator_zo.py
  watertap/unit_models/zero_order/tests/test_tramp_oil_tank_zo.py
Labels: Priority:Normal, wt3 migration, costing

#433 Migrating WT3 walnut shell filter model
  watertap/data/techno_economic/walnut_shell_filter.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_walnut_shell_filter_zo.py
  watertap/unit_models/zero_order/walnut_shell_filter_zo.py
Labels: Priority:Normal, wt3 migration, costing

#427 Adding costing to Seawater RO example
  watertap/data/techno_economic/static_mixer.yaml
  watertap/data/techno_economic/storage_tank.yaml
  watertap/examples/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/case_studies/seawater_RO_desalination/tests/test_seawater_RO_desalination.py
Labels: Priority:High, nawi, wt3 migration, costing

#435 Migrating electrodialysis reversal model
  watertap/data/techno_economic/electrodialysis_reversal.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/electrodialysis_reversal_zo.py
  watertap/unit_models/zero_order/tests/test_electrodialysis_reversal_zo.py
Labels: Priority:High, wt3 migration, costing

#438 Modify electricity coefficients as variables for electrodialysis reversal model
  watertap/data/techno_economic/electrodialysis_reversal.yaml
  watertap/unit_models/zero_order/electrodialysis_reversal_zo.py
  watertap/unit_models/zero_order/tests/test_electrodialysis_reversal_zo.py
Labels: wt3 migration, costing

#437 Add costing model for microfiltration
  watertap/data/techno_economic/microfiltration.yaml
  watertap/unit_models/zero_order/tests/test_microfiltration_zo.py
Labels: Priority:Normal, wt3 migration, costing

#439 Add costing model for coagulation/flocculation unit
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/coag_and_floc.yaml
  watertap/unit_models/zero_order/coag_and_floc_zo.py
  watertap/unit_models/zero_order/tests/test_coag_and_floc_zo.py
Labels: Priority:Normal, wt3 migration, costing

#440 Migrating WT3 cooling tower model
  watertap/data/techno_economic/cooling_tower.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/cooling_tower_zo.py
  watertap/unit_models/zero_order/tests/test_cooling_tower_zo.py
Labels: Priority:Normal, wt3 migration, costing

#442 Migrating WT3 iron and manganese removal model
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/iron_and_manganese_removal.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/iron_and_manganese_removal_zo.py
  watertap/unit_models/zero_order/tests/test_iron_and_manganese_removal_zo.py
Labels: Priority:Normal, wt3 migration, costing

#445 Migrating WT3 deep well injection model
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/deep_well_injection.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/deep_well_injection_zo.py
  watertap/unit_models/zero_order/tests/test_deep_well_injection_zo.py
Labels: Priority:Normal, wt3 migration, costing

#441 WT3: Adding costing for GAC units
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/default_case_study.yaml
  watertap/data/techno_economic/fixed_bed.yaml
  watertap/data/techno_economic/gac.yaml
  watertap/unit_models/zero_order/fixed_bed_zo.py
  watertap/unit_models/zero_order/gac_zo.py
  watertap/unit_models/zero_order/tests/test_fixed_bed_zo.py
  watertap/unit_models/zero_order/tests/test_gac_zo.py
Labels: Priority:High, nawi, wt3 migration, costing

#448 add filter press model
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/filter_press.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/filter_press_zo.py
  watertap/unit_models/zero_order/tests/test_filter_press_zo.py
Labels: wt3 migration, costing

#395 Fixed minor error in EDB and cleaned up some comments/notes about pre-processing
  watertap/edb/data_model.py
  watertap/edb/db_api.py
  watertap/edb/tests/test_db_api.py
Labels: Priority:Low, chem team

#444 Wt3 evap pond
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/evaporation_pond.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/evaporation_pond_zo.py
  watertap/unit_models/zero_order/tests/test_evaporation_pond_zo.py
Labels: Priority:High, wt3 migration, costing

#408 Add 0-D crystallizer model
  watertap/examples/flowsheets/crystallization/sim_simple_crystallizer.py
  watertap/property_models/cryst_prop_pack.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/tests/test_crystallizer.py
Labels: Priority:High

#455 Fix broken links in Sphinx docs
  docs/background/what_is_watertap.rst
  docs/getting_started/install.rst
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/tutorials/index.rst
Labels: documentation, Priority:High

#453 Add documentation for running models in Python scripts
  docs/getting_started/install.rst
  docs/how_to_guides/how_to_run_models_in_a_py_script.rst
  docs/how_to_guides/index.rst
Labels: Priority:High

#460 Add Water Pumping Station
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/water_pumping_station.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_water_pumping_station_zo.py
  watertap/unit_models/zero_order/water_pumping_station_zo.py
Labels: Priority:High, wt3 migration, costing

#462 Add place for AMO cases to live
  watertap/examples/case_studies/wastewater_resource_recovery/__init__.py
Labels: Priority:High, amo

#452 Gas sparged membrane ZO
  watertap/data/techno_economic/gas_sparged_membrane.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/gas_sparged_membrane_zo.py
  watertap/unit_models/zero_order/tests/test_gas_sparged_membrane.py
Labels: Priority:High, amo

#459 WT3 surface discharge ZO model
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/surface_discharge.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/well_field.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/surface_discharge_zo.py
  watertap/unit_models/zero_order/tests/test_surface_discharge.py
Labels: Priority:High, wt3 migration, costing

#457 Municipal treatment case
  watertap/examples/case_studies/municipal_treatment/__init__.py
  watertap/examples/case_studies/municipal_treatment/municipal_treatment.py
  watertap/examples/case_studies/municipal_treatment/tests/test_municipal_treatment.py
  watertap/unit_models/zero_order/fixed_bed_zo.py
  watertap/unit_models/zero_order/ozone_zo.py
Labels: Priority:High, wt3 migration

#463 MABR and DMBR ZO
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/default_case_study.yaml
  watertap/data/techno_economic/dmbr.yaml
  watertap/data/techno_economic/mabr.yaml
  watertap/examples/case_studies/wastewater_resource_recovery/case_1598.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/dmbr_zo.py
  watertap/unit_models/zero_order/mabr_zo.py
  watertap/unit_models/zero_order/tests/test_dmbr_zo.py
  watertap/unit_models/zero_order/tests/test_mabr_zo.py
Labels: Priority:High, amo

#469 Revise default removal of TSS for cartridge filtration
  watertap/data/techno_economic/cartridge_filtration.yaml
  watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py
Labels: Priority:Normal, wt3 migration

#468 move case studies
  docs/apidoc/watertap.examples.case_studies.rst
  docs/apidoc/watertap.examples.rst
  watertap/examples/flowsheets/case_studies/__init__.py
  watertap/examples/flowsheets/case_studies/case_study_basis.csv
  watertap/examples/flowsheets/case_studies/case_study_water_sources.csv
  watertap/examples/flowsheets/case_studies/constituent_removal.csv
  watertap/examples/flowsheets/case_studies/electricity_costs.csv
  watertap/examples/flowsheets/case_studies/municipal_treatment/__init__.py
  watertap/examples/flowsheets/case_studies/municipal_treatment/municipal_treatment.py
  watertap/examples/flowsheets/case_studies/municipal_treatment/tests/__init__.py
  watertap/examples/flowsheets/case_studies/municipal_treatment/tests/test_municipal_treatment.py
  watertap/examples/flowsheets/case_studies/plant_cost_indices.csv
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/__init__.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/tests/__init__.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/tests/test_seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/treatment_train_setup.csv
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/case_1598.yaml
  watertap/examples/flowsheets/case_studies/water_recovery.csv
Labels: Priority:Normal

#472 account for TPEC and TIC factor in surface discharge costing
  watertap/core/zero_order_costing.py
Labels: wt3 migration, costing
