Repository watertap-org/watertap, pull requests merged in 2022-10, with the labels that each got.

#774 Electrodialysis 0D refinement
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
Labels: Priority:Normal, :cherries: Merge to rel

#744 Electrodialysis 1D refinement
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:Normal, :cherries: Merge to rel

#745 Electrodialysis 1D refinement- documentation update
  docs/_static/unit_models/elecdia.png
  docs/technical_reference/unit_models/electrodialysis_1D.rst
Labels: Priority:Normal, :cherries: Merge to rel

#768 Electrodialysis 0D documentation update
  docs/technical_reference/unit_models/electrodialysis_0D.rst
Labels: Priority:Normal, :cherries: Merge to rel

#754 Fix use of `.. doctest::` directive in documentation
  docs/how_to_guides/how_to_setup_RO_config_options.rst
  docs/how_to_guides/how_to_setup_simple_RO.rst
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/how_to_guides/how_to_use_a_property_model.rst
  docs/how_to_guides/how_to_use_apparent_and_true_chemical_species.rst
  docs/how_to_guides/how_to_use_inherent_reactions.rst
Labels: Priority:Normal

#790 Metab GUI Typo
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.py
Labels: amo, :cherries: Merge to rel, ui

#713 Remove examples directory
  examples/__init__.py
  examples/ui/__init__.py
  examples/ui/api_example.py
  examples/ui/api_example_bad.py
Labels: Priority:Normal

#789 Add GLSD Anaerobic digester model
  watertap/data/techno_economic/anaerobic_digestion_reactive.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/tests/test_GLSD_anaerobic_digestion.py
  watertap/unit_models/zero_order/anaerobic_digestion_reactive_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_digestion_reactive_zo.py
Labels: Priority:High, :cherries: Merge to rel

#794 adding cost_factor expression to unit costing block
  watertap/core/zero_order_costing.py
Labels: Priority:High, amo, :cherries: Merge to rel

#798 Resolve near-silent errors when building flowsheet interfaces with Param objects
  .github/workflows/checks.yml
  codecov.yml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_ui.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:High, :cherries: Merge to rel, ui

#799 ZO Documentation Check
  docs/technical_reference/unit_models/zero_order_unit_models/WT3_unit_classification_for_doc.xlsx
  docs/technical_reference/unit_models/zero_order_unit_models/anaerobic_digestion_reactive_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/automate_rst_file_wt3.py
  docs/technical_reference/unit_models/zero_order_unit_models/autothermal_hydrothermal_liquefaction_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/centrifuge_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/cloth_media_filtration_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/constructed_wetlands_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/hrcs_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/hydrothermal_gasification_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/index.rst
  docs/technical_reference/unit_models/zero_order_unit_models/magprex_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/membrane_evaporator_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/microbial_battery_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/peracetic_acid_disinfection_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/struvite_classifier_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/suboxic_activated_sludge_process_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/supercritical_salt_precipitation_zo.rst
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/clarifier_zo.py
  watertap/unit_models/zero_order/membrane_evaporator_zo.py
Labels: documentation, Priority:High, :cherries: Merge to rel

#803 Revise typo in MABR
  watertap/data/techno_economic/mabr.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/tests/test_biomembrane_filtration.py
  watertap/unit_models/zero_order/tests/test_mabr_zo.py
Labels: amo

#716 RO Membrane Channel Cleanup
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/reverse_osmosis_1D.rst
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  watertap/examples/flowsheets/RO_with_energy_recovery/default_configuration.yaml
  watertap/examples/flowsheets/RO_with_energy_recovery/mc_sweep_params.yaml
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/examples/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_single_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_0DRO.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_1DRO.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/examples/flowsheets/lsrro/multi_sweep.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal

#820 Remove unnecessary requirements file
  requirements.txt
Labels: Priority:Normal

#814 Normalize all line endings
  .gitattributes
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/make.bat
  docs/technical_reference/property_models/coagulation.rst
  docs/technical_reference/unit_models/boron_removal.rst
  docs/technical_reference/unit_models/coag_floc_model.rst
  watertap/examples/flowsheets/lsrro/tests/paper_analysis_baselines/10_nodes_A_5LMHbar_optimize_Bmax_nomax_125gL_35.0pct.csv
  watertap/examples/flowsheets/lsrro/tests/paper_analysis_baselines/10_nodes_A_5LMHbar_optimize_Bmax_nomax_35gL_70.0pct.csv
  watertap/examples/flowsheets/lsrro/tests/paper_analysis_baselines/10_nodes_A_5LMHbar_optimize_Bmax_nomax_70gL_55.00000000000001pct.csv
Labels: Priority:High, software admin

#827 Test NF stability across pressure and recovery rate range
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
Labels: Priority:Normal, model dev team, analysis team, nawi

#812 Example flowsheets for activated sludge processes d2
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM2D_flowsheet.py
  watertap/examples/flowsheets/case_studies/activated_sludge/tests/test_asm2d_flowsheet.py
  watertap/property_models/activated_sludge/asm2d_properties.py
  watertap/property_models/activated_sludge/asm2d_reactions.py
  watertap/property_models/activated_sludge/tests/test_asm2d_reaction.py
Labels: Priority:High

#828 Fixing deprecation warnings in seawater alkalinity tests
  watertap/examples/chemistry/tests/test_seawater_alkalinity.py
Labels: bug, Priority:Normal, chem team

#824 Revise the Getting Started section in the documentation
  docs/getting_started.rst
  docs/getting_started/index.rst
  docs/getting_started/install.rst
  docs/how_to_guides/how_to_install_electrolyte_database.rst
  docs/how_to_guides/index.rst
  docs/index.rst
Labels: documentation, Priority:High
