Repository watertap-org/watertap, pull requests merged in 2022-01, with the labels that each got.

#284 Updating the chemistry tests and docs
  docs/apidoc/watertap.examples.flowsheets.full_treatment_train.flowsheet_components.chemistry.rst
  docs/how_to_guides/edb_cli.rst
  docs/how_to_guides/how_to_scale_chemical_process_energy_balance.rst
  docs/how_to_guides/how_to_scale_chemical_reactions.rst
  docs/how_to_guides/how_to_scale_chemical_species.rst
  docs/how_to_guides/how_to_use_EDB.rst
  docs/how_to_guides/index.rst
  watertap/examples/chemistry/chem_scaling_utils.py
  watertap/examples/chemistry/tests/test_chlorination.py
  watertap/examples/chemistry/tests/test_enrtl_water_pH_edb.py
  watertap/examples/chemistry/tests/test_pH_dependent_solubility.py
  watertap/examples/chemistry/tests/test_phosphorus_removal.py
  watertap/examples/chemistry/tests/test_recarbonation_process.py
  watertap/examples/chemistry/tests/test_remineralization.py
  watertap/examples/chemistry/tests/test_solids.py
  watertap/examples/chemistry/tests/test_water_softening_Ca.py
  watertap/examples/chemistry/tests/test_water_softening_Mg.py
  watertap/examples/flowsheets/full_treatment_train/chemical_flowsheet_util.py
  watertap/examples/flowsheets/full_treatment_train/electrolyte_scaling_utils.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/PostTreatment_SimpleNaOCl_Chlorination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/PreTreatment_Simple_Softening.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/SepRO_plus_Chlorination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/ZeroDRO_plus_Chlorination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/pretreatment_stoich_softening_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/test_chlorination_example.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/test_posttreatment.py
Labels: chem team

#278 Adding outline of WT database class
  docs/technical_reference/core/zero_order_unit.rst
  setup.py
  watertap/core/tests/test_wt_database.py
  watertap/core/tests/test_zero_order_properties.py
  watertap/core/tests/test_zero_order_sido.py
  watertap/core/tests/test_zero_order_sito.py
  watertap/core/wt_database.py
  watertap/core/zero_order_properties.py
  watertap/core/zero_order_sido.py
  watertap/data/techno_economic/nanofiltration.yml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/nanofiltration_zo.py
  watertap/unit_models/zero_order/tests/__init__.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
Labels: Priority:Normal, nawi

#288 Adding zero-order Feed Block and extending database
  watertap/core/tests/test_wt_database.py
  watertap/core/tests/test_zero_order_properties.py
  watertap/core/wt_database.py
  watertap/core/zero_order_properties.py
  watertap/data/techno_economic/water_sources.yml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/feed_zo.py
  watertap/unit_models/zero_order/nanofiltration_zo.py
  watertap/unit_models/zero_order/tests/test_feed_zo.py
Labels: Priority:Normal, nawi

#285 Excise bound push pt 2
  watertap/core/plugins/solvers.py
  watertap/examples/chemistry/tests/test_solids.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_single_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_softening.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_softening_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/chemical_flowsheet_util.py
  watertap/examples/flowsheets/full_treatment_train/electrolyte_scaling_utils.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/pretreatment_stoich_softening_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/costing.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/desalination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/examples/full_example.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/pretreatment_NF.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/pretreatment_softening.py
  watertap/examples/flowsheets/full_treatment_train/model_components/eNRTL/test_enrtl.py
  watertap/examples/flowsheets/full_treatment_train/model_components/property_models.py
  watertap/examples/flowsheets/full_treatment_train/model_components/tests/test_prop_pack.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_0DRO.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_1DRO.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_ZONF.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_separator.py
  watertap/examples/flowsheets/full_treatment_train/util.py
  watertap/examples/flowsheets/lsrro/tests/test_lsrro.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
Labels: Priority:Normal

#292 Expanding zero-order water source database
  watertap/data/techno_economic/__init__.py
  watertap/data/techno_economic/tests/__init__.py
  watertap/data/techno_economic/tests/test_water_sources.py
  watertap/data/techno_economic/water_sources.yml
Labels: Priority:Normal, nawi

#283 Aligned RO Initialization and Scaling
  watertap/examples/flowsheets/lsrro/tests/test_lsrro.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/unit_models/_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal

#293 Drop support for Python 3.6
  .github/workflows/checks.yml
  setup.py
Labels: Priority:High

#294 Adding EDB docs and methods for available base configs
  docs/technical_reference/edb/index.rst
  watertap/edb/commands.py
  watertap/edb/data_model.py
  watertap/edb/db_api.py
  watertap/edb/tests/test_db_api.py
Labels: Priority:Normal

#303 Create codecov.yml
  codecov.yml
Labels: Priority:Normal, software admin

#290 Add CI check to test macOS experimental setup
  .github/workflows/checks.yml
  docs/getting_started/install.rst
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:High
