Repository watertap-org/watertap, pull requests merged in 2022-08, with the labels that each got.

#624 Add UV cost
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/tests/test_uv_aop.py
  watertap/unit_models/uv_aop.py
Labels: Priority:High, nawi

#637 Adding GAC costing package documentation to unit_model doc
  docs/technical_reference/unit_models/gac.rst
  watertap/costing/watertap_costing_package.py
Labels: Priority:Normal

#633 Example flowsheets for activated sludge processes
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM1_flowsheet.py
  watertap/examples/flowsheets/case_studies/activated_sludge/__init__.py
  watertap/examples/flowsheets/case_studies/activated_sludge/tests/__init__.py
  watertap/examples/flowsheets/case_studies/activated_sludge/tests/test_asm1_flowsheet.py
  watertap/property_models/activated_sludge/asm1_properties.py
  watertap/property_models/activated_sludge/tests/test_asm1_thermo.py
  watertap/unit_models/cstr_injection.py
  watertap/unit_models/tests/test_cstr_injection.py
Labels: Priority:Normal, WIP, amo

#632 Electrodialysis Flowsheet
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:Normal, chem team

#655 Full Metab Results
  watertap/data/techno_economic/metab.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/test_metab.py
  watertap/unit_models/zero_order/tests/test_metab_zo.py
Labels: Priority:High

#665 Update idaes-pse prerelease requirement to IDAES/idaes-pse#925
  setup.py
Labels: Priority:High

#670 Additions to the display of the dye desalination flowsheet example
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
Labels: amo

#667 Biomembrane filtration full report
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration.py
Labels: amo

#656 UI API simplification
  docs/conf.py
  docs/how_to_guides/how_to_use_ui_api.rst
  docs/technical_reference/ui/index.rst
  examples/__init__.py
  examples/ui/__init__.py
  examples/ui/api_example.py
  examples/ui/api_example_bad.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/ui/api.py
  watertap/ui/api_model.py
  watertap/ui/api_util.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_api.py
  watertap/ui/tests/test_fsapi.py
  watertap/unit_models/zero_order/feed_zo.py
  watertap/unit_models/zero_order/metab_zo.py
Labels: Priority:High

#674 Revise biomembrane filtration flowsheet
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/tests/test_biomembrane_filtration.py
Labels: Priority:High, amo

#668 DSPMDE property pack update
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
  watertap/unit_models/electrodialysis_1D.py
Labels: Priority:High

#654 Variable efficiency pump 0D
  watertap/unit_models/pressure_changer.py
  watertap/unit_models/tests/test_pressure_changer.py
Labels: Priority:Normal

#664 Correct zero order costs
  watertap/data/techno_economic/brine_concentrator.yaml
  watertap/data/techno_economic/electrodialysis_reversal.yaml
  watertap/data/techno_economic/iron_and_manganese_removal.yaml
  watertap/data/techno_economic/landfill.yaml
  watertap/data/techno_economic/mbr.yaml
  watertap/data/techno_economic/storage_tank.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/water_sources.yaml
  watertap/unit_models/zero_order/evaporation_pond_zo.py
  watertap/unit_models/zero_order/iron_and_manganese_removal_zo.py
  watertap/unit_models/zero_order/storage_tank_zo.py
  watertap/unit_models/zero_order/tests/test_iron_and_manganese_removal_zo.py
  watertap/unit_models/zero_order/tests/test_landfill_zo.py
Labels: Priority:Normal, wt3 migration

#626 GAC scaling revisions and other general enhancements
  docs/technical_reference/unit_models/gac.rst
  watertap/unit_models/gac.py
  watertap/unit_models/tests/test_gac.py
Labels: Priority:Normal

#662 Add detailed UV dose formula
  docs/technical_reference/unit_models/uv_aop.rst
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/tests/test_uv_aop.py
  watertap/unit_models/uv_aop.py
Labels: Priority:Normal, nawi

#693 Revise report for AMO 1614
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/tests/test_supercritical_sludge_to_gas.py
Labels: amo

#680 NF DSPM-DE cleanup, part 1/n
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
  watertap/unit_models/tests/test_pressure_changer.py
Labels: Priority:Normal, model dev team, nawi

#700 Replace zero-order UV and UV AOP models costing methods
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/uv.yaml
  watertap/data/techno_economic/uv_aop.yaml
  watertap/examples/flowsheets/case_studies/municipal_treatment/tests/test_municipal_treatment.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/tests/test_seawater_RO_desalination.py
  watertap/unit_models/zero_order/tests/test_uv_aop_zo.py
  watertap/unit_models/zero_order/tests/test_uv_zo.py
Labels: wt3 migration
