Repository watertap-org/watertap, pull requests merged in 2022-04, with the labels that each got.

#477 Low pressure pump model for AMO
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/pump_electricity.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/pump_electricity_zo.py
  watertap/unit_models/zero_order/tests/test_pump_electricity_zo.py
Labels: Priority:Normal, amo

#446 Streamline results storage within parameter_sweep.py
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  docs/technical_reference/tools/parameter_sweep.rst
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/examples/flowsheets/full_treatment_train/analysis/multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_multi_sweep.py
  watertap/tools/parameter_sweep.py
  watertap/tools/tests/test_parameter_sweep.py
Labels: Priority:High

#480 Zero-order NF subtype for dye rejection
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/wt_database.py
  watertap/core/zero_order_base.py
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/nanofiltration.yaml
  watertap/unit_models/zero_order/nanofiltration_zo.py
  watertap/unit_models/zero_order/pump_electricity_zo.py
  watertap/unit_models/zero_order/pump_zo.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
  watertap/unit_models/zero_order/tests/test_pump_electricity_zo.py
Labels: model dev team, amo, costing

#479 Photothermal membrane and CANDO+P ZO models
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/CANDO_P.yaml
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/photothermal_membrane.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/wastewater_default_case_study.yaml
  watertap/unit_models/zero_order/CANDOP_zo.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/photothermal_membrane_zo.py
  watertap/unit_models/zero_order/tests/test_CANDOP_zo.py
  watertap/unit_models/zero_order/tests/test_photothermal_membrane_zo.py
Labels: Priority:Normal

#486 Initial Sensitivity analyses incorporated for METAB
  watertap/core/tests/test_zero_order_sido_reactive.py
  watertap/core/zero_order_costing.py
  watertap/core/zero_order_sido_reactive.py
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/metab.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/multi_sweep.py
  watertap/tools/parameter_sweep.py
  watertap/unit_models/mvc/components/evaporator.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/metab_zo.py
  watertap/unit_models/zero_order/tests/test_metab_zo.py
Labels: amo

#487 Simplifying parameter sweep API
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  docs/technical_reference/tools/parameter_sweep.rst
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/examples/flowsheets/full_treatment_train/analysis/multi_sweep.py
  watertap/tools/parameter_sweep.py
  watertap/tools/tests/test_parameter_sweep.py
Labels: bug, Priority:High, analysis team

#494 Cleaning up YAML files for zero-order models
  .pre-commit-config.yaml
  watertap/data/techno_economic/agglom_stacking.yaml
  watertap/data/techno_economic/anti_oxidant_addition.yaml
  watertap/data/techno_economic/cartridge_filtration_with_backflush.yaml
  watertap/data/techno_economic/coagulant_addition.yaml
  watertap/data/techno_economic/coal_plant_cooling_tower.yaml
  watertap/data/techno_economic/deep_bed_filtration.yaml
  watertap/data/techno_economic/depr/anion_exchange_epa.yaml
  watertap/data/techno_economic/depr/ion_exchange.yaml
  watertap/data/techno_economic/depr/reverse_osmosis.yaml
  watertap/data/techno_economic/depr/ro_deep.yaml
  watertap/data/techno_economic/depr/ro_deep_guo.yaml
  watertap/data/techno_economic/depr/ro_deep_mcgivney.yaml
  watertap/data/techno_economic/depr/ro_deep_scnd_pass.yaml
  watertap/data/techno_economic/direct_injection.yaml
  watertap/data/techno_economic/electro_deionization.yaml
  watertap/data/techno_economic/engineered_buffer_with_chloramine.yaml
  watertap/data/techno_economic/engineered_buffer_with_chlorine.yaml
  watertap/data/techno_economic/fluidized_bed.yaml
  watertap/data/techno_economic/heap_leaching.yaml
  watertap/data/techno_economic/holding_tank.yaml
  watertap/data/techno_economic/injection_well.yaml
  watertap/data/techno_economic/lime_softening.yaml
  watertap/data/techno_economic/mbr_denitrification.yaml
  watertap/data/techno_economic/mbr_nitrification.yaml
  watertap/data/techno_economic/multi_stage_bubble_aeration.yaml
  watertap/data/techno_economic/nuclear_cooling_tower.yaml
  watertap/data/techno_economic/onsite_storage.yaml
  watertap/data/techno_economic/packed_tower_aeration.yaml
  watertap/data/techno_economic/passthrough.yaml
  watertap/data/techno_economic/ph_decrease.yaml
  watertap/data/techno_economic/ph_increase.yaml
  watertap/data/techno_economic/soil_aquifer_treatment.yaml
  watertap/data/techno_economic/solution_distribution_and_recovery_plant.yaml
  watertap/data/techno_economic/surface_augmentation.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/tri_media_filtration_with_backflush.yaml
Labels: Priority:Normal, nawi, wt3 migration

#483 Add documentation files for crystallization
  docs/_static/unit_models/crystallizer.jpg
  docs/technical_reference/unit_models/crystallizer_0D.rst
  docs/technical_reference/unit_models/index.rst
  watertap/unit_models/crystallizer.py
Labels: documentation, Priority:Normal, model dev team, nawi

#493 Metab flowsheet 2
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  docs/technical_reference/tools/parameter_sweep.rst
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/analysis/multi_sweep.py
  watertap/tools/parameter_sweep.py
  watertap/tools/tests/test_parameter_sweep.py
  watertap/unit_models/zero_order/aeration_basin_zo.py
  watertap/unit_models/zero_order/air_flotation_zo.py
  watertap/unit_models/zero_order/anaerobic_digestion_oxidation_zo.py
  watertap/unit_models/zero_order/blending_reservoir_zo.py
  watertap/unit_models/zero_order/buffer_tank_zo.py
  watertap/unit_models/zero_order/cartridge_filtration_zo.py
  watertap/unit_models/zero_order/clarifier_zo.py
  watertap/unit_models/zero_order/coag_and_floc_zo.py
  watertap/unit_models/zero_order/cooling_supply_zo.py
  watertap/unit_models/zero_order/decarbonator_zo.py
  watertap/unit_models/zero_order/deep_well_injection_zo.py
  watertap/unit_models/zero_order/dissolved_air_flotation_zo.py
  watertap/unit_models/zero_order/dual_media_filtration_zo.py
  watertap/unit_models/zero_order/energy_recovery_zo.py
  watertap/unit_models/zero_order/feed_water_tank_zo.py
  watertap/unit_models/zero_order/feed_zo.py
  watertap/unit_models/zero_order/fixed_bed_zo.py
  watertap/unit_models/zero_order/gac_zo.py
  watertap/unit_models/zero_order/gas_sparged_membrane_zo.py
  watertap/unit_models/zero_order/ion_exchange_zo.py
  watertap/unit_models/zero_order/iron_and_manganese_removal_zo.py
  watertap/unit_models/zero_order/landfill_zo.py
  watertap/unit_models/zero_order/mbr_zo.py
  watertap/unit_models/zero_order/media_filtration_zo.py
  watertap/unit_models/zero_order/metab_zo.py
  watertap/unit_models/zero_order/microfiltration_zo.py
  watertap/unit_models/zero_order/microscreen_filtration_zo.py
  watertap/unit_models/zero_order/municipal_drinking_zo.py
  watertap/unit_models/zero_order/municipal_wwtp_zo.py
  watertap/unit_models/zero_order/ozone_aop_zo.py
  watertap/unit_models/zero_order/sedimentation_zo.py
  watertap/unit_models/zero_order/tests/test_metab_zo.py
  watertap/unit_models/zero_order/tri_media_filtration_zo.py
  watertap/unit_models/zero_order/ultra_filtration_zo.py
  watertap/unit_models/zero_order/uv_aop_zo.py
  watertap/unit_models/zero_order/uv_zo.py
  watertap/unit_models/zero_order/vfa_recovery_zo.py
Labels: amo

#443 Adding power usage / performance equations to Coagulation-Flocculation
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/tests/test_coag_prop_pack.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/tests/test_coag_floc_model.py
Labels: Priority:Normal, chem team

#450 Documentation for Coagulation/Flocculation
  docs/_static/unit_models/coagulation_flocculation.png
  docs/technical_reference/property_models/coagulation.rst
  docs/technical_reference/property_models/index.rst
  docs/technical_reference/unit_models/coag_floc_model.rst
  docs/technical_reference/unit_models/index.rst
Labels: documentation, Priority:Normal, chem team

#501 Updating all naming conventions in ion_prop_pack
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
Labels: enhancement, Priority:High, chem team, property_model

#500 How-To Guide for Using a Property Model
  docs/how_to_guides/how_to_use_a_property_model.rst
  docs/how_to_guides/index.rst
Labels: documentation

#512 Use new tag on our idea-pse fork: 1.14.0dev0.watertap.2022.04.16
  setup.py
Labels: Priority:Normal
