Repository watertap-org/watertap, pull requests merged in 2022-12, with the labels that each got.

#835 Reorganzing the WaterTAP Costing Package
  watertap/costing/__init__.py
  watertap/costing/tests/test_util.py
  watertap/costing/tests/test_watertap_costing_package.py
  watertap/costing/units/__init__.py
  watertap/costing/units/crystallizer.py
  watertap/costing/units/electrodialysis.py
  watertap/costing/units/energy_recovery_device.py
  watertap/costing/units/gac.py
  watertap/costing/units/ion_exchange.py
  watertap/costing/units/mixer.py
  watertap/costing/units/nanofiltration.py
  watertap/costing/units/pressure_exchanger.py
  watertap/costing/units/pump.py
  watertap/costing/units/reverse_osmosis.py
  watertap/costing/units/tests/test_configuration_errors.py
  watertap/costing/units/uv_aop.py
  watertap/costing/util.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/crystallization/sim_simple_crystallizer.py
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/unit_models/tests/test_crystallizer.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
  watertap/unit_models/tests/test_uv_aop.py
Labels: Priority:High

#859 update tutorials
  .github/workflows/checks.yml
  setup.py
  tutorials/introduction.ipynb
  tutorials/reverse_osmosis_0D.ipynb
  watertap/tests/test_notebooks.py
Labels: bug, Priority:High

#862 Update idaes-pse requirement to 2.0.0b2
  setup.py
  watertap/unit_models/cstr_injection.py
Labels: Priority:High

#866 Unifying meaning of total_capital_cost across costing packages
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/RO_with_energy_recovery/default_configuration.yaml
  watertap/examples/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/examples/flowsheets/full_treatment_train/analysis/multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/costing.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/examples/flowsheets/lsrro/multi_sweep.py
  watertap/unit_models/tests/test_crystallizer.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:Normal

#863 Fix crystallizer documentation
  docs/technical_reference/unit_models/crystallizer_0D.rst
Labels: Priority:High

#845 Isothermal constraint
  watertap/core/__init__.py
  watertap/core/control_volume_isothermal.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/unit_models/boron_removal.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/gac.py
  watertap/unit_models/nanofiltration_ZO.py
  watertap/unit_models/pressure_exchanger.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
  watertap/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_nanofiltration_ZO.py
  watertap/unit_models/tests/test_pressure_exchanger.py
Labels: Priority:Normal

#855 Ion exchange initialization
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:High

#865 Adding more control for defined flows
  watertap/costing/tests/test_watertap_costing_package.py
  watertap/costing/units/crystallizer.py
  watertap/costing/units/ion_exchange.py
  watertap/costing/units/mixer.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
  watertap/examples/flowsheets/lsrro/lsrro.py
Labels: Priority:High

#861 Additional limiting current density methods for ED_1D
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:Normal
