Repository watertap-org/watertap, pull requests merged in 2022-02, with the labels that each got.

#318 Correct scaling factors for MW, ``molality_comp`` and ``flow_mol_phase_comp``
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
Labels: bug

#311 Ion property package
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
Labels: Priority:High, nawi, property_model

#324 Ensure ipopt-watertap leaves model unchanged
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
Labels: Priority:High

#321 NaCl S-L-V property package for crystallization
  setup.py
  watertap/property_models/cryst_prop_pack.py
  watertap/property_models/tests/test_cryst_prop_pack.py
Labels: Priority:High

#332 Migrating WT3 Coagulation/Flocculation Unit
  watertap/core/zero_order_electricity.py
  watertap/core/zero_order_properties.py
  watertap/data/techno_economic/coag_and_floc.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/coag_and_floc_zo.py
  watertap/unit_models/zero_order/tests/test_coag_and_floc_zo.py
Labels: amo, nawi, wt3 migration

#334 Reference bound relax fix
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
  watertap/examples/chemistry/tests/test_pH_dependent_solubility.py
  watertap/examples/chemistry/tests/test_solids.py
Labels: Priority:High

#322 Initial Coagulation/Flocculation Property Package
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/tests/test_coag_prop_pack.py
Labels: Priority:High, chem team

#335 SISO class & UV-AOP ZO Model
  watertap/core/__init__.py
  watertap/core/tests/test_zero_order_siso.py
  watertap/core/zero_order_base.py
  watertap/core/zero_order_siso.py
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/uv.yaml
  watertap/data/techno_economic/uv_aop.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_uv_aop_zo.py
  watertap/unit_models/zero_order/tests/test_uv_zo.py
  watertap/unit_models/zero_order/uv_aop_zo.py
  watertap/unit_models/zero_order/uv_zo.py
Labels: Priority:Normal, nawi, wt3 migration

#344 WT3 Unit Migration: Ion Exchange
  watertap/core/zero_order_properties.py
  watertap/data/techno_economic/anion_exchange.yaml
  watertap/data/techno_economic/cation_exchange.yaml
  watertap/data/techno_economic/ion_exchange.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/ion_exchange_zo.py
  watertap/unit_models/zero_order/tests/test_ion_exchange_zo.py
Labels: Priority:Normal, wt3 migration

#340 Adding methods for zero order reactive separators
  docs/technical_reference/core/sido_methods.rst
  docs/technical_reference/core/sidor_methods.rst
  docs/technical_reference/core/zo_form_libraries.rst
  watertap/core/__init__.py
  watertap/core/tests/test_sidor_data.yaml
  watertap/core/tests/test_zero_order_sido_reactive.py
  watertap/core/zero_order_base.py
  watertap/core/zero_order_sido_reactive.py
Labels: Priority:High, model dev team, amo

#345 Migrating WT3 dual media filtration model
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/dual_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_dual_media_filtration_zo.py
Labels: Priority:Normal, wt3 migration

#348 Migrate WT3 ozonation and ozone_aop unit models.
  watertap/data/techno_economic/ozonation.yaml
  watertap/data/techno_economic/ozone_aop.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/ozone_aop_zo.py
  watertap/unit_models/zero_order/ozone_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_aop_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_zo.py
Labels: Priority:High, wt3 migration

#301 Parameter sweep refine
  .gitignore
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  setup.py
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  watertap/examples/flowsheets/RO_with_energy_recovery/default_configuration.yaml
  watertap/examples/flowsheets/RO_with_energy_recovery/mc_sweep_params.yaml
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/examples/flowsheets/RO_with_energy_recovery/tests/test_monte_carlo_sampling_RO_ERD.py
  watertap/tools/parameter_sweep.py
  watertap/tools/parameter_sweep_input_parser.py
  watertap/tools/tests/test_parameter_sweep.py
  watertap/tools/tests/test_parameter_sweep_input_parser.py
Labels: Priority:High

#336 Update default bound relax factor
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
  watertap/examples/chemistry/tests/test_pH_dependent_solubility.py
  watertap/examples/chemistry/tests/test_remineralization.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_flowsheets.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/property_models/tests/test_cryst_prop_pack.py
Labels: Priority:Normal

#339 Add pytest marker to mark tests requiring IDAES solvers
  watertap/conftest.py
Labels: Priority:Normal

#346 WT3 Fixed Bed Unit
  watertap/data/techno_economic/fixed_bed.yaml
  watertap/data/techno_economic/fixed_bed_gravity_basin.yaml
  watertap/data/techno_economic/fixed_bed_pressure_vessel.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/fixed_bed_zo.py
  watertap/unit_models/zero_order/tests/test_fixed_bed_zo.py
Labels: Priority:Normal, wt3 migration

#349 Migrating WT3 GAC unit
  watertap/data/techno_economic/fixed_bed.yaml
  watertap/data/techno_economic/gac.yaml
  watertap/data/techno_economic/gac_gravity.yaml
  watertap/data/techno_economic/gac_gravity_60_min.yaml
  watertap/data/techno_economic/gac_pressure_30_min.yaml
  watertap/data/techno_economic/gac_pressure_vessel.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/gac_zo.py
  watertap/unit_models/zero_order/tests/test_gac_zo.py
Labels: Priority:Normal, wt3 migration

#351 WT3 brine concentrator
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/brine_concentrator_zo.py
  watertap/unit_models/zero_order/tests/test_brine_concentrator_zo.py
Labels: Priority:High, wt3 migration

#353 Migrating WT3 air flotation unit
  watertap/data/techno_economic/air_flotation.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_digestion_oxidation_zo.py
Labels: Priority:Normal, wt3 migration

#352 WT3 Chlorination migration
  watertap/data/techno_economic/chlorination.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/chlorination_zo.py
  watertap/unit_models/zero_order/tests/test_chlorination_zo.py
Labels: wt3 migration

#355 WT3 Aeration Basin
  watertap/data/techno_economic/aeration_basin.yaml
  watertap/data/techno_economic/aeration_tank.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/aeration_basin_zo.py
  watertap/unit_models/zero_order/tests/test_aeration_basin_zo.py
Labels: Priority:High, amo, wt3 migration

#356 WT3 treated storage
  watertap/data/techno_economic/ozonation.yaml
  watertap/data/techno_economic/ozone_aop.yaml
  watertap/data/techno_economic/storage_tank.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/treated_storage.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/ozone_zo.py
  watertap/unit_models/zero_order/storage_tank_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_aop_zo.py
  watertap/unit_models/zero_order/tests/test_ozone_zo.py
  watertap/unit_models/zero_order/tests/test_storage_tank_zo.py
Labels: wt3 migration

#357 General 0-Order VFA Recovery Unit
  watertap/data/techno_economic/aeration_basin.yaml
  watertap/data/techno_economic/component_list.yaml
  watertap/data/techno_economic/vfa_recovery.yaml
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/tests/test_vfa_recovery_zo.py
  watertap/unit_models/zero_order/vfa_recovery_zo.py
Labels: Priority:High, amo

#359 Quick Revision of Ion Property Model for DSPM
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
Labels: Priority:Normal, property_model

#315 Add first pass of tests for EDB CLI
  watertap/edb/commands.py
  watertap/edb/db_api.py
  watertap/edb/tests/test_commands.py
Labels: Priority:Normal
