Repository watertap-org/watertap, pull requests merged in 2022-07, with the labels that each got.

#602 Refine NF-DSPMDE documentation
  docs/technical_reference/unit_models/nanofiltration_dspmde_0D.rst
Labels: documentation, Priority:High, nawi

#564 Updating property names to better follow standards
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  watertap/examples/flowsheets/RO_with_energy_recovery/default_configuration.yaml
  watertap/property_models/NDMA_prop_pack.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/cryst_prop_pack.py
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/tests/test_NDMA_prop_pack.py
  watertap/property_models/tests/test_NaCl_prop_pack.py
  watertap/property_models/tests/test_coag_prop_pack.py
  watertap/property_models/tests/test_cryst_prop_pack.py
  watertap/property_models/tests/test_ion_DSPMDE_prop_pack.py
  watertap/property_models/tests/test_seawater_prop_pack.py
  watertap/property_models/tests/test_water_prop_pack.py
  watertap/property_models/water_prop_pack.py
  watertap/unit_models/_reverse_osmosis_base.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/tests/test_crystallizer.py
  watertap/unit_models/tests/test_nanofiltration_0D.py
Labels: Priority:Normal

#603 Simple example
  watertap/examples/custom_model_demo/__init__.py
  watertap/examples/custom_model_demo/demo_simple_filter.py
  watertap/examples/custom_model_demo/demo_simple_prop_pack.py
  watertap/examples/custom_model_demo/simple_filter.py
  watertap/examples/custom_model_demo/simple_prop_pack.py
  watertap/examples/custom_model_demo/tests/__init__.py
  watertap/examples/custom_model_demo/tests/test_demo_simple_filter.py
  watertap/examples/custom_model_demo/tests/test_demo_simple_prop_pack.py
Labels: Priority:High

#604 ASM2D documentation
  docs/technical_reference/property_models/ASM1.rst
  docs/technical_reference/property_models/ASM2D.rst
  docs/technical_reference/property_models/index.rst
  watertap/property_models/activated_sludge/asm2d_reactions.py
Labels: documentation, Priority:High, amo, :cherries: Merge to rel

#606 AMO Swine wastewater treatment flowsheet
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/anaerobic_mbr_mec.yaml
  watertap/data/techno_economic/cofermentation.yaml
  watertap/data/techno_economic/constructed_wetlands.yaml
  watertap/data/techno_economic/default_case_study.yaml
  watertap/data/techno_economic/ion_exchange.yaml
  watertap/data/techno_economic/sedimentation.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/data/techno_economic/vfa_recovery.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/tests/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/tests/test_multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/tests/test_swine_wwt.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/anaerobic_mbr_mec_zo.py
  watertap/unit_models/zero_order/cofermentation_zo.py
  watertap/unit_models/zero_order/gas_sparged_membrane_zo.py
  watertap/unit_models/zero_order/ion_exchange_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_mbr_mec_zo.py
  watertap/unit_models/zero_order/tests/test_cofermentation_zo.py
  watertap/unit_models/zero_order/tests/test_constructed_wetlands_zo.py
  watertap/unit_models/zero_order/tests/test_ion_exchange_zo.py
  watertap/unit_models/zero_order/tests/test_sedimentation_zo.py
  watertap/unit_models/zero_order/tests/test_vfa_recovery_zo.py
  watertap/unit_models/zero_order/vfa_recovery_zo.py
Labels: Priority:Normal, amo, costing

#619 Remove get_costing functions
  watertap/unit_models/_reverse_osmosis_base.py
  watertap/unit_models/gac.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/nanofiltration_ZO.py
  watertap/unit_models/pressure_exchanger.py
  watertap/unit_models/uv_aop.py
Labels: Priority:Normal

#570 Change small positive bounds to 0
  watertap/core/zero_order_diso.py
  watertap/core/zero_order_sido.py
  watertap/core/zero_order_sido_reactive.py
  watertap/core/zero_order_siso.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/pretreatment_stoich_softening_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/gypsum_saturation_index.py
  watertap/examples/flowsheets/full_treatment_train/model_components/seawater_ion_prop_pack.py
  watertap/examples/flowsheets/full_treatment_train/model_components/seawater_salt_prop_pack.py
  watertap/examples/flowsheets/lsrro/tests/parameter_sweep_baselines/1_stage_results_LSRRO.csv
  watertap/examples/flowsheets/lsrro/tests/parameter_sweep_baselines/2_stage_results_LSRRO.csv
  watertap/examples/flowsheets/lsrro/tests/parameter_sweep_baselines/3_stage_results_LSRRO.csv
  watertap/examples/flowsheets/lsrro/tests/parameter_sweep_baselines/4_stage_results_LSRRO.csv
  watertap/examples/flowsheets/lsrro/tests/parameter_sweep_baselines/5_stage_results_LSRRO.csv
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/water_prop_pack.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/mvc/components/compressor.py
  watertap/unit_models/mvc/components/evaporator.py
  watertap/unit_models/mvc/components/tests/test_complete_condenser.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/nanofiltration_ZO.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/zero_order/gas_sparged_membrane_zo.py
Labels: Priority:Normal

#540 Parameter Sweep Tool: resetting variable values before reinitialization
  watertap/tools/parameter_sweep.py
  watertap/tools/tests/test_parameter_sweep.py
Labels: Priority:Normal

#623 Simple fix to remove _get_performance_contents from ED costing
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
Labels: Priority:Normal, nawi

#631 Add ability to specify a separate probe function within parameter sweep
  watertap/tools/parameter_sweep.py
  watertap/tools/recursive_parameter_sweep.py
  watertap/tools/tests/test_parameter_sweep.py
Labels: Priority:Normal

#630 Workshop tutorial merge
  tutorials/RO_ERD_flowsheet.png
  tutorials/aeesp_workshop_tutorial.ipynb
  tutorials/demo_properties.py
  tutorials/generate_pyomo_example_plot.py
  tutorials/pyomo_example.png
  tutorials/pyomo_solution.png
  tutorials/workshop_flowsheet.py
  watertap/examples/chemistry/tests/test_tutorials.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_api.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/tests/test_metab_api.py
  watertap/ui/api.py
  watertap/ui/api_model.py
  watertap/ui/tests/test_api.py
Labels: Priority:High

#617 GAC Costing Package
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/__init__.py
  watertap/unit_models/tests/test_gac.py
Labels: Priority:Normal

#635 adding some docstrings to the infeasibility module
  watertap/core/util/infeasible.py
Labels: Priority:Normal
