Repository watertap-org/watertap, pull requests merged in 2022-11, with the labels that each got.

#831 OARO Unit Model Documentation
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/osmotically_assisted_reverse_osmosis_0D.rst
Labels: documentation

#788 Custom Ipopt options for LPs
  watertap/core/plugins/solvers.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690.py
  watertap/unit_models/zero_order/tests/test_aeration_basin_zo.py
  watertap/unit_models/zero_order/tests/test_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_digestion_oxidation_zo.py
  watertap/unit_models/zero_order/tests/test_anaerobic_mbr_mec_zo.py
  watertap/unit_models/zero_order/tests/test_autothermal_hydrothermal_liquefaction_zo.py
  watertap/unit_models/zero_order/tests/test_bio_active_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_blending_reservoir_zo.py
  watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_centrifuge_zo.py
  watertap/unit_models/zero_order/tests/test_cofermentation_zo.py
  watertap/unit_models/zero_order/tests/test_conventional_activated_sludge_zo.py
  watertap/unit_models/zero_order/tests/test_cooling_tower_zo.py
  watertap/unit_models/zero_order/tests/test_dissolved_air_flotation_zo.py
  watertap/unit_models/zero_order/tests/test_dmbr_zo.py
  watertap/unit_models/zero_order/tests/test_electrochemical_nutrient_removal_zo.py
  watertap/unit_models/zero_order/tests/test_hrcs_zo.py
  watertap/unit_models/zero_order/tests/test_magprex_zo.py
  watertap/unit_models/zero_order/tests/test_microbial_battery_zo.py
  watertap/unit_models/zero_order/tests/test_microfiltration_zo.py
  watertap/unit_models/zero_order/tests/test_microscreen_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_municipal_wwtp_zo.py
  watertap/unit_models/zero_order/tests/test_primary_separator_zo.py
  watertap/unit_models/zero_order/tests/test_screen_zo.py
  watertap/unit_models/zero_order/tests/test_secondary_treatment_wwtp_zo.py
  watertap/unit_models/zero_order/tests/test_settling_pond_zo.py
  watertap/unit_models/zero_order/tests/test_sludge_tank_zo.py
  watertap/unit_models/zero_order/tests/test_smp_zo.py
  watertap/unit_models/zero_order/tests/test_struvite_classifier_zo.py
  watertap/unit_models/zero_order/tests/test_tri_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_ultra_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_vfa_recovery_zo.py
  watertap/unit_models/zero_order/tests/test_waiv_zo.py
  watertap/unit_models/zero_order/tests/test_walnut_shell_filter_zo.py
Labels: Priority:Normal

#818 Adds InitializationError to Unit Models
  watertap/unit_models/boron_removal.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/gac.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/nanofiltration_ZO.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/pressure_exchanger.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/uv_aop.py
Labels: Priority:Normal

#839 Initialization mixin
  watertap/core/__init__.py
  watertap/core/initialization_mixin.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/unit_models/boron_removal.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/cstr_injection.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/gac.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/mvc/components/complete_condenser.py
  watertap/unit_models/mvc/components/compressor.py
  watertap/unit_models/mvc/components/evaporator.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/nanofiltration_ZO.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/pressure_changer.py
  watertap/unit_models/pressure_exchanger.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/uv_aop.py
  watertap/unit_models/zero_order/feed_zo.py
Labels: Priority:Normal

#834 Initial commit on BPE equation in seawater property package
  docs/technical_reference/property_models/seawater.rst
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/tests/test_seawater_prop_pack.py
Labels: Priority:Normal

#817 Update idaes-pse prerelease requirement to watertap-org:2.0.0.dev4.watertap.22.10.13
  docs/examples/edb/simple_acid_example.ipynb
  docs/how_to_guides/how_to_run_models_in_a_py_script.rst
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/how_to_guides/how_to_use_a_property_model.rst
  docs/how_to_guides/how_to_use_apparent_and_true_chemical_species.rst
  docs/how_to_guides/how_to_use_inherent_reactions.rst
  docs/technical_reference/core/water_props.rst
  docs/technical_reference/core/zero_order_costing.rst
  docs/technical_reference/property_models/NaCl.rst
  docs/technical_reference/property_models/coagulation.rst
  docs/technical_reference/property_models/seawater.rst
  docs/technical_reference/unit_models/boron_removal.rst
  docs/technical_reference/unit_models/coag_floc_model.rst
  setup.py
  watertap/core/zero_order_costing.py
  watertap/edb/data/component.json
  watertap/edb/data_model.py
  watertap/examples/chemistry/tests/test_chlorination.py
  watertap/examples/chemistry/tests/test_enrtl_water_pH.py
  watertap/examples/chemistry/tests/test_pure_water_pH.py
  watertap/examples/chemistry/tests/test_recarbonation_process.py
  watertap/examples/chemistry/tests/test_remineralization.py
  watertap/examples/chemistry/tests/test_water_softening.py
  watertap/examples/flowsheets/case_studies/municipal_treatment/municipal_treatment.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_ui.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/pretreatment_stoich_softening_block.py
  watertap/unit_models/cstr_injection.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/tests/test_cstr_injection.py
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
Labels: Priority:High

#840 Add reference text and citation file
  CITATION.cff
  README.md
  docs/index.rst
Labels: documentation, Priority:High, software admin

#846 Isothermal 0DRO
  watertap/core/membrane_channel1d.py
  watertap/core/membrane_channel_base.py
  watertap/examples/flowsheets/RO_with_energy_recovery/default_configuration.yaml
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/tests/test_seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/examples/test_full_example.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:High

#841 OARO Modeling & Initialization
  watertap/core/membrane_channel0d.py
  watertap/core/membrane_channel1d.py
  watertap/core/membrane_channel_base.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
Labels: Priority:High

#808 Seawater Ion Generic Documentation
  docs/technical_reference/property_models/index.rst
  docs/technical_reference/property_models/seawater_ion_generic.rst
Labels: documentation, Priority:Normal

#829 OARO flowsheet
  watertap/examples/flowsheets/oaro/__init__.py
  watertap/examples/flowsheets/oaro/oaro.py
  watertap/examples/flowsheets/oaro/tests/__init__.py
  watertap/examples/flowsheets/oaro/tests/test_oaro.py
Labels: Priority:Normal

#852 fixing getting started links in README
  README.md
Labels: Priority:Normal

#836 Remove idaes solver directives
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
  watertap/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
  watertap/unit_models/tests/test_uv_aop.py
  watertap/unit_models/zero_order/tests/test_autothermal_hydrothermal_liquefaction_zo.py
  watertap/unit_models/zero_order/tests/test_electrochemical_nutrient_removal_zo.py
  watertap/unit_models/zero_order/tests/test_gas_sparged_membrane.py
  watertap/unit_models/zero_order/tests/test_hydrothermal_gasification_zo.py
  watertap/unit_models/zero_order/tests/test_mabr_zo.py
  watertap/unit_models/zero_order/tests/test_metab_zo.py
  watertap/unit_models/zero_order/tests/test_supercritical_salt_precipitation_zo.py
Labels: Priority:Normal

#806 Differential Parameter Sweep Sampling
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  watertap/examples/flowsheets/RO_with_energy_recovery/mc_sweep_params.yaml
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/tools/parameter_sweep/__init__.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_differential.py
  watertap/tools/parameter_sweep/parameter_sweep_functions.py
  watertap/tools/parameter_sweep/parameter_sweep_reader.py
  watertap/tools/parameter_sweep/parameter_sweep_writer.py
  watertap/tools/parameter_sweep/sampling_types.py
  watertap/tools/parameter_sweep/tests/test_differential_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_reader.py
  watertap/tools/parameter_sweep/tests/test_recursive_parameter_sweep.py
Labels: Priority:Normal

#837 Property Package Constraint Indexing & Utility Function Update
  watertap/core/util/scaling.py
  watertap/property_models/NDMA_prop_pack.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/ion_DSPMDE_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/water_prop_pack.py
Labels: Priority:Normal

#833 Add frictional pressure drop to electrodialysis
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:Normal
