Repository watertap-org/watertap, pull requests merged in 2023-05, with the labels that each got.

#1019 Use README for long description
  README.md
  setup.py
Labels: Priority:Normal, software admin

#1015 Consolidating parameters in GAC costing model
  docs/technical_reference/unit_models/gac.rst
  watertap/costing/units/gac.py
Labels: documentation, enhancement, Priority:Normal, costing

#935 ADM1 ASM2D translator block part 1
  docs/technical_reference/unit_models/translators/index.rst
  docs/technical_reference/unit_models/translators/translator_adm1_asm2d.rst
  watertap/property_models/activated_sludge/modified_asm2d_properties.py
  watertap/property_models/activated_sludge/modified_asm2d_reactions.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm2d.py
  watertap/unit_models/translators/translator_adm1_asm2d.py
Labels: Priority:Normal

#1020 ElectroNP ZO model with UnitModelBlockData base
  watertap/costing/units/electroNP.py
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/__init__.py
  watertap/unit_models/electroNP_ZO.py
  watertap/unit_models/tests/test_electroNP_ZO.py
Labels: Priority:Normal, iedo

#1022 UI parameter sweep
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_ASM_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_ui.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:Normal

#1017 Thickener & Dewatering Unit Model Documentation
  docs/technical_reference/unit_models/dewatering.rst
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/thickener.rst
Labels: documentation, Priority:High, iedo

#1028 Resolve macOS CI failures due to conda-forge IPopt version
  .github/workflows/checks.yml
Labels: Priority:High

#1013 Add Acid-Base Eq.Constraints to ADM1 Documentation
  docs/technical_reference/property_models/ADM1.rst
  docs/technical_reference/property_models/ASM1.rst
  docs/technical_reference/property_models/ASM2D.rst
  docs/technical_reference/property_models/modified_ADM1.rst
  watertap/property_models/activated_sludge/asm1_properties.py
  watertap/property_models/activated_sludge/asm2d_properties.py
  watertap/property_models/anaerobic_digestion/adm1_reactions.py
  watertap/property_models/anaerobic_digestion/modified_adm1_reactions.py
Labels: documentation, Priority:High, iedo

#1024 Refine selective oil permeation model
  watertap/property_models/selective_oil_permeation_prop_pack.py
  watertap/property_models/tests/test_selective_oil_permeation_prop_pack.py
  watertap/unit_models/selective_oil_permeation.py
  watertap/unit_models/tests/test_selective_oil_permeation.py
Labels: Priority:Normal

#1033 Add is_sweep option for UI export model variables
  watertap/ui/fsapi.py
Labels: Priority:High

#1037 Add .git-blame-ignore-revs file
  .git-blame-ignore-revs
  setup.py
Labels: Priority:High, software admin

#1016 Removing unnecessary warnings as a result of `diffus_phase_comp` in MCAS prop pack
  watertap/property_models/multicomp_aq_sol_prop_pack.py
Labels: bug, Priority:Normal

#986 Initial implementation of parallel manager for MPI and single process…
  watertap/tools/parallel/parallel_manager.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_differential.py
  watertap/tools/parameter_sweep/parameter_sweep_functions.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
Labels: Priority:Normal, parameter-sweep
