Repository watertap-org/watertap, pull requests merged in 2023-04, with the labels that each got.

#996 Modified ADM1 Documentation
  docs/technical_reference/property_models/ADM1.rst
  docs/technical_reference/property_models/index.rst
  docs/technical_reference/property_models/modified_ADM1.rst
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/property_models/anaerobic_digestion/modified_adm1_reactions.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_reaction.py
Labels: documentation, Priority:Normal, amo

#991 Updating ASM and ADM Pytest Marks
  watertap/property_models/activated_sludge/tests/test_asm1_reaction.py
  watertap/property_models/activated_sludge/tests/test_asm1_thermo.py
  watertap/property_models/activated_sludge/tests/test_asm2d_reaction.py
  watertap/property_models/activated_sludge/tests/test_asm2d_thermo.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_thermo.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_vapor_thermo.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_thermo.py
Labels: Priority:Normal

#997 Minor Refinements to ADM1
  docs/technical_reference/property_models/ADM1.rst
  docs/technical_reference/property_models/modified_ADM1.rst
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_vapor_thermo.py
  watertap/unit_models/anaerobic_digestor.py
Labels: Priority:Normal, amo

#1000 ASM1/ADM1 Translator Documentation
  docs/_static/unit_models/translators/mapping_step_a.jpg
  docs/_static/unit_models/translators/mapping_step_b.jpg
  docs/_static/unit_models/translators/mapping_step_c.jpg
  docs/_static/unit_models/translators/mapping_step_final.jpg
  docs/technical_reference/unit_models/translators/index.rst
  docs/technical_reference/unit_models/translators/translator_adm1_asm1.rst
  docs/technical_reference/unit_models/translators/translator_asm1_adm1.rst
  watertap/unit_models/translators/translator_asm1_adm1.py
Labels: documentation, Priority:Normal

#1007 Removing unwanted code from `test_gac.py`
  watertap/unit_models/tests/test_gac.py
Labels: Priority:Normal

#1012 ADM1 Documentation Update
  docs/technical_reference/property_models/ADM1.rst
  docs/technical_reference/property_models/modified_ADM1.rst
  docs/technical_reference/unit_models/translators/translator_adm1_asm1.rst
  docs/technical_reference/unit_models/translators/translator_asm1_adm1.rst
Labels: documentation, Priority:Normal

#1001 Add K and Mg components to ASM2D
  watertap/property_models/activated_sludge/modified_asm2d_properties.py
  watertap/property_models/activated_sludge/modified_asm2d_reactions.py
  watertap/property_models/activated_sludge/tests/test_modified_asm2d_reaction.py
  watertap/property_models/activated_sludge/tests/test_modified_asm2d_thermo.py
Labels: Priority:Normal

#1010 Dewatering and thickener unit models BSM2
  watertap/unit_models/__init__.py
  watertap/unit_models/dewatering.py
  watertap/unit_models/tests/test_dewatering_unit.py
  watertap/unit_models/tests/test_thickener_unit.py
  watertap/unit_models/thickener.py
Labels: Priority:Normal, iedo
