Repository watertap-org/watertap, pull requests merged in 2023-08, with the labels that each got.

#1093 Update monte carlo flowsheet and documentation to use new parameter sweep API
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  watertap/examples/flowsheets/RO_with_energy_recovery/monte_carlo_sampling_RO_ERD.py
  watertap/tools/parameter_sweep/parameter_sweep_functions.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
Labels: Priority:Normal

#1074 ASM2d/ADM1 Translator
  docs/technical_reference/property_models/modified_ADM1.rst
  docs/technical_reference/unit_models/translators/index.rst
  docs/technical_reference/unit_models/translators/translator_adm1_asm2d.rst
  docs/technical_reference/unit_models/translators/translator_asm2d_adm1.rst
  watertap/property_models/activated_sludge/modified_asm2d_reactions.py
  watertap/property_models/activated_sludge/tests/test_modified_asm2d_reaction.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:Normal, iedo

#1079 Add mapping keys between nominal and differential values for the DifferentialParameterSweep object
  docs/how_to_guides/how_to_run_differential_parameter_sweep.rst
  docs/how_to_guides/index.rst
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_differential.py
  watertap/tools/parameter_sweep/parameter_sweep_writer.py
  watertap/tools/parameter_sweep/tests/test_differential_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_recursive_parameter_sweep.py
Labels: Priority:Normal

#1089 Fix Pydantic 2 failures
  setup.py
Labels: Priority:High, dependencies

#1038 BSM2 full flowsheet
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM1_flowsheet.py
  watertap/examples/flowsheets/case_studies/activated_sludge/tests/test_asm2_noPHA_flowsheet.py
  watertap/examples/flowsheets/case_studies/anaerobic_digestor/ADM1_flowsheet.py
  watertap/examples/flowsheets/case_studies/anaerobic_digestor/tests/test_adm1_flowsheet.py
  watertap/examples/flowsheets/case_studies/electroNP/tests/test_electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/full_WRRF_with_ASM1_ADM1.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
  watertap/property_models/activated_sludge/asm1_properties.py
  watertap/property_models/activated_sludge/asm1_reactions.py
  watertap/property_models/activated_sludge/asm2d_properties.py
  watertap/property_models/activated_sludge/asm2d_reactions.py
  watertap/property_models/anaerobic_digestion/adm1_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/property_models/anaerobic_digestion/adm1_reactions.py
  watertap/property_models/anaerobic_digestion/modified_adm1_properties.py
  watertap/property_models/anaerobic_digestion/modified_adm1_reactions.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_thermo.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_vapor_thermo.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_thermo.py
  watertap/unit_models/anaerobic_digestor.py
  watertap/unit_models/dewatering.py
  watertap/unit_models/tests/test_anaerobic_digestor.py
  watertap/unit_models/thickener.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm1.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm2d.py
  watertap/unit_models/translators/tests/test_translator_asm1_adm1.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
  watertap/unit_models/translators/translator_adm1_asm1.py
  watertap/unit_models/translators/translator_adm1_asm2d.py
  watertap/unit_models/translators/translator_asm1_adm1.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:High

#1091 Changing ElectroN-P unit model to separator structure
  watertap/costing/units/electroNP.py
  watertap/examples/flowsheets/case_studies/electroNP/electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/full_WRRF_with_ASM1_ADM1.py
  watertap/unit_models/electroNP_ZO.py
  watertap/unit_models/tests/test_electroNP_ZO.py
Labels: Priority:Normal, iedo

#1088 Make pytest the only requirement for running test suite without errors
  .github/workflows/checks.yml
  docs/getting_started.rst
  setup.py
  watertap/edb/commands.py
  watertap/edb/data/__init__.py
  watertap/edb/tests/test_commands.py
  watertap/edb/tests/test_edb.py
  watertap/edb/tests/test_schemas.py
  watertap/edb/tests/util.py
  watertap/examples/chemistry/tests/conftest.py
  watertap/examples/chemistry/tests/test_notebooks.py
  watertap/examples/chemistry/tests/test_tutorials.py
  watertap/examples/edb/tests/conftest.py
  watertap/examples/flowsheets/lsrro/tests/paper_analysis_baselines/__init__.py
  watertap/examples/flowsheets/lsrro/tests/parameter_sweep_baselines/__init__.py
  watertap/tools/parallel/__init__.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/unit_models/tests/test_cstr_injection.py
  watertap/unit_models/tests/test_electroNP_ZO.py
  watertap/unit_models/translators/__init__.py
  watertap/unit_models/translators/translator_asm1_adm1.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:High, dependencies

#930 Update IDAES requirement to 2.2.0.dev0.watertap.23.08.03 and other stability improvements
  .github/workflows/checks.yml
  docs/how_to_guides/how_to_use_a_property_model.rst
  setup.py
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
  watertap/edb/data/base.json
  watertap/edb/data/component.json
  watertap/examples/chemistry/chem_scaling_utils.py
  watertap/examples/chemistry/tests/test_chlorination.py
  watertap/examples/chemistry/tests/test_enrtl_water_pH.py
  watertap/examples/chemistry/tests/test_pH_dependent_solubility.py
  watertap/examples/chemistry/tests/test_pure_water_pH.py
  watertap/examples/chemistry/tests/test_recarbonation_process.py
  watertap/examples/chemistry/tests/test_remineralization.py
  watertap/examples/chemistry/tests/test_seawater_alkalinity.py
  watertap/examples/chemistry/tests/test_solids.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/examples/flowsheets/nf_dspmde/nf.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass.py
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf_with_bypass.py
  watertap/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:High

#1110 Address Sphinx failures
  .github/workflows/checks.yml
  .readthedocs.yaml
  docs/examples/edb/simple_acid_example.ipynb
  setup.py
  watertap/edb/tests/test_commands.py
Labels: documentation, Priority:High, software admin, dependencies

#1101 Modified ASM2D Refinement and Associated Changes
  watertap/property_models/activated_sludge/modified_asm2d_properties.py
  watertap/property_models/activated_sludge/modified_asm2d_reactions.py
  watertap/property_models/activated_sludge/tests/test_modified_asm2d_reaction.py
  watertap/unit_models/translators/tests/test_translator_adm1_simple_asm2d.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
  watertap/unit_models/translators/translator_adm1_simple_asm2d.py
Labels: enhancement, Priority:High, iedo

#1076 Fix NF notebook and flowsheets for UI
  tutorials/nawi_spring_meeting2023.ipynb
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf_with_bypass.py
Labels: Priority:Normal

#1103 Add coverage reports from MPI tests
  .github/workflows/mpi4py-test.yml
  codecov.yml
Labels: Priority:Normal

#1114 Add support for Python 3.11
  .github/workflows/checks.yml
  setup.py
Labels: Priority:Normal, software admin

#1056 Adding OLI API
  watertap/core/util/oli_api.py
  watertap/core/util/tests/test_oli_api.py
Labels: Priority:Normal, oli
