Repository watertap-org/watertap, pull requests merged in 2023-11, with the labels that each got.

#1188 BSM2 GUI Update
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
Labels: Priority:Normal, ui

#1132 Skk model
  watertap/core/membrane_channel_base.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal

#1182 Parameter Estimation (parmest) Demo
  tutorials/parmest_demo/P_sat_Data.csv
  tutorials/parmest_demo/parmest_example.ipynb
Labels: Priority:High

#1194 Small BSM2 GUI Update
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
Labels: Priority:Normal, ui

#1193 BSM2 tutorial - quick cleanup
  docs/technical_reference/unit_models/reverse_osmosis_1D.rst
  tutorials/BSM2.ipynb
  tutorials/BSM2.png
Labels: documentation, Priority:High

#1205 Correcting documentation typo for loopTool code block
  docs/how_to_guides/how_to_use_loopTool_to_explore_flowsheets.rst
Labels: documentation, Priority:Low

#1181 Merge in Parameter Sweep Tool Demo
  tutorials/assets_parameter_sweep_demo/Differential_Parameter_Sweep_Flowchart.png
  tutorials/assets_parameter_sweep_demo/LSRRO_Eagle_strong_10K.png
  tutorials/assets_parameter_sweep_demo/Parameter_Sweep_Flowchart.png
  tutorials/assets_parameter_sweep_demo/RO-ERD_Eagle_Strong_Scaling_100K.png
  tutorials/assets_parameter_sweep_demo/RO-ERD_Mac_2500_speedup.png
  tutorials/assets_parameter_sweep_demo/RO-ERD_Mac_2500_time.png
  tutorials/assets_parameter_sweep_demo/RO_ERD_flowsheet.png
  tutorials/assets_parameter_sweep_demo/Recursive_Parameter_Sweep_flowchart.png
  tutorials/assets_parameter_sweep_demo/maps_LCOW_recovery_NaCl_loading.jpg
  tutorials/assets_parameter_sweep_demo/parameter_sweep_demo_script.py
  tutorials/assets_parameter_sweep_demo/scatter_LCOW_vs_Acomp.jpg
  tutorials/assets_parameter_sweep_demo/watertap-logo.png
  tutorials/parameter_sweep_demo.ipynb
  watertap/tools/parallel/concurrent_futures_parallel_manager.py
  watertap/tools/parallel/multiprocessing_parallel_manager.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_differential.py
  watertap/tools/parameter_sweep/parameter_sweep_functions.py
  watertap/tools/parameter_sweep/tests/test_differential_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_recursive_parameter_sweep.py
Labels: Priority:High

#1202 Extract Data from Molecular Formulas
  watertap/tools/oli_api/util/periodic_table.csv
  watertap/tools/oli_api/util/tests/test_periodic_table.py
  watertap/tools/oli_api/util/tests/test_watertap_to_oli_helper_functions.py
  watertap/tools/oli_api/util/watertap_to_oli_helper_functions.py
Labels: Priority:Normal, chem team, oli, utility

#1149 Minor update to MCAS scaling
  watertap/property_models/multicomp_aq_sol_prop_pack.py
Labels: Priority:Normal

#1141 OLIApi Revision
  requirements-dev.txt
  setup.py
  watertap/core/util/oli_api.py
  watertap/core/util/tests/test_oli_api.py
  watertap/tools/oli_api/__init__.py
  watertap/tools/oli_api/client.py
  watertap/tools/oli_api/core/__init__.py
  watertap/tools/oli_api/core/water_analysis.py
  watertap/tools/oli_api/credentials.py
  watertap/tools/oli_api/incorporating_oli_calculations.ipynb
  watertap/tools/oli_api/tests/__init__.py
  watertap/tools/oli_api/tests/test.dbs
  watertap/tools/oli_api/tests/test_client.py
  watertap/tools/oli_api/tests/test_credentials.py
  watertap/tools/oli_api/util/__init__.py
  watertap/tools/oli_api/util/fixed_keys_dict.py
  watertap/tools/oli_api/util/state_block_helper_functions.py
  watertap/tools/oli_api/util/tests/__init__.py
  watertap/tools/oli_api/util/tests/test_fixed_keys_dict.py
  watertap/tools/oli_api/util/tests/test_state_block_helper_functions.py
  watertap/tools/oli_api/util/tests/test_watertap_to_oli_helper_functions.py
Labels: Priority:High, oli, dependencies

#1212 Add Costing for Dewatering Unit
  tutorials/BSM2.ipynb
  watertap/costing/unit_models/dewatering.py
  watertap/data/techno_economic/centrifuge.yaml
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
  watertap/unit_models/dewatering.py
  watertap/unit_models/tests/test_dewatering_unit.py
Labels: Priority:Normal, iedo, costing

#1152 Add build options to UI api; add example to nf_ui.py
  docs/how_to_guides/how_to_use_ui_api.rst
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery_ui.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/__init__.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_ASM_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_ui.py
  watertap/examples/flowsheets/nf_dspmde/nf_ui.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass_ui.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_flowsheet_interfaces.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:High

#1183 multiple choice costing
  docs/technical_reference/costing/index.rst
  docs/technical_reference/costing/multiple_choice_costing_block.rst
  watertap/costing/__init__.py
  watertap/costing/multiple_choice_costing_block.py
  watertap/costing/tests/test_multiple_choice_costing_block.py
Labels: Priority:Normal

#1198 Add clarifier model and costing
  watertap/costing/unit_models/clarifier.py
  watertap/unit_models/__init__.py
  watertap/unit_models/clarifier.py
  watertap/unit_models/tests/test_clarifier.py
Labels: Priority:Normal, iedo, costing

#1218 ED flowsheet updates
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack_conc_recirc.py
Labels: Priority:High
