Repository watertap-org/watertap, pull requests merged in 2023-01, with the labels that each got.

#880 Add OARO costing method
  watertap/costing/units/osmotically_assisted_reverse_osmosis.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/oaro/oaro.py
  watertap/unit_models/__init__.py
Labels: Priority:High, nawi

#864 moving ElectroCoagulation ZO model to new branch
  .vscode/settings.json
Labels: Priority:Normal, WIP

#853 Adds Pressure Effects Into Specific Enthalpy
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_flowsheets.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/tests/property_test_harness.py
  watertap/property_models/tests/test_NaCl_prop_pack.py
  watertap/property_models/tests/test_seawater_prop_pack.py
  watertap/unit_models/mvc/components/tests/test_chen_heat_exchanger.py
  watertap/unit_models/mvc/components/tests/test_evaporator.py
  watertap/unit_models/mvc/tests/test_mvc.py
  watertap/unit_models/tests/test_nanofiltration_0D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_pressure_changer.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal

#881 Add items to `.gitignore` for VSCode and Sublime Text editors
  .gitignore
Labels: Priority:Normal

#877 ZO Documentation Test
  setup.py
  watertap/unit_models/zero_order/tests/test_zo_documentation.py
Labels: documentation, Priority:Normal

#883 IX 0D Documentation
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/ion_exchange_0D.rst
Labels: documentation, Priority:Normal

#882 Improving GAC ZO costing
  watertap/core/zero_order_costing.py
  watertap/data/techno_economic/gac.yaml
  watertap/examples/flowsheets/case_studies/municipal_treatment/tests/test_municipal_treatment.py
  watertap/unit_models/zero_order/gac_zo.py
  watertap/unit_models/zero_order/tests/test_gac_zo.py
Labels: enhancement, Priority:Normal, costing

#903 Adding density parameter to MCAS when `DensityCalculation.constant`
  watertap/property_models/multicomp_aq_sol_prop_pack.py
Labels: enhancement, Priority:Normal

#875 Flowsheet demonstration of IonExchange0D
  watertap/examples/flowsheets/ion_exchange/__init__.py
  watertap/examples/flowsheets/ion_exchange/ion_exchange_demo.py
  watertap/examples/flowsheets/ion_exchange/tests/test_ion_exchange_demo.py
  watertap/unit_models/ion_exchange_0D.py
Labels: Priority:Normal, analysis team, nawi
