Repository watertap-org/watertap, pull requests merged in 2023-12, with the labels that each got.

#1216 Add Thickener Costing
  tutorials/BSM2.ipynb
  watertap/costing/unit_models/thickener.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2.py
  watertap/unit_models/tests/test_dewatering_unit.py
  watertap/unit_models/tests/test_thickener_unit.py
  watertap/unit_models/thickener.py
Labels: Priority:High, iedo, costing

#1220 Add documentation for the Parallel Manager
  docs/technical_reference/tools/index.rst
  docs/technical_reference/tools/parallel_manager.rst
Labels: documentation, Priority:Normal

#1224 Fixes for Pyomo 6.7
  setup.py
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
  watertap/examples/custom_model_demo/simple_prop_pack.py
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM2D_flowsheet_noPHA.py
  watertap/examples/flowsheets/case_studies/activated_sludge/tests/test_asm2_noPHA_flowsheet.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/examples/flowsheets/full_treatment_train/model_components/seawater_salt_prop_pack.py
  watertap/property_models/NDMA_prop_pack.py
  watertap/property_models/NaCl_T_dep_prop_pack.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/activated_sludge/asm1_properties.py
  watertap/property_models/activated_sludge/asm2d_properties.py
  watertap/property_models/activated_sludge/modified_asm2d_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/property_models/anaerobic_digestion/modified_adm1_properties.py
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/cryst_prop_pack.py
  watertap/property_models/seawater_ion_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/water_prop_pack.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_1D.py
Labels: Priority:High

#1186 BSM2 Anoxic CSTR Costing
  watertap/costing/costing_base.py
  watertap/costing/unit_models/cstr.py
  watertap/unit_models/__init__.py
  watertap/unit_models/cstr.py
  watertap/unit_models/tests/test_cstr.py
Labels: Priority:Normal

#1196 anaerobic digestor and aerobic basin costing update
  watertap/costing/unit_models/cstr_injection.py
  watertap/examples/flowsheets/case_studies/electroNP/tests/test_electroNP_flowsheet.py
  watertap/unit_models/__init__.py
  watertap/unit_models/anaerobic_digestor.py
  watertap/unit_models/cstr_injection.py
  watertap/unit_models/tests/test_anaerobic_digestor.py
  watertap/unit_models/tests/test_cstr_injection.py
Labels: Priority:Normal, iedo, costing

#1213 Add Costing to BSM2 Flowsheet
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
  watertap/property_models/activated_sludge/asm1_reactions.py
Labels: Priority:High

#1208 Add pressure drop to electrodialysis_0D.py
  docs/technical_reference/unit_models/electrodialysis_0D.rst
  docs/technical_reference/unit_models/electrodialysis_1D.rst
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:Normal

#1241 Update idaes-pse requirement in preparation of 2.3.0 release
  setup.py
Labels: Priority:High

#1214 OARO SKK config option and tests
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_1D.py
Labels: Priority:Normal

#1243 Add influent/effluent quality metrics for ASM1
  watertap/property_models/activated_sludge/asm1_properties.py
  watertap/property_models/activated_sludge/asm1_reactions.py
  watertap/property_models/activated_sludge/tests/test_asm1_thermo.py
  watertap/unit_models/tests/test_dewatering_unit.py
  watertap/unit_models/tests/test_thickener_unit.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm1.py
  watertap/unit_models/translators/tests/test_translator_asm1_adm1.py
Labels: iedo, property_model

#1174 Costing Unification: parameter consistency across costing packages
  docs/technical_reference/costing/watertap_costing.rst
  watertap/costing/tests/test_zero_order_costing.py
  watertap/costing/watertap_costing_package.py
  watertap/costing/zero_order_costing.py
  watertap/examples/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/examples/flowsheets/ion_exchange/tests/test_ion_exchange_demo.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/examples/flowsheets/mvc/mvc_single_stage.py
  watertap/examples/flowsheets/mvc/tests/test_mvc_single_stage.py
  watertap/examples/flowsheets/nf_dspmde/nf_ui.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass_ui.py
  watertap/examples/flowsheets/oaro/oaro_multi.py
  watertap/unit_models/tests/test_cstr.py
  watertap/unit_models/zero_order/tests/test_anaerobic_digestion_reactive_zo.py
  watertap/unit_models/zero_order/tests/test_cloth_media_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_membrane_evaporator.py
  watertap/unit_models/zero_order/tests/test_metab_zo.py
  watertap/unit_models/zero_order/tests/test_microbial_battery_zo.py
Labels: Priority:Normal, costing

#1246 Automatically load MW and charge in MCAS
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/tools/oli_api/util/tests/test_watertap_to_oli_helper_functions.py
  watertap/tools/oli_api/util/watertap_to_oli_helper_functions.py
Labels: Priority:Normal, property_model

#1232 CSV-driven variable exports
  docs/how_to_guides/how_to_use_ui_api.rst
  pytest.ini
  setup.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:Normal

#1139 IonExchange0D Unit Model and Costing Improvements
  docs/technical_reference/unit_models/ion_exchange_0D.rst
  watertap/costing/unit_models/ion_exchange.py
  watertap/examples/flowsheets/ion_exchange/ion_exchange_demo.py
  watertap/examples/flowsheets/ion_exchange/tests/test_ion_exchange_demo.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:High, model dev team

#1185 MVC GUI
  .github/workflows/checks.yml
  setup.py
  watertap/examples/flowsheets/mvc/mvc_single_stage.py
  watertap/examples/flowsheets/mvc/mvc_single_stage_ui.py
Labels: Priority:Normal, ui

#1203 Modified ASM2d flowsheet with P extension
  watertap/examples/flowsheets/case_studies/activated_sludge/modified_ASM2D_flowsheet.py
  watertap/examples/flowsheets/case_studies/activated_sludge/tests/test_modified_asm2d_flowsheet.py
Labels: Priority:High

#1247 added fixed samples to paramter sweep reader and looptool
  watertap/tools/analysis_tools/loop_tool/loop_tool.py
  watertap/tools/analysis_tools/loop_tool/tests/test_all_options.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_expected_option_directory.yaml
  watertap/tools/parameter_sweep/parameter_sweep_reader.py
  watertap/tools/parameter_sweep/sampling_types.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_reader.py
Labels: Priority:Normal

#1240 Fixes and updates for differential parmater sweep tool
  docs/how_to_guides/how_to_run_differential_parameter_sweep.rst
  docs/how_to_guides/how_to_use_loopTool_to_explore_flowsheets.rst
  tutorials/assets_parameter_sweep_demo/parameter_sweep_demo_script.py
  tutorials/parameter_sweep_demo.ipynb
  watertap/tools/analysis_tools/loop_tool/loop_tool.py
  watertap/tools/parameter_sweep/model_manager.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_differential.py
  watertap/tools/parameter_sweep/parameter_sweep_functions.py
  watertap/tools/parameter_sweep/parameter_sweep_writer.py
  watertap/tools/parameter_sweep/paramter_sweep_parallel_utils.py
  watertap/tools/parameter_sweep/tests/test_differential_parameter_sweep.py
Labels: Priority:Normal

#1254 Add missing __init__.py files preventing MVC GUI from loading
  watertap/examples/flowsheets/mvc/__init__.py
  watertap/examples/flowsheets/mvc/mvc_single_stage.py
  watertap/examples/flowsheets/mvc/mvc_single_stage_ui.py
  watertap/examples/flowsheets/mvc/tests/__init__.py
  watertap/examples/flowsheets/mvc/tests/test_mvc_single_stage.py
Labels: ui, bugfix
