Repository watertap-org/watertap, pull requests merged in 2023-03, with the labels that each got.

#921 Add documentation for running zero-order models
  docs/how_to_guides/how_to_run_zero_order_model.rst
  docs/how_to_guides/index.rst
  docs/technical_reference/unit_models/zero_order_unit_models/index.rst
Labels: Priority:Normal

#937 Update IDAES to 2.0.0rc0
  setup.py
  watertap/core/util/scaling.py
  watertap/core/zero_order_properties.py
  watertap/examples/custom_model_demo/simple_prop_pack.py
  watertap/examples/flowsheets/full_treatment_train/model_components/seawater_ion_prop_pack.py
  watertap/examples/flowsheets/full_treatment_train/model_components/seawater_salt_prop_pack.py
  watertap/property_models/NDMA_prop_pack.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/activated_sludge/asm1_properties.py
  watertap/property_models/activated_sludge/asm2d_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/property_models/anaerobic_digestion/adm1_reactions.py
  watertap/property_models/coagulation_prop_pack.py
  watertap/property_models/cryst_prop_pack.py
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/tests/property_test_harness.py
  watertap/property_models/tests/test_coag_prop_pack.py
  watertap/property_models/tests/test_cryst_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/property_models/water_prop_pack.py
Labels: Priority:High

#906 MCAS Property Package Documentation
  docs/_static/unit_models/mcas_set_hierarchy.png
  docs/technical_reference/property_models/mc_aq_sol.rst
  docs/technical_reference/unit_models/gac.rst
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/unit_models/gac.py
Labels: documentation, Priority:Normal

#949 Update IDAES to 2.0.0
  setup.py
Labels: Priority:High

#933 Translator block ADM1-ASM1
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/translators/index.rst
  docs/technical_reference/unit_models/translators/translator_adm1_asm1.rst
  watertap/unit_models/translators/tests/test_translator_adm1_asm1.py
  watertap/unit_models/translators/translator_adm1_asm1.py
Labels: Priority:Normal, amo

#946 Reorganize model diagnostics
  watertap/core/util/initialization.py
  watertap/core/util/model_diagnostics/__init__.py
  watertap/core/util/model_diagnostics/infeasible.py
  watertap/core/util/model_diagnostics/ipopt_initialization.py
  watertap/core/util/model_diagnostics/tests/__init__.py
  watertap/core/util/model_diagnostics/tests/test_infeasible.py
  watertap/core/util/model_diagnostics/tests/test_ipopt_initialization.py
  watertap/core/util/tests/test_initialization.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:Normal

#962 Translator block ASM1-ADM1
  watertap/unit_models/translators/tests/test_translator_asm1_adm1.py
  watertap/unit_models/translators/translator_adm1_asm1.py
  watertap/unit_models/translators/translator_asm1_adm1.py
Labels: Priority:High

#953 Add electrocoagulation zero-order model
  docs/technical_reference/unit_models/zero_order_unit_models/electrocoagulation_zo.rst
  docs/technical_reference/unit_models/zero_order_unit_models/index.rst
  watertap/data/techno_economic/electrocoagulation.yaml
  watertap/data/techno_economic/tests/test_unit_parameter_files.py
  watertap/unit_models/zero_order/__init__.py
  watertap/unit_models/zero_order/electrocoagulation_zo.py
  watertap/unit_models/zero_order/tests/test_electrocoagulation_zo.py
Labels: Priority:Normal

#972 Replace ValueError w/ Initialization Error
  watertap/core/util/initialization.py
  watertap/core/util/tests/test_initialization.py
Labels: enhancement, Priority:Normal, utility

#925 Allow custom parameter sweep functions and store additional data
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_differential.py
  watertap/tools/parameter_sweep/tests/test_differential_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_writer.py
Labels: Priority:Normal

#960 Adding costing options for pressure or gravity GAC contactors
  docs/technical_reference/unit_models/gac.rst
  watertap/costing/units/gac.py
  watertap/data/techno_economic/gac.yaml
  watertap/examples/flowsheets/case_studies/municipal_treatment/tests/test_municipal_treatment.py
  watertap/unit_models/tests/test_gac.py
Labels: enhancement, Priority:Normal, costing

#943 Refine Scaling Utility
  watertap/core/util/scaling.py
  watertap/core/util/tests/test_scaling.py
Labels: Priority:Normal, utility

#889 Selective oil permeation model development
  watertap/property_models/selective_oil_permeation_prop_pack.py
  watertap/property_models/tests/test_selective_oil_permeation_prop_pack.py
  watertap/unit_models/selective_oil_permeation.py
  watertap/unit_models/tests/test_selective_oil_permeation.py
Labels: Priority:Normal

#983 Touch up LSRRO example
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/examples/flowsheets/lsrro/multi_sweep.py
  watertap/examples/flowsheets/lsrro/tests/test_lssro_paper_analysis.py
Labels: Priority:Normal, :cherries: Merge to rel

#948 Add modified ADM1 model with P extension
  watertap/property_models/anaerobic_digestion/modified_adm1_properties.py
  watertap/property_models/anaerobic_digestion/modified_adm1_reactions.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_thermo.py
  watertap/unit_models/anaerobic_digestor.py
  watertap/unit_models/tests/test_anaerobic_digestor.py
Labels: Priority:Normal, :cherries: Merge to rel

#989 Fix #987
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/tests/test_multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/tests/test_multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/tests/test_amo_1690_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/multi_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
Labels: Priority:High, :cherries: Merge to rel
