Repository watertap-org/watertap, pull requests merged in 2023-07, with the labels that each got.

#1075 Add additional comments for valid temp ranges for NaCl_T_dep_prop_pack
  watertap/property_models/NaCl_T_dep_prop_pack.py
Labels: Priority:Normal

#1082 Correct units in GAC costing `energy_consumption_constraint`
  watertap/costing/units/gac.py
  watertap/unit_models/tests/test_gac.py
Labels: bug, Priority:High, costing

#998 IonExchange0D Model Overhaul
  docs/technical_reference/unit_models/ion_exchange_0D.rst
  watertap/costing/units/ion_exchange.py
  watertap/examples/flowsheets/ion_exchange/ion_exchange_demo.py
  watertap/examples/flowsheets/ion_exchange/tests/test_ion_exchange_demo.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:Normal, model dev team

#1078 ASM2d compatibility with thickener and dewatering units
  watertap/property_models/activated_sludge/asm1_properties.py
  watertap/property_models/activated_sludge/asm2d_properties.py
  watertap/property_models/activated_sludge/modified_asm2d_properties.py
  watertap/property_models/activated_sludge/modified_asm2d_reactions.py
  watertap/property_models/activated_sludge/tests/test_asm1_thermo.py
  watertap/property_models/activated_sludge/tests/test_asm2d_reaction.py
  watertap/property_models/activated_sludge/tests/test_asm2d_thermo.py
  watertap/property_models/activated_sludge/tests/test_modified_asm2d_reaction.py
  watertap/property_models/activated_sludge/tests/test_modified_asm2d_thermo.py
  watertap/property_models/anaerobic_digestion/modified_adm1_properties.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_thermo.py
  watertap/unit_models/dewatering.py
  watertap/unit_models/tests/test_dewatering_unit.py
  watertap/unit_models/tests/test_thickener_unit.py
  watertap/unit_models/thickener.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm2d.py
  watertap/unit_models/translators/tests/test_translator_adm1_simple_asm2d.py
Labels: enhancement, Priority:Normal, iedo

#1077 Add sweep analysis for electroNP flowsheet
  watertap/costing/units/electroNP.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/case_studies/electroNP/electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/electroNP/multi_sweep.py
  watertap/examples/flowsheets/case_studies/electroNP/tests/test_electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/electroNP/tests/test_multi_sweep.py
  watertap/unit_models/electroNP_ZO.py
  watertap/unit_models/tests/test_electroNP_ZO.py
Labels: Priority:Normal

#1059 Initial implementation of ConcurrentFuturesParallelManager
  .gitignore
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  watertap/tools/parallel/concurrent_futures_parallel_manager.py
  watertap/tools/parallel/mpi_parallel_manager.py
  watertap/tools/parallel/parallel_manager.py
  watertap/tools/parallel/parallel_manager_factory.py
  watertap/tools/parallel/results.py
  watertap/tools/parallel/single_process_parallel_manager.py
  watertap/tools/parallel/tests/test_parallel_manager.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_differential.py
  watertap/tools/parameter_sweep/parameter_sweep_functions.py
  watertap/tools/parameter_sweep/parameter_sweep_writer.py
  watertap/tools/parameter_sweep/tests/test_differential_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_recursive_parameter_sweep.py
Labels: Priority:Normal, parameter-sweep

#1086 Update electrodialysis costing
  watertap/costing/tests/test_util.py
  watertap/costing/units/electrodialysis.py
  watertap/costing/util.py
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack_conc_recirc.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:High
