Repository watertap-org/watertap, pull requests merged in 2023-06, with the labels that each got.

#1041 Add flow_vol property to SOP property package
  watertap/property_models/selective_oil_permeation_prop_pack.py
  watertap/property_models/tests/test_selective_oil_permeation_prop_pack.py
Labels: Priority:Normal

#1047 Remove explicit uses of MPI from ParameterSweep and ParameterSweepWri…
  watertap/tools/parallel/parallel_manager.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_writer.py
  watertap/tools/parameter_sweep/tests/test_differential_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_writer.py
  watertap/tools/parameter_sweep/tests/test_recursive_parameter_sweep.py
Labels: Priority:Normal

#1052 Update SOP Params to Vars
  watertap/unit_models/selective_oil_permeation.py
  watertap/unit_models/tests/test_selective_oil_permeation.py
Labels: Priority:Normal

#1009 MVC example flowsheet
  watertap/costing/units/compressor.py
  watertap/costing/units/evaporator.py
  watertap/costing/units/heat_exchanger.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/mvc/mvc_single_stage.py
  watertap/examples/flowsheets/mvc/tests/test_mvc_single_stage.py
Labels: Priority:High

#1032 Initial ElectroNP flowsheet
  watertap/examples/flowsheets/case_studies/electroNP/__init__.py
  watertap/examples/flowsheets/case_studies/electroNP/electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/electroNP/tests/__init__.py
  watertap/examples/flowsheets/case_studies/electroNP/tests/test_electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/tests/test_electrochemical_nutrient_removal.py
  watertap/unit_models/electroNP_ZO.py
  watertap/unit_models/tests/test_electroNP_ZO.py
  watertap/unit_models/zero_order/electrochemical_nutrient_removal_zo.py
  watertap/unit_models/zero_order/tests/test_electrochemical_nutrient_removal_zo.py
Labels: Priority:Normal

#1060 Update version of GHA actions using deprecated Node versions
  .github/workflows/checks.yml
  .github/workflows/mpi4py-test.yml
Labels: Priority:Normal

#1027 Add code demo from NAWI spring meeting
  setup.py
  tutorials/introduction.ipynb
  tutorials/nawi_spring_meeting2023.ipynb
  tutorials/nf_dspmde_transport_mechanisms.png
  tutorials/nf_ui.png
  watertap/core/util/scaling.py
  watertap/core/util/tests/test_scaling.py
  watertap/costing/units/pump.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/nf_dspmde/__init__.py
  watertap/examples/flowsheets/nf_dspmde/tests/__init__.py
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
Labels: Priority:High, analysis team

#1046 Add number of samples to model export for param sweep
  watertap/ui/fsapi.py
Labels: Priority:Normal

#1063 ADM1/ASM2d Translator Doc Update
  docs/technical_reference/unit_models/translators/translator_adm1_asm2d.rst
Labels: documentation, Priority:Normal, iedo

#1057 Adding costing method for rectifier capital cost and upscaled electricity flow
  watertap/costing/__init__.py
  watertap/costing/tests/test_util.py
  watertap/costing/util.py
Labels: enhancement, Priority:Normal, costing

#1006 Adding basic Electrolyzer unit model
  docs/technical_reference/unit_models/electrolyzer.rst
  docs/technical_reference/unit_models/index.rst
  watertap/costing/units/electrolyzer.py
  watertap/costing/watertap_costing_package.py
  watertap/unit_models/__init__.py
  watertap/unit_models/electrolyzer.py
  watertap/unit_models/tests/test_electrolyzer.py
Labels: Priority:Normal, nawi

#1054 NaCl Property Pack with Temperature Dependence
  docs/technical_reference/property_models/NaCl_T_dep.rst
  docs/technical_reference/property_models/index.rst
  watertap/property_models/NaCl_T_dep_prop_pack.py
  watertap/property_models/tests/test_NaCl_T_dep_prop_pack.py
Labels: Priority:High

#1062 Merging demo from NAWI Spring Meeting Pt2 - NF+Bypass example
  .github/workflows/checks.yml
  tutorials/nawi_spring_meeting2023.ipynb
  watertap/costing/units/pump.py
  watertap/examples/flowsheets/nf_dspmde/nf.py
  watertap/examples/flowsheets/nf_dspmde/nf_ui.png
  watertap/examples/flowsheets/nf_dspmde/nf_ui.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass_ui.png
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass_ui.py
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf.py
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf_with_bypass.py
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
Labels: Priority:High

#1068 Fix sweep_param key names to use the short names
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_recursive_parameter_sweep.py
Labels: bug, Priority:Normal, parameter-sweep

#1034 Update idaes-pse requirement in preparation to 2.1 release
  .github/workflows/checks.yml
  setup.py
  watertap/core/tests/test_zero_order_properties.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/chemistry/tests/test_pH_dependent_solubility.py
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM2D_flowsheet.py
  watertap/examples/flowsheets/case_studies/activated_sludge/tests/test_asm2d_flowsheet.py
  watertap/examples/flowsheets/case_studies/electroNP/electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf_with_bypass.py
  watertap/property_models/NDMA_prop_pack.py
  watertap/property_models/NaCl_T_dep_prop_pack.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/property_models/activated_sludge/tests/test_asm1_integration.py
  watertap/property_models/activated_sludge/tests/test_asm1_reaction.py
  watertap/property_models/cryst_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/water_prop_pack.py
  watertap/unit_models/tests/test_crystallizer.py
Labels: Priority:High, IDAES
