Repository watertap-org/watertap, pull requests merged in 2023-09, with the labels that each got.

#1118 Update idaes-pse requirement to 2.2.0rc0
  setup.py
Labels: Priority:High, dependencies

#1116 ADM1 Documentation Update
  docs/technical_reference/property_models/ADM1.rst
  docs/technical_reference/property_models/modified_ADM1.rst
Labels: documentation, Priority:Normal

#1120 Add NaCl recovery value to crystallizer model
  watertap/costing/units/crystallizer.py
  watertap/costing/watertap_costing_package.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_flowsheets.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf.py
  watertap/unit_models/tests/test_crystallizer.py
Labels: Priority:Normal

#1098 Adding loopTool to analysis tools
  .github/workflows/mpi4py-test.yml
  docs/how_to_guides/how_to_use_loopTool_to_explore_flowsheets.rst
  docs/how_to_guides/index.rst
  docs/technical_reference/tools/index.rst
  watertap/tools/analysis_tools/loop_tool/data_merging_tool.py
  watertap/tools/analysis_tools/loop_tool/loop_tool.py
  watertap/tools/analysis_tools/loop_tool/tests/ro_setup.py
  watertap/tools/analysis_tools/loop_tool/tests/test_all_options.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_bad_default.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_data_merging_tool.py
  watertap/tools/analysis_tools/loop_tool/tests/test_diff.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_expected_diff_directory.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_expected_option_directory.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_expected_sweep_directory.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_loop_tool.py
  watertap/tools/analysis_tools/loop_tool/tests/test_missing_sweep_loop.yaml
  watertap/tools/analysis_tools/loop_tool/tests/test_sweep.yaml
  watertap/tools/parallel/parallel_manager_factory.py
  watertap/tools/parameter_sweep/model_manager.py
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_reader.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_reader.py
Labels: Priority:High

#1129 Add idaes-extensions step to getting started for devs
  docs/getting_started.rst
Labels: documentation

#1136 MCAS Update
  tutorials/nawi_spring_meeting2023.ipynb
  watertap/core/util/scaling.py
  watertap/examples/flowsheets/nf_dspmde/nf.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass.py
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf.py
  watertap/examples/flowsheets/nf_dspmde/tests/test_nf_with_bypass.py
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
Labels: Priority:Normal

#1156 Update CI in preparation of 0.10 release
  .github/workflows/checks.yml
  setup.py
Labels: Priority:High, IDAES, dependencies

#1125 BSM2 GUI
  setup.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.png
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
Labels: Priority:High, iedo, ui

#1105 Add MD 0D
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/membrane_distillation_0D.rst
  watertap/unit_models/MD/MD_channel_0D.py
  watertap/unit_models/MD/MD_channel_base.py
  watertap/unit_models/MD/__init__.py
  watertap/unit_models/MD/membrane_distillation_0D.py
  watertap/unit_models/MD/membrane_distillation_base.py
  watertap/unit_models/tests/test_membrane_distillation_0D.py
Labels: Priority:High

#897 Add multi-stage OARO flowsheet and cost optimization
  watertap/examples/flowsheets/oaro/oaro_multi.py
  watertap/examples/flowsheets/oaro/tests/test_oaro_multi.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_base.py
Labels: Priority:Normal, nawi

#1142 Add documentation for electroNP_ZO model
  docs/technical_reference/unit_models/electroNP_ZO.rst
  docs/technical_reference/unit_models/index.rst
Labels: Priority:Normal

#1126 Dye Desalination Parameter Update
  watertap/data/techno_economic/nanofiltration.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_sweep.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
Labels: Priority:Normal, analysis, iedo

#1155 Add documentation for using Jupyter notebooks
  docs/getting_started.rst
  docs/how_to_guides/index.rst
  docs/how_to_guides/notebooks.rst
  requirements-dev.txt
  setup.py
Labels: documentation, Priority:High, dependencies, jupyter
