Repository watertap-org/watertap, pull requests merged in 2023-10, with the labels that each got.

#1162 Eliminate bounds relaxation in WaterTAP Ipopt
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
  watertap/examples/chemistry/tests/test_pH_dependent_solubility.py
  watertap/examples/chemistry/tests/test_pure_water_pH.py
  watertap/examples/chemistry/tests/test_remineralization.py
  watertap/examples/chemistry/tests/test_solids.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/property_models/tests/test_cryst_prop_pack.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/mvc/components/compressor.py
  watertap/unit_models/mvc/tests/test_mvc.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
  watertap/unit_models/zero_order/tests/test_blending_reservoir_zo.py
  watertap/unit_models/zero_order/tests/test_municipal_wwtp_zo.py
  watertap/unit_models/zero_order/tests/test_smp_zo.py
  watertap/unit_models/zero_order/tests/test_struvite_classifier_zo.py
Labels: Priority:High, bugfix

#1167 Add Binder configuration and documentation
  .binder/apt.txt
  .binder/postBuild
  .binder/requirements.txt
  README.md
  docs/how_to_guides/notebooks.rst
Labels: documentation, jupyter

#1160 BSM2 GUI Update
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
Labels: Priority:Normal, iedo, ui

#1171 BSM2 GUI Variable Name Update
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
Labels: Priority:Normal, ui

#1164 Updates to EC ZO model
  docs/technical_reference/unit_models/zero_order_unit_models/electrocoagulation_zo.rst
  watertap/data/techno_economic/electrocoagulation.yaml
  watertap/unit_models/zero_order/electrocoagulation_zo.py
  watertap/unit_models/zero_order/tests/test_electrocoagulation_zo.py
Labels: Priority:Normal

#1163 Stakeholder demo for adding custom constraints to existing unit model
  tutorials/RO_flowsheet.png
  tutorials/unit_model_customization_example.ipynb
Labels: Priority:Normal

#1159 Add GUI for RO flowsheet
  setup.py
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery_ui.png
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery_ui.py
Labels: Priority:Normal

#1176 MCAS Usage Example and Raising Appropriate Exceptions
  docs/how_to_guides/how_to_use_MCAS_property_model.rst
  docs/how_to_guides/how_to_use_a_property_model.rst
  docs/how_to_guides/index.rst
  docs/technical_reference/property_models/mc_aq_sol.rst
  tutorials/nawi_spring_meeting2023.ipynb
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/unit_models/tests/test_boron_removal.py
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
  watertap/unit_models/tests/test_pressure_changer.py
Labels: documentation, Priority:Normal, property_model
