Repository watertap-org/watertap, pull requests merged in 2023-02, with the labels that each got.

#857 ADM1
  watertap/examples/flowsheets/case_studies/anaerobic_digestor/ADM1_flowsheet.py
  watertap/examples/flowsheets/case_studies/anaerobic_digestor/tests/test_adm1_flowsheet.py
  watertap/property_models/anaerobic_digestion/__init__.py
  watertap/property_models/anaerobic_digestion/adm1_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/property_models/anaerobic_digestion/adm1_reactions.py
  watertap/property_models/anaerobic_digestion/tests/__init__.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_thermo.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_vapor_thermo.py
  watertap/unit_models/anaerobic_digestor.py
  watertap/unit_models/tests/test_anaerobic_digestor.py
Labels: Priority:High

#904 ADM1 Documentation
  docs/technical_reference/property_models/ADM1.rst
  docs/technical_reference/property_models/index.rst
Labels: documentation, amo

#878 ADM1 Unit Model Documentation
  docs/_static/unit_models/anaerobic_digestor.png
  docs/technical_reference/unit_models/anaerobic_digestor.rst
  docs/technical_reference/unit_models/index.rst
Labels: documentation, Priority:Normal

#915 Minor ADM1 Refinement
  docs/technical_reference/property_models/ADM1.rst
  docs/technical_reference/unit_models/anaerobic_digestor.rst
  watertap/examples/flowsheets/case_studies/anaerobic_digestor/ADM1_flowsheet.py
  watertap/property_models/anaerobic_digestion/adm1_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/unit_models/anaerobic_digestor.py
  watertap/unit_models/tests/test_anaerobic_digestor.py
Labels: documentation, Priority:Normal

#911 Reorganize zero order costing methods
  watertap/core/tests/test_zero_order_costing.py
  watertap/core/zero_order_base.py
  watertap/core/zero_order_costing.py
  watertap/unit_models/zero_order/CANDOP_zo.py
  watertap/unit_models/zero_order/anaerobic_mbr_mec_zo.py
  watertap/unit_models/zero_order/aop_addition_zo.py
  watertap/unit_models/zero_order/autothermal_hydrothermal_liquefaction_zo.py
  watertap/unit_models/zero_order/brine_concentrator_zo.py
  watertap/unit_models/zero_order/centrifuge_zo.py
  watertap/unit_models/zero_order/chemical_addition_zo.py
  watertap/unit_models/zero_order/chlorination_zo.py
  watertap/unit_models/zero_order/clarifier_zo.py
  watertap/unit_models/zero_order/cloth_media_filtration_zo.py
  watertap/unit_models/zero_order/coag_and_floc_zo.py
  watertap/unit_models/zero_order/cofermentation_zo.py
  watertap/unit_models/zero_order/constructed_wetlands_zo.py
  watertap/unit_models/zero_order/deep_well_injection_zo.py
  watertap/unit_models/zero_order/dmbr_zo.py
  watertap/unit_models/zero_order/electrochemical_nutrient_removal_zo.py
  watertap/unit_models/zero_order/evaporation_pond_zo.py
  watertap/unit_models/zero_order/filter_press_zo.py
  watertap/unit_models/zero_order/fixed_bed_zo.py
  watertap/unit_models/zero_order/gac_zo.py
  watertap/unit_models/zero_order/hrcs_zo.py
  watertap/unit_models/zero_order/hydrothermal_gasification_zo.py
  watertap/unit_models/zero_order/ion_exchange_zo.py
  watertap/unit_models/zero_order/iron_and_manganese_removal_zo.py
  watertap/unit_models/zero_order/landfill_zo.py
  watertap/unit_models/zero_order/mabr_zo.py
  watertap/unit_models/zero_order/magprex_zo.py
  watertap/unit_models/zero_order/membrane_evaporator_zo.py
  watertap/unit_models/zero_order/metab_zo.py
  watertap/unit_models/zero_order/microbial_battery_zo.py
  watertap/unit_models/zero_order/nanofiltration_zo.py
  watertap/unit_models/zero_order/ozone_aop_zo.py
  watertap/unit_models/zero_order/ozone_zo.py
  watertap/unit_models/zero_order/peracetic_acid_disinfection_zo.py
  watertap/unit_models/zero_order/photothermal_membrane_zo.py
  watertap/unit_models/zero_order/pump_electricity_zo.py
  watertap/unit_models/zero_order/sedimentation_zo.py
  watertap/unit_models/zero_order/storage_tank_zo.py
  watertap/unit_models/zero_order/struvite_classifier_zo.py
  watertap/unit_models/zero_order/suboxic_activated_sludge_process_zo.py
  watertap/unit_models/zero_order/supercritical_salt_precipitation_zo.py
  watertap/unit_models/zero_order/surface_discharge_zo.py
  watertap/unit_models/zero_order/tests/test_zo_documentation.py
  watertap/unit_models/zero_order/uv_aop_zo.py
  watertap/unit_models/zero_order/uv_zo.py
  watertap/unit_models/zero_order/vfa_recovery_zo.py
  watertap/unit_models/zero_order/well_field_zo.py
Labels: Priority:Normal

#918 ADM1 temperature dependent physico-chemical parameters
  watertap/property_models/anaerobic_digestion/adm1_properties.py
  watertap/property_models/anaerobic_digestion/adm1_properties_vapor.py
  watertap/property_models/anaerobic_digestion/adm1_reactions.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_vapor_thermo.py
  watertap/unit_models/anaerobic_digestor.py
  watertap/unit_models/tests/test_anaerobic_digestor.py
Labels: Priority:Normal

#920 Adding BVT as a GAC performance variable
  docs/technical_reference/unit_models/gac.rst
  watertap/unit_models/gac.py
  watertap/unit_models/tests/test_gac.py
Labels: enhancement, Priority:Normal

#917 Pylint: enable all errors passing on main
  pyproject.toml
  watertap/edb/tests/test_commands.py
  watertap/edb/tests/test_data_model.py
  watertap/examples/flowsheets/oaro/oaro.py
Labels: Priority:Normal

#924 [pylint] not-callable
  pyproject.toml
  watertap/core/tests/test_zero_order_base.py
  watertap/core/tests/test_zero_order_diso.py
  watertap/core/tests/test_zero_order_electricity.py
  watertap/core/tests/test_zero_order_pt.py
  watertap/core/tests/test_zero_order_sido.py
  watertap/core/tests/test_zero_order_sido_reactive.py
  watertap/core/tests/test_zero_order_siso.py
  watertap/core/zero_order_base.py
  watertap/core/zero_order_diso.py
  watertap/core/zero_order_pt.py
  watertap/core/zero_order_sido.py
  watertap/core/zero_order_sido_reactive.py
  watertap/core/zero_order_siso.py
  watertap/unit_models/zero_order/gas_sparged_membrane_zo.py
  watertap/unit_models/zero_order/tests/test_gas_sparged_membrane.py
Labels: Priority:Normal

#926 Updating Magprex & HRCS Costing and Decision Variables
  watertap/data/techno_economic/centrifuge.yaml
  watertap/data/techno_economic/magprex.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_case_1575.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/tests/test_hrcs.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_case_1575.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/tests/test_magprex.py
  watertap/unit_models/zero_order/magprex_zo.py
  watertap/unit_models/zero_order/tests/test_centrifuge_zo.py
Labels: Priority:Normal, amo

#873 Electrodialysis flowsheet with pumps and flow recirculation
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc.py
  watertap/examples/flowsheets/electrodialysis/tests/test_electrodialysis_1stack_conc_recirc.py
Labels: Priority:Normal

#931 Update electroN_P model
  watertap/data/techno_economic/electrochemical_nutrient_removal.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/case_1617.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/tests/test_electrochemical_nutrient_removal.py
  watertap/unit_models/zero_order/electrochemical_nutrient_removal_zo.py
  watertap/unit_models/zero_order/tests/test_electrochemical_nutrient_removal_zo.py
Labels: amo

#860 Reorganize sets in multicomponent aq solution proper pack
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/unit_models/tests/test_gac.py
Labels: Priority:Normal

#807 Making Flowsheets More User-Friendly
  watertap/core/util/initialization.py
  watertap/core/util/tests/test_initialization.py
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM1_flowsheet.py
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM2D_flowsheet.py
  watertap/examples/flowsheets/case_studies/activated_sludge/ASM2D_flowsheet_noPHA.py
  watertap/examples/flowsheets/case_studies/municipal_treatment/municipal_treatment.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_activated_sludge_process.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/multi_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt.py
  watertap/examples/flowsheets/electrodialysis/electrodialysis_1stack.py
Labels: Priority:Normal

#893 Adding Friction Factor Config Option
  watertap/core/__init__.py
  watertap/core/membrane_channel_base.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal

#896 Moving GAC properties to MCAS, `DiffusivityCalculation` as an MCAS argument
  watertap/core/util/scaling.py
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/gac.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
  watertap/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
  watertap/unit_models/tests/test_nanofiltration_DSPMDE_0D.py
  watertap/unit_models/tests/test_uv_aop.py
Labels: enhancement, Priority:Normal
