Repository watertap-org/watertap, pull requests merged in 2024-10, with the labels that each got.

#1492 BSM2-P Effluent Metrics w/o Flowsheet Constraints
  docs/technical_reference/flowsheets/extended_BSM2.rst
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension_ui.png
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_ui.png
  watertap/property_models/unit_specific/activated_sludge/asm1_properties.py
  watertap/property_models/unit_specific/activated_sludge/modified_asm2d_properties.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_asm1_thermo.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_modified_asm2d_thermo.py
  watertap/unit_models/tests/test_aeration_tank.py
  watertap/unit_models/tests/test_dewatering_unit.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm1.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm2d.py
  watertap/unit_models/translators/tests/test_translator_asm1_adm1.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
Labels: Priority:Normal

#1507 Update Getting Started Documentation
  docs/getting_started.rst
Labels: documentation, Priority:Normal

#1506 Delete Simple Modified ASM2d
  watertap/property_models/unit_specific/activated_sludge/tests/test_simple_modified_asm2d_reaction.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_simple_modified_asm2d_thermo.py
  watertap/unit_models/tests/test_electroNP_ZO.py
  watertap/unit_models/translators/tests/test_translator_adm1_simple_asm2d.py
  watertap/unit_models/translators/translator_adm1_simple_asm2d.py
Labels: Priority:Normal

#1501 Add initialize function to fsapi
  watertap/ui/fsapi.py
Labels: Priority:Normal

#1471 Enable RO0D to be dynamic
  .github/workflows/checks.yml
  watertap/core/membrane_channel_base.py
  watertap/property_models/NaCl_prop_pack.py
  watertap/unit_models/reverse_osmosis_0D.py
  watertap/unit_models/tests/test_cstr.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
Labels: Priority:Normal, IDAES, dynamics

#1487 MCAS w/generic crystallizer
  docs/technical_reference/property_models/mc_aq_sol.rst
  docs/technical_reference/property_models/seawater.rst
  watertap/costing/unit_models/surrogate_crystallizer.py
  watertap/data/surrogate_defaults/__init__.py
  watertap/data/surrogate_defaults/surrogate_crystallizer_defaults/Anhydrite_g.json
  watertap/data/surrogate_defaults/surrogate_crystallizer_defaults/Calcite_g.json
  watertap/data/surrogate_defaults/surrogate_crystallizer_defaults/Glauberite_g.json
  watertap/data/surrogate_defaults/surrogate_crystallizer_defaults/Halite_g.json
  watertap/data/surrogate_defaults/surrogate_crystallizer_defaults/Vapor_Pressure.json
  watertap/data/surrogate_defaults/surrogate_crystallizer_defaults/__init__.py
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/unit_models/surrogate_crystallizer.py
  watertap/unit_models/tests/test_surrogate_crystallizer.py
Labels: Priority:Normal
