Repository watertap-org/watertap, pull requests merged in 2024-05, with the labels that each got.

#1342 Add SKK Documentation
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/reverse_osmosis_1D.rst
Labels: Priority:Normal

#1357 GUI for Extended BSM2 Flowsheet
  .github/workflows/checks.yml
  setup.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension_ui.png
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension_ui.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
Labels: Priority:Normal

#1352 Combine Dye Desal Flowsheets
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_sweep.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_sweep.py
Labels: Priority:Normal

#1378 Passing through the base solver attributes for solver wrapper
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
Labels: Priority:High

#1376 Flowsheets documentation ADM1, ASM1, ASM2d
  docs/_static/flowsheets/ADM1.png
  docs/_static/flowsheets/ASM1.png
  docs/_static/flowsheets/ASM2d.png
  docs/technical_reference/flowsheets/ADM1.rst
  docs/technical_reference/flowsheets/ASM1.rst
  docs/technical_reference/flowsheets/ASM2d.rst
  docs/technical_reference/flowsheets/index.rst
Labels: documentation, 1.0

#1346 Rename fsapi.FlowsheetExport dict() method and model_objects field to resolve Pydantic 2.0 warnings
  watertap/ui/fsapi.py
  watertap/ui/tests/test_flowsheet_interfaces.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:Normal, ui, dependencies, fsapi, deprecation

#1381 Update idaes-pse requirement to support Pyomo 6.7.2
  setup.py
Labels: Priority:High

#1379 CSTR and Clarifier Unit Model Documentation
  docs/technical_reference/flowsheets/ASM1.rst
  docs/technical_reference/flowsheets/ASM2d.rst
  docs/technical_reference/flowsheets/BSM2.rst
  docs/technical_reference/flowsheets/extended_BSM2.rst
  docs/technical_reference/unit_models/aeration_tank.rst
  docs/technical_reference/unit_models/clarifier.rst
  docs/technical_reference/unit_models/cstr.rst
  docs/technical_reference/unit_models/cstr_injection.rst
  docs/technical_reference/unit_models/index.rst
Labels: Priority:High, 1.0

#1362 Replacing Expr_if & Changing Bio_P Default
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:Normal

#1375 GAC costing documentation into template dedicated file
  docs/technical_reference/costing/gac.rst
  docs/technical_reference/unit_models/gac.rst
Labels: Priority:High, 1.0

#1386 Doc for second electrodialysis flowsheet
  docs/_static/flowsheets/edfs.png
  docs/technical_reference/flowsheets/electrodialysis_1stack.rst
  docs/technical_reference/flowsheets/index.rst
Labels: Priority:Normal

#1390 Custom Model Demo Rework
  tutorials/creating_a_simple_property_model.ipynb
  tutorials/creating_a_simple_unit_model.ipynb
  tutorials/using_a_simple_property_model.ipynb
  tutorials/using_a_simple_unit_model.ipynb
  watertap/examples/custom_model_demo/__init__.py
  watertap/examples/custom_model_demo/demo_simple_filter.py
  watertap/examples/custom_model_demo/demo_simple_prop_pack.py
  watertap/examples/custom_model_demo/simple_filter.py
  watertap/examples/custom_model_demo/simple_prop_pack.py
  watertap/examples/custom_model_demo/tests/__init__.py
  watertap/examples/custom_model_demo/tests/test_demo_simple_filter.py
  watertap/examples/custom_model_demo/tests/test_demo_simple_prop_pack.py
Labels: Priority:High, 1.0

#1178 Create landing page for tutorials
  docs/conf.py
  docs/how_to_guides/notebooks.rst
  docs/tutorials/index.rst
  tutorials/00-index.ipynb
  tutorials/creating_a_simple_property_model.ipynb
  tutorials/introduction.ipynb
  tutorials/modeling_multicomponent_rejection.ipynb
  tutorials/oli_calculations.ipynb
  tutorials/parameter_sweep_demo.ipynb
  tutorials/parmest_demo/parmest_example.ipynb
  tutorials/unit_model_customization_example.ipynb
  tutorials/using_a_simple_property_model.ipynb
  tutorials/using_a_simple_unit_model.ipynb
Labels: documentation, Priority:High, jupyter, 1.0

#1377 Add documentation for electroNP, OARO and UV-AOP
  docs/technical_reference/costing/electroNP.rst
  docs/technical_reference/costing/osmotically_assisted_reverse_osmosis.rst
  docs/technical_reference/costing/uv_aop.rst
Labels: Priority:High, 1.0

#1391 Update crystallizer costing documentation
  docs/technical_reference/costing/crystallizer.rst
Labels: Priority:Normal

#1392 Electrolyzer costing documentation into template dedicated file
  docs/technical_reference/costing/electrolyzer.rst
  docs/technical_reference/costing/gac.rst
  docs/technical_reference/unit_models/electrolyzer.rst
Labels: Priority:High, 1.0

#1395 Add More Costing Documentation
  docs/technical_reference/costing/clarifier.rst
  docs/technical_reference/costing/cstr_injection.rst
  docs/technical_reference/costing/dewatering.rst
  docs/technical_reference/costing/energy_recovery_device.rst
  docs/technical_reference/costing/nanofiltration.rst
  docs/technical_reference/costing/pressure_exchanger.rst
  docs/technical_reference/costing/pump.rst
  docs/technical_reference/costing/reverse_osmosis.rst
  docs/technical_reference/costing/thickener.rst
Labels: documentation, Priority:Normal, 1.0

#1401 Apply UnitTestHarness to IonExchange0D
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: Priority:High, 1.0

#1394 Update Costing Doc Automation
  docs/technical_reference/costing/aeration_tank.rst
  docs/technical_reference/costing/anaerobic_digester.rst
  docs/technical_reference/costing/automate_detailed_unit_costing_rst_file.py
  docs/technical_reference/costing/clarifier.rst
  docs/technical_reference/costing/compressor.rst
  docs/technical_reference/costing/crystallizer.rst
  docs/technical_reference/costing/cstr.rst
  docs/technical_reference/costing/cstr_injection.rst
  docs/technical_reference/costing/dewatering.rst
  docs/technical_reference/costing/electroNP.rst
  docs/technical_reference/costing/electrodialysis.rst
  docs/technical_reference/costing/electrolyzer.rst
  docs/technical_reference/costing/evaporator.rst
  docs/technical_reference/costing/gac.rst
  docs/technical_reference/costing/heat_exchanger.rst
  docs/technical_reference/costing/heater_chiller.rst
  docs/technical_reference/costing/ion_exchange.rst
  docs/technical_reference/costing/membrane_distillation.rst
  docs/technical_reference/costing/mixer.rst
  docs/technical_reference/costing/osmotically_assisted_reverse_osmosis.rst
  docs/technical_reference/costing/pressure_exchanger.rst
  docs/technical_reference/costing/reverse_osmosis.rst
  docs/technical_reference/costing/stoichiometric_reactor.rst
  docs/technical_reference/costing/thickener.rst
  docs/technical_reference/costing/uv_aop.rst
Labels: documentation, Priority:Normal, 1.0

#1403 Flowsheet documentation for NaCl crystallizer
  docs/_static/flowsheets/crystallizer.jpg
  docs/technical_reference/flowsheets/crystallization.rst
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/unit_models/crystallizer_0D.rst
Labels: Priority:High, 1.0

#1385 Doc for electrodialysis flowsheet
  docs/_static/flowsheets/ed_conc_recirc.png
  docs/technical_reference/flowsheets/electrodialysis_1stack_conc_recirc.rst
  docs/technical_reference/flowsheets/index.rst
Labels: Priority:Normal, 1.0

#1402 IonExchange0D costing documentation into template dedicated file
  docs/technical_reference/costing/gac.rst
  docs/technical_reference/costing/ion_exchange.rst
  docs/technical_reference/unit_models/ion_exchange_0D.rst
Labels: Priority:Normal, 1.0

#1412 improved error message.
  watertap/core/plugins/solvers.py
Labels: Priority:Normal

#1396 Flowsheet Documentation for GAC
  docs/_static/flowsheets/gac.png
  docs/conf.py
  docs/technical_reference/flowsheets/gac.rst
  docs/technical_reference/flowsheets/index.rst
Labels: Priority:High, 1.0

#1371 test harness for unit models of waste treatment
  watertap/unit_models/tests/test_cstr.py
  watertap/unit_models/tests/test_cstr_injection.py
  watertap/unit_models/tests/test_thickener_unit.py
Labels: Priority:Normal
