Repository watertap-org/watertap, pull requests merged in 2024-06, with the labels that each got.

#1420 IX model small fix for anions in demo
  watertap/examples/flowsheets/ion_exchange/ion_exchange_demo.py
  watertap/examples/flowsheets/ion_exchange/tests/test_ion_exchange_demo.py
  watertap/unit_models/ion_exchange_0D.py
Labels: Priority:High, 1.0

#1422 Remove legacy WT3 data files
  watertap/examples/flowsheets/case_studies/case_study_basis.csv
  watertap/examples/flowsheets/case_studies/case_study_water_sources.csv
  watertap/examples/flowsheets/case_studies/constituent_removal.csv
  watertap/examples/flowsheets/case_studies/electricity_costs.csv
  watertap/examples/flowsheets/case_studies/plant_cost_indices.csv
  watertap/examples/flowsheets/case_studies/treatment_train_setup.csv
  watertap/examples/flowsheets/case_studies/water_recovery.csv
Labels: wt3 migration

#1413 Add chart options to fsapi
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:High

#1421 Update idaes-pse requirement in preparation to 2.5 release
  setup.py
Labels: Priority:High, IDAES, PrOMMiS

#1411 Add more input options for OARO GUI
  watertap/examples/flowsheets/oaro/oaro_multi_ui.py
Labels: Priority:Normal, 1.0

#1415 Boron removal unit test harness
  watertap/unit_models/boron_removal.py
  watertap/unit_models/tests/test_boron_removal.py
Labels: Priority:High

#1418 Flowsheet documentation for IX
  docs/_static/flowsheets/ion_exchange.png
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/flowsheets/ion_exchange.rst
Labels: Priority:High, 1.0

#1417 Delete Simple IEDO GUI Flowsheets
  setup.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/GLSD_anaerobic_digester/GLSD_anaerobic_digestion_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_hrcs/hrcs_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1575_magprex/magprex_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1595_photothermal_membrane_candoP/amo_1595_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/amo_1690/amo_1690_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/biomembrane_filtration/biomembrane_filtration_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/electrochemical_nutrient_removal/electrochemical_nutrient_removal_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/groundwater_treatment/groundwater_treatment_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/metab/metab_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/peracetic_acid_disinfection/peracetic_acid_disinfection_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_ASM_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/suboxic_activated_sludge_process/suboxic_ASM_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/supercritical_sludge_to_gas/supercritical_sludge_to_gas_ui.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_ui.png
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/swine_wwt/swine_wwt_ui.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:Normal

#1388 Fix bubblepoint function and unit inconsistency in OLI API
  watertap/tools/oli_api/client.py
  watertap/tools/oli_api/conftest.py
  watertap/tools/oli_api/flash.py
  watertap/tools/oli_api/tests/test_client.py
  watertap/tools/oli_api/tests/test_flash.py
  watertap/tools/oli_api/util/fixed_keys_dict.py
  watertap/tools/oli_api/util/tests/test_fixed_keys_dict.py
Labels: Priority:High, oli, 1.0

#1431 cyipopt-watertap
  .github/workflows/checks.yml
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
Labels: Priority:Normal

#1432 Remove code, docs, and references for EDB
  bin/document_schemas.py
  docs/background/index.rst
  docs/background/why_use_edb.rst
  docs/examples/edb/edb_example.ipynb
  docs/examples/edb/multiple_phases_example.ipynb
  docs/examples/edb/simple_acid_example.ipynb
  docs/how_to_guides/edb_api.rst
  docs/how_to_guides/edb_cli.rst
  docs/how_to_guides/how_to_install_electrolyte_database.rst
  docs/how_to_guides/how_to_setup_simple_chemistry.rst
  docs/how_to_guides/how_to_use_EDB.rst
  docs/how_to_guides/how_to_use_apparent_and_true_chemical_species.rst
  docs/how_to_guides/index.rst
  docs/technical_reference/edb/index.rst
  docs/technical_reference/edb/schemas/component.html
  docs/technical_reference/edb/schemas/component.json
  docs/technical_reference/edb/schemas/reaction.html
  docs/technical_reference/edb/schemas/reaction.json
  docs/technical_reference/edb/schemas/schema_doc.css
  docs/technical_reference/edb/schemas/schema_doc.min.js
  docs/technical_reference/index.rst
  setup.py
  watertap/conftest.py
  watertap/edb/__init__.py
  watertap/edb/commands.py
  watertap/edb/data/__init__.py
  watertap/edb/data/base.json
  watertap/edb/data/component.json
  watertap/edb/data/reaction.json
  watertap/edb/data_model.py
  watertap/edb/db_api.py
  watertap/edb/error.py
  watertap/edb/schemas.py
  watertap/edb/tests/__init__.py
  watertap/edb/tests/data.py
  watertap/edb/tests/test_commands.py
  watertap/edb/tests/test_data_model.py
  watertap/edb/tests/test_db_api.py
  watertap/edb/tests/test_edb.py
  watertap/edb/tests/test_schemas.py
  watertap/edb/tests/test_validate.py
  watertap/edb/tests/util.py
  watertap/edb/validate.py
  watertap/examples/edb/__init__.py
  watertap/examples/edb/simple_acid.py
  watertap/examples/edb/solid_precipitation_reactions.py
  watertap/examples/edb/tests/__init__.py
  watertap/examples/edb/tests/conftest.py
  watertap/examples/edb/tests/test__fixtures.py
  watertap/examples/edb/tests/test_edb_examples.py
  watertap/examples/edb/the_basics.py
  watertap/examples/edb/vapor_liquid_equilibrium.py
  watertap/tests/conftest.py
Labels: Priority:Normal, 1.0

#1441 Exclude NumPy v2 when installing CyIpopt via conda-forge to resolve #1440
  .github/workflows/checks.yml
Labels: Priority:High, dependencies

#1433 Adding anaerobic digester cost
  docs/technical_reference/costing/anaerobic_digester.rst
Labels: documentation, Priority:Normal, costing, 1.0

#1448 Resolve Codecov upload failures
  .github/workflows/checks.yml
  .github/workflows/mpi4py-test.yml
Labels: Priority:High

#1428 Remove Units from Report Strings
  watertap/unit_models/MD/membrane_distillation_base.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/nanofiltration_DSPMDE_0D.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:Normal, 1.0

#1404 Interval Initializer
  watertap/core/util/initialization.py
  watertap/core/util/tests/test_initialization.py
  watertap/examples/flowsheets/MD/MD_single_stage_continuous_recirculation.py
  watertap/examples/flowsheets/case_studies/electroNP/BSM2_electroNP_no_bioP.py
  watertap/examples/flowsheets/case_studies/municipal_treatment/municipal_treatment.py
  watertap/unit_models/MD/membrane_distillation_base.py
  watertap/unit_models/coag_floc_model.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/electrolyzer.py
  watertap/unit_models/gac.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/pressure_exchanger.py
  watertap/unit_models/reverse_osmosis_base.py
Labels: Priority:High

#1436 Remove NF_With_Bypass flowsheet from UI
  setup.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass_ui.py
Labels: Priority:Normal, 1.0

#1425 Flowsheet documentation for seawater RO desalination
  docs/_static/flowsheets/SW_RO_fs_desal_PXR.png
  docs/_static/flowsheets/SW_RO_fs_desal_turbine.png
  docs/_static/flowsheets/SW_RO_fs_full.png
  docs/_static/flowsheets/SW_RO_fs_posttreat.png
  docs/_static/flowsheets/SW_RO_fs_pretreat.png
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/flowsheets/seawater_RO_desalination.rst
Labels: Priority:High, 1.0

#1434 Enable GreyBoxBlocks with cyipopt-watertap
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
Labels: Priority:Normal

#1430 MVC Flowsheet Documentation
  docs/_static/flowsheets/mvc.png
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/flowsheets/mvc.rst
Labels: Priority:High, 1.0

#1442 add costing docs for evaporator, compressor, heat exchanger, heater/c…
  docs/technical_reference/costing/compressor.rst
  docs/technical_reference/costing/evaporator.rst
  docs/technical_reference/costing/heat_exchanger.rst
  docs/technical_reference/costing/heater_chiller.rst
  docs/technical_reference/costing/membrane_distillation.rst
Labels: Priority:High, 1.0

#1454 ED Cost Documentation
  docs/technical_reference/costing/electrodialysis.rst
  watertap/costing/unit_models/electrodialysis.py
  watertap/costing/util.py
Labels: documentation, Priority:Normal

#1450 add documentation for LSRRO flowsheet
  docs/_static/flowsheets/lsrro.png
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/flowsheets/lsrro.rst
Labels: documentation, Priority:High, 1.0

#1444 add documentation for MD flowsheet
  docs/_static/flowsheets/MD.png
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/flowsheets/membrane_distillation.rst
Labels: Priority:High, 1.0

#1446 Flowsheet documentation for RO w/ ERD
  docs/_static/flowsheets/RO_w_ERD-PXR.png
  docs/_static/flowsheets/RO_w_ERD-no_ERD.png
  docs/_static/flowsheets/RO_w_ERD-turbine.png
  docs/technical_reference/flowsheets/RO_with_energy_recovery.rst
  docs/technical_reference/flowsheets/index.rst
Labels: Priority:High, 1.0

#1416 Adding Conservation Tests to the Test Harness
  docs/how_to_guides/how_to_use_unit_test_harness.rst
  watertap/examples/flowsheets/case_studies/municipal_treatment/municipal_treatment.py
  watertap/unit_models/tests/test_anaerobic_digester.py
  watertap/unit_models/tests/test_boron_removal.py
  watertap/unit_models/tests/test_clarifier.py
  watertap/unit_models/tests/test_coag_floc_model.py
  watertap/unit_models/tests/test_crystallizer.py
  watertap/unit_models/tests/test_cstr.py
  watertap/unit_models/tests/test_cstr_injection.py
  watertap/unit_models/tests/test_electrolyzer.py
  watertap/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
  watertap/unit_models/tests/test_membrane_distillation_0D.py
  watertap/unit_models/tests/test_membrane_distillation_1D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_1D.py
  watertap/unit_models/tests/test_pressure_changer.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
  watertap/unit_models/tests/test_thickener_unit.py
  watertap/unit_models/tests/unit_test_harness.py
Labels: Priority:Normal

#1458 Enable concentration factor survey in OLI API
  watertap/tools/oli_api/flash.py
  watertap/tools/oli_api/util/fixed_keys_dict.py
  watertap/tools/oli_api/util/tests/test_fixed_keys_dict.py
Labels: oli, :cherries: Merge to rel, 1.0

#1452 Add documentation of pump and ERD
  docs/technical_reference/unit_models/energy_recovery_device.rst
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/pump.rst
Labels: documentation, Priority:High, 1.0

#1456 Mixer Cost Documentation
  docs/technical_reference/costing/mixer.rst
Labels: documentation, Priority:High, 1.0

#1447 Updating copyright year to 2024
  COPYRIGHT.md
  LICENSE.md
  docs/conf.py
  watertap/core/plugins/solvers.py
  watertap/flowsheets/electroNP/BSM2_electroNP_no_bioP.py
  watertap/flowsheets/electroNP/tests/test_BSM2_electroNP_no_bioP.py
  watertap/flowsheets/oaro/oaro_multi_ui.py
  watertap/unit_models/MD/MD_channel_1D.py
  watertap/unit_models/MD/membrane_distillation_1D.py
  watertap/unit_models/tests/test_aeration_tank.py
Labels: Priority:Normal, 1.0
