Repository watertap-org/watertap, pull requests merged in 2024-02, with the labels that each got.

#1282 fix deprecation warnings in water and seawater prop packs
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/water_prop_pack.py
Labels: Priority:Normal, property_model, deprecation

#1260 add continuous recirculation DCMD flowsheet
  watertap/costing/__init__.py
  watertap/costing/costing_base.py
  watertap/costing/unit_models/heater_chiller.py
  watertap/costing/unit_models/membrane_distillation.py
  watertap/costing/unit_models/pump.py
  watertap/examples/flowsheets/MD/MD_single_stage_continuous_recirculation.py
  watertap/examples/flowsheets/MD/__init__.py
  watertap/examples/flowsheets/MD/tests/__init__.py
  watertap/examples/flowsheets/MD/tests/test_MD.py
  watertap/unit_models/MD/membrane_distillation_base.py
  watertap/unit_models/tests/test_membrane_distillation_0D.py
Labels: Priority:Normal

#1263 BSM2 Flowsheet Documentation
  docs/_static/flowsheets/BSM2.png
  docs/_static/unit_models/anaerobic_digester.png
  docs/technical_reference/flowsheets/BSM2.rst
  docs/technical_reference/flowsheets/extended_BSM2.rst
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/index.rst
  docs/technical_reference/unit_models/anaerobic_digester.rst
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/translators/translator_adm1_asm1.rst
  docs/technical_reference/unit_models/translators/translator_adm1_asm2d.rst
  docs/technical_reference/unit_models/translators/translator_asm1_adm1.rst
  docs/technical_reference/unit_models/translators/translator_asm2d_adm1.rst
  tutorials/BSM2.ipynb
  watertap/costing/unit_models/anaerobic_digester.py
  watertap/examples/flowsheets/case_studies/anaerobic_digester/ADM1_flowsheet.py
  watertap/examples/flowsheets/case_studies/anaerobic_digester/tests/test_adm1_flowsheet.py
  watertap/examples/flowsheets/case_studies/electroNP/electroNP_flowsheet.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_ui.py
  watertap/property_models/anaerobic_digestion/tests/test_adm1_reaction.py
  watertap/property_models/anaerobic_digestion/tests/test_modified_adm1_reaction.py
  watertap/unit_models/__init__.py
  watertap/unit_models/anaerobic_digester.py
  watertap/unit_models/tests/test_anaerobic_digestor.py
Labels: documentation, Priority:Normal

#1277 Unit Model Test Harness
  watertap/unit_models/tests/test_anaerobic_digestor.py
  watertap/unit_models/tests/unit_test_harness.py
Labels: Priority:Normal

#1278 Dye Desalination TEA Update
  watertap/costing/unit_models/dewatering.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_global_costing.yaml
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
Labels: Priority:Normal

#1288 Test Harness Documentation
  docs/how_to_guides/how_to_use_property_test_harness.rst
  docs/how_to_guides/how_to_use_unit_test_harness.rst
  docs/how_to_guides/index.rst
Labels: Priority:Normal

#1316 Work around for issue #1312
  tutorials/parameter_sweep_demo.ipynb
  watertap/tools/parallel/parallel_manager_factory.py
Labels: parameter-sweep

#1315 ASM2d/ADM1 Translator Update
  docs/technical_reference/unit_models/translators/translator_asm2d_adm1.rst
  watertap/property_models/activated_sludge/modified_asm2d_reactions.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:Normal

#1244 Tinkering with BSM2 Optimization
  pytest.ini
  watertap/costing/unit_models/cstr.py
  watertap/costing/unit_models/cstr_injection.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
  watertap/property_models/activated_sludge/asm1_reactions.py
  watertap/unit_models/__init__.py
  watertap/unit_models/aeration_tank.py
  watertap/unit_models/anaerobic_digester.py
  watertap/unit_models/cstr_injection.py
  watertap/unit_models/tests/test_cstr.py
  watertap/unit_models/tests/test_cstr_injection.py
Labels: Priority:High

#1317 Make sure top-level model is not garbage collected in UnitTestHarness
  docs/how_to_guides/how_to_use_unit_test_harness.rst
  watertap/unit_models/tests/test_anaerobic_digestor.py
  watertap/unit_models/tests/unit_test_harness.py
Labels: Priority:High
