Repository watertap-org/watertap, pull requests merged in 2024-04, with the labels that each got.

#1350 improves compressor initialization
  watertap/unit_models/mvc/components/compressor.py
  watertap/unit_models/mvc/tests/test_mvc.py
Labels: Priority:Normal, nawi

#1368 modifies MD0D test to use unit test harness
  watertap/unit_models/tests/test_membrane_distillation_0D.py
  watertap/unit_models/tests/test_membrane_distillation_1D.py
  watertap/unit_models/tests/unit_test_harness.py
Labels: Priority:Normal

#1367 Unit test harness for OARO models
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_1D.py
Labels: Priority:Normal

#1354 BSM2 Flowsheet Documentation Update
  docs/_static/flowsheets/BSM2.png
  docs/_static/flowsheets/extended_BSM2.png
  docs/technical_reference/flowsheets/BSM2.rst
  docs/technical_reference/flowsheets/extended_BSM2.rst
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/property_models/activated_sludge/modified_asm2d_properties.py
Labels: Priority:High, 1.0

#1363 Pressure Changer and Coag & Floc Test Harness
  watertap/unit_models/tests/test_coag_floc_model.py
  watertap/unit_models/tests/test_pressure_changer.py
Labels: Priority:Normal

#1326 Convert ipopt-watertap to a solver wrapper
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solvers.py
Labels: Priority:Normal

#1272 Adding spiral-wound vs flat-sheet config options to RO and OARO
  docs/technical_reference/unit_models/osmotically_assisted_reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/osmotically_assisted_reverse_osmosis_1D.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/reverse_osmosis_1D.rst
  watertap/core/membrane_channel_base.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_1D.py
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/reverse_osmosis_1D.py
  watertap/unit_models/reverse_osmosis_base.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_1D.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
Labels: Priority:Normal, 1.0

#1361 Costing docs- initial template rollout
  docs/technical_reference/costing/WT_unit_costing_for_docs.csv
  docs/technical_reference/costing/anaerobic_digester.rst
  docs/technical_reference/costing/automate_detailed_unit_costing_rst_file.py
  docs/technical_reference/costing/clarifier.rst
  docs/technical_reference/costing/compressor.rst
  docs/technical_reference/costing/costing_base.rst
  docs/technical_reference/costing/crystallizer.rst
  docs/technical_reference/costing/cstr.rst
  docs/technical_reference/costing/cstr_injection.rst
  docs/technical_reference/costing/detailed_unit_model_costing.rst
  docs/technical_reference/costing/dewatering.rst
  docs/technical_reference/costing/electroNP.rst
  docs/technical_reference/costing/electrodialysis.rst
  docs/technical_reference/costing/electrolyzer.rst
  docs/technical_reference/costing/energy_recovery_device.rst
  docs/technical_reference/costing/evaporator.rst
  docs/technical_reference/costing/gac.rst
  docs/technical_reference/costing/heat_exchanger.rst
  docs/technical_reference/costing/heater_chiller.rst
  docs/technical_reference/costing/index.rst
  docs/technical_reference/costing/ion_exchange.rst
  docs/technical_reference/costing/membrane_distillation.rst
  docs/technical_reference/costing/mixer.rst
  docs/technical_reference/costing/nanofiltration.rst
  docs/technical_reference/costing/osmotically_assisted_reverse_osmosis.rst
  docs/technical_reference/costing/pressure_exchanger.rst
  docs/technical_reference/costing/pump.rst
  docs/technical_reference/costing/reverse_osmosis.rst
  docs/technical_reference/costing/stoichiometric_reactor.rst
  docs/technical_reference/costing/thickener.rst
  docs/technical_reference/costing/uv_aop.rst
Labels: Priority:High, 1.0
