Repository watertap-org/watertap, pull requests merged in 2024-03, with the labels that each got.

#1311 GAC Test Harness
  watertap/costing/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_gac.py
Labels: Priority:High

#1301 Clarifier, Crystallizer & RO Unit Test Harness
  watertap/unit_models/tests/test_anaerobic_digester.py
  watertap/unit_models/tests/test_clarifier.py
  watertap/unit_models/tests/test_crystallizer.py
  watertap/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_reverse_osmosis_1D.py
  watertap/unit_models/tests/unit_test_harness.py
Labels: Priority:Normal

#1321 Electrolyzer Test Harness
  watertap/costing/unit_models/tests/test_electrolyzer.py
  watertap/costing/unit_models/tests/test_gac.py
  watertap/unit_models/tests/test_electrolyzer.py
Labels: Priority:High

#1295 Changes to GAC model and GAC example flowsheet to solve when `MaterialFlowBasis.mass`
  watertap/examples/flowsheets/gac/gac.py
  watertap/examples/flowsheets/gac/gac_ui.py
  watertap/examples/flowsheets/gac/tests/test_gac.py
  watertap/unit_models/gac.py
Labels: Priority:Normal

#1327 Set `acceptable_constr_viol_tol` to `1e-08`
  watertap/core/plugins/solvers.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/examples/flowsheets/mvc/mvc_single_stage.py
  watertap/unit_models/anaerobic_digester.py
Labels: Priority:High

#1325 Enable solver logs in Unit Test Harness
  watertap/unit_models/tests/unit_test_harness.py
Labels: Priority:Normal

#1299 Costing Unification: reorganize classes and consistent calculation of capital annualization
  docs/technical_reference/costing/costing_base.rst
  docs/technical_reference/costing/index.rst
  docs/technical_reference/costing/watertap_costing.rst
  docs/technical_reference/costing/watertap_costing_detailed.rst
  docs/technical_reference/costing/zero_order_costing.rst
  watertap/costing/__init__.py
  watertap/costing/costing_base.py
  watertap/costing/tests/test_costing_base.py
  watertap/costing/tests/test_costing_interop.py
  watertap/costing/tests/test_zero_order_costing.py
  watertap/costing/watertap_costing_package.py
  watertap/costing/zero_order_costing.py
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery_ui.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/costing.py
  watertap/examples/flowsheets/lsrro/lsrro.py
  watertap/examples/flowsheets/lsrro/multi_sweep.py
  watertap/examples/flowsheets/mvc/mvc_single_stage_ui.py
  watertap/examples/flowsheets/nf_dspmde/nf_ui.py
  watertap/examples/flowsheets/nf_dspmde/nf_with_bypass_ui.py
  watertap/examples/flowsheets/oaro/oaro_multi.py
Labels: Priority:Normal

#1309 Update idaes-pse requirement in preparation of 2.4 IDAES release
  setup.py
Labels: Priority:High, IDAES

#1330 Upgrade pydantic version and update corresponding fsapi code
  setup.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:Normal

#1304 Add validity ranges and clean up water_prop_pack, seawater_prop_pack, and NaCl_T_dep_prop_pack
  docs/technical_reference/property_models/NaCl_T_dep.rst
  watertap/property_models/NaCl_T_dep_prop_pack.py
  watertap/property_models/seawater_prop_pack.py
  watertap/property_models/water_prop_pack.py
Labels: Priority:Normal

#1296 OLI API Flash update
  tutorials/conftest.py
  tutorials/incorporating_oli_calculations.ipynb
  watertap/tools/oli_api/client.py
  watertap/tools/oli_api/conftest.py
  watertap/tools/oli_api/flash.py
  watertap/tools/oli_api/tests/test_client.py
  watertap/tools/oli_api/tests/test_flash.py
  watertap/tools/oli_api/util/fixed_keys_dict.py
  watertap/tools/oli_api/util/watertap_to_oli_helper_functions.py
Labels: Priority:High, oli

#1333 add missed test for aeration tank
  watertap/unit_models/tests/test_aeration_tank.py
Labels: iedo

#1334 Delete nf_0d files
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/nanofiltration_0D.rst
  watertap/unit_models/__init__.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/tests/test_nanofiltration_0D.py
Labels: Priority:Normal, spring-cleaning

#1336 Remove selective oil permeation
  watertap/property_models/selective_oil_permeation_prop_pack.py
  watertap/property_models/tests/test_selective_oil_permeation_prop_pack.py
  watertap/unit_models/selective_oil_permeation.py
  watertap/unit_models/tests/test_selective_oil_permeation.py
Labels: Priority:Normal, spring-cleaning

#1335 Remove full treatment train
  docs/how_to_guides/how_to_contribute_development.rst
  watertap/examples/flowsheets/full_treatment_train/__init__.py
  watertap/examples/flowsheets/full_treatment_train/analysis/__init__.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF_no_bypass.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_NF_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_single_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_softening.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_softening_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/flowsheet_two_stage.py
  watertap/examples/flowsheets/full_treatment_train/analysis/multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/__init__.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_flowsheets.py
  watertap/examples/flowsheets/full_treatment_train/analysis/tests/test_multi_sweep.py
  watertap/examples/flowsheets/full_treatment_train/chemical_flowsheet_util.py
  watertap/examples/flowsheets/full_treatment_train/electrolyte_scaling_utils.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/__init__.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/__init__.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/posttreatment_ideal_naocl_chlorination_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/pretreatment_stoich_softening_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/__init__.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_posttreatment.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/chemistry/tests/test_pretreatment.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/costing.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/desalination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/examples/__init__.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/examples/full_example.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/examples/test_full_example.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/feed_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/gypsum_saturation_index.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/pretreatment_NF.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/pretreatment_softening.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/tests/__init__.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/tests/test_desalination.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/tests/test_pretreatment.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/tests/test_pretreatment_softening.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/tests/test_translator_block.py
  watertap/examples/flowsheets/full_treatment_train/flowsheet_components/translator_block.py
  watertap/examples/flowsheets/full_treatment_train/model_components/__init__.py
  watertap/examples/flowsheets/full_treatment_train/model_components/eNRTL/__init__.py
  watertap/examples/flowsheets/full_treatment_train/model_components/eNRTL/entrl_config_FTPx.py
  watertap/examples/flowsheets/full_treatment_train/model_components/eNRTL/entrl_config_FpcTP.py
  watertap/examples/flowsheets/full_treatment_train/model_components/eNRTL/test_enrtl.py
  watertap/examples/flowsheets/full_treatment_train/model_components/property_models.py
  watertap/examples/flowsheets/full_treatment_train/model_components/seawater_salt_prop_pack.py
  watertap/examples/flowsheets/full_treatment_train/model_components/tests/__init__.py
  watertap/examples/flowsheets/full_treatment_train/model_components/tests/test_prop_pack.py
  watertap/examples/flowsheets/full_treatment_train/model_components/tests/test_property_models.py
  watertap/examples/flowsheets/full_treatment_train/model_components/tests/test_unit_models.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_0DRO.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_1DRO.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_ZONF.py
  watertap/examples/flowsheets/full_treatment_train/model_components/unit_separator.py
  watertap/examples/flowsheets/full_treatment_train/util.py
Labels: Priority:Normal, spring-cleaning

#1290 Add GUI for OARO
  setup.py
  watertap/examples/flowsheets/oaro/OARO_multi_ui.png
  watertap/examples/flowsheets/oaro/oaro_multi_ui.py
Labels: Priority:Normal, :cherries: Merge to rel, ui

#1294 Adding GAC into Dye Desalination w/RO
  docs/technical_reference/flowsheets/extended_BSM2.rst
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
Labels: Priority:Normal, :cherries: Merge to rel

#1338 Minor MVC GUI Update
  watertap/examples/flowsheets/mvc/mvc_single_stage_ui.py
Labels: Priority:High, :cherries: Merge to rel

#1264 Add more detailed pressure exchanger
  docs/technical_reference/unit_models/pressure_exchanger.rst
  watertap/costing/unit_models/pressure_exchanger.py
  watertap/examples/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery.py
  watertap/examples/flowsheets/RO_with_energy_recovery/default_configuration.yaml
  watertap/examples/flowsheets/RO_with_energy_recovery/tests/test_RO_with_energy_recovery_simulation.py
  watertap/examples/flowsheets/case_studies/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/dye_desalination_withRO.py
  watertap/examples/flowsheets/case_studies/wastewater_resource_recovery/dye_desalination/tests/test_dye_desalination_withRO.py
  watertap/unit_models/pressure_exchanger.py
  watertap/unit_models/tests/test_pressure_exchanger.py
Labels: Priority:Normal, :cherries: Merge to rel

#1347 delete sw prop files
  docs/technical_reference/property_models/index.rst
  docs/technical_reference/property_models/seawater_ion_generic.rst
  watertap/property_models/seawater_ion_generic.py
  watertap/property_models/seawater_ion_prop_pack.py
  watertap/property_models/tests/test_seawater_ion_generic.py
  watertap/unit_models/tests/test_nanofiltration_ZO.py
Labels: low effort/low impact, spring-cleaning
