Repository watertap-org/watertap, pull requests merged in 2024-12, with the labels that each got.

#1509 Move get_solver test to more natural location
  watertap/core/plugins/tests/test_solver_wrappers.py
  watertap/core/tests/test_solvers.py
Labels: Priority:Normal, Discussion

#1498 Add molar flows for precipitate and reagent to simplify reaktoro integration
  docs/technical_reference/unit_models/stoichiometric_reactor.rst
  watertap/unit_models/stoichiometric_reactor.py
  watertap/unit_models/tests/test_stoichiometric_reactor.py
Labels: Priority:Normal

#1524 Update looptool documentation
  docs/how_to_guides/how_to_use_loopTool_to_explore_flowsheets.rst
Labels: Priority:Normal

#1512 Repair OLIAPI
  tutorials/oli_calculations.ipynb
  watertap/tools/oli_api/client.py
  watertap/tools/oli_api/conftest.py
  watertap/tools/oli_api/credentials.py
  watertap/tools/oli_api/flash.py
  watertap/tools/oli_api/tests/test_client.py
  watertap/tools/oli_api/tests/test_flash.py
Labels: Priority:High

#1539 Fix Doc Typo in Flowsheet List
  docs/technical_reference/flowsheets/lsrro.rst
Labels: documentation, Priority:High

#1519 ASM1 Property Package Re-Scaling
  tutorials/BSM2.ipynb
  watertap/flowsheets/activated_sludge/ASM1_flowsheet.py
  watertap/flowsheets/anaerobic_digester/ADM1_flowsheet.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
  watertap/property_models/unit_specific/activated_sludge/asm1_properties.py
  watertap/property_models/unit_specific/activated_sludge/asm1_reactions.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_asm1_reaction.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_asm1_thermo.py
  watertap/property_models/unit_specific/anaerobic_digestion/adm1_properties.py
  watertap/unit_models/tests/test_clarifier.py
  watertap/unit_models/tests/test_cstr.py
  watertap/unit_models/tests/test_cstr_injection.py
  watertap/unit_models/tests/test_thickener_unit.py
  watertap/unit_models/translators/tests/test_translator_asm1_adm1.py
Labels: Priority:Normal, IDAES

#1537 Modified ADM1 Property Package Re-Scaling
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/property_models/unit_specific/anaerobic_digestion/modified_adm1_properties.py
  watertap/property_models/unit_specific/anaerobic_digestion/modified_adm1_reactions.py
  watertap/property_models/unit_specific/anaerobic_digestion/tests/test_modified_adm1_reaction.py
  watertap/property_models/unit_specific/anaerobic_digestion/tests/test_modified_adm1_thermo.py
Labels: Priority:High, IDAES

#1540 Ensure no unhandled warnings are emitted during pytest run
  .github/workflows/checks.yml
  pytest.ini
  watertap/core/tests/test_zero_order_base.py
  watertap/flowsheets/RO_with_energy_recovery/tests/test_monte_carlo_sampling_RO_ERD.py
  watertap/flowsheets/activated_sludge/tests/test_modified_asm2d_flowsheet.py
  watertap/flowsheets/anaerobic_digester/tests/test_modified_ADM1_flowsheet_with_translators.py
  watertap/flowsheets/electroNP/tests/test_BSM2_electroNP_no_bioP.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
  watertap/flowsheets/lsrro/tests/test_lssro_multi_sweep.py
  watertap/tools/oli_api/client.py
  watertap/tools/oli_api/credentials.py
  watertap/unit_models/tests/test_generic_desalter.py
  watertap/unit_models/tests/test_generic_separator.py
Labels: Priority:High

#1533 Modified ASM2d model with new scaling tool
  watertap/property_models/unit_specific/activated_sludge/modified_asm2d_properties.py
  watertap/property_models/unit_specific/activated_sludge/modified_asm2d_reactions.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_modified_asm2d_reaction.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_modified_asm2d_thermo.py
Labels: Priority:High, IDAES

#1528 Update Dye Desal Flowsheet Parameters
  watertap/data/techno_economic/nanofiltration.yaml
  watertap/flowsheets/dye_desalination/dye_desalination.py
  watertap/flowsheets/dye_desalination/tests/test_dye_desalination.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
Labels: Priority:Normal

#1534 Update idaes-pse requirement to 2.7.0
  setup.py
Labels: Priority:High

#1530 ADM1 Property Package Re-Scaling
  watertap/flowsheets/anaerobic_digester/modified_ADM1_flowsheet_with_translators.py
  watertap/property_models/unit_specific/anaerobic_digestion/adm1_properties.py
  watertap/property_models/unit_specific/anaerobic_digestion/adm1_reactions.py
  watertap/property_models/unit_specific/anaerobic_digestion/tests/test_adm1_reaction.py
  watertap/property_models/unit_specific/anaerobic_digestion/tests/test_adm1_thermo.py
  watertap/unit_models/translators/tests/test_translator_asm1_adm1.py
Labels: Priority:High, IDAES

#1541 Replace `watertap.core.plugins` with `watertap_solvers`
  docs/how_to_guides/how_to_use_debugging_solver_wrapper.rst
  setup.py
  watertap/__init__.py
  watertap/core/plugins/__init__.py
  watertap/core/plugins/solvers.py
  watertap/core/plugins/tests/test_solver_wrappers.py
  watertap/core/solvers.py
  watertap/core/tests/test_solvers.py
  watertap/core/util/model_debug_mode.py
  watertap/core/util/tests/test_model_debug_mode.py
Labels: Priority:High, dependencies

#1516 add TVC model
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/steam_ejector.rst
  watertap/costing/unit_models/steam_ejector.py
  watertap/unit_models/steam_ejector.py
  watertap/unit_models/tests/test_steam_ejector.py
Labels: Priority:Normal, :cherries: Merge to rel

#1466 add VMD, PGMD/CGMD
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/membrane_distillation_0D.rst
  docs/technical_reference/unit_models/membrane_distillation_1D.rst
  watertap/unit_models/MD/MD_channel_0D.py
  watertap/unit_models/MD/MD_channel_1D.py
  watertap/unit_models/MD/MD_channel_base.py
  watertap/unit_models/MD/membrane_distillation_0D.py
  watertap/unit_models/MD/membrane_distillation_1D.py
  watertap/unit_models/MD/membrane_distillation_base.py
  watertap/unit_models/tests/test_membrane_distillation_0D.py
  watertap/unit_models/tests/test_membrane_distillation_1D.py
Labels: Priority:Normal, :cherries: Merge to rel

#1522 Add method to ED1d for calculating membrane resistance as a function of ion concentration
  docs/technical_reference/unit_models/electrodialysis_1D.rst
  watertap/flowsheets/electrodialysis/electrodialysis_1stack.py
  watertap/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc.py
  watertap/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc_ui.py
  watertap/flowsheets/electrodialysis/tests/test_electrodialysis_1stack.py
  watertap/unit_models/electrodialysis_1D.py
  watertap/unit_models/tests/test_electrodialysis_1D.py
Labels: Priority:Normal
