Repository watertap-org/watertap, pull requests merged in 2024-11, with the labels that each got.

#1520 Update BSM2-P CSTR Model
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension_ui.py
  watertap/unit_models/anaerobic_digester.py
Labels: Priority:Normal

#1526 Update IDAES requirement in preparation to 2.7.0 release
  setup.py
Labels: Priority:High, IDAES, dependencies

#1485 Update Costing in Dye Desal Flowsheet
  watertap/flowsheets/dye_desalination/dye_desalination.py
  watertap/flowsheets/dye_desalination/dye_desalination_global_costing.yaml
  watertap/flowsheets/dye_desalination/dye_desalination_ui.py
  watertap/flowsheets/dye_desalination/dye_sweep.py
  watertap/flowsheets/dye_desalination/tests/test_dye_desalination.py
  watertap/unit_models/zero_order/nanofiltration_zo.py
  watertap/unit_models/zero_order/tests/test_nanofiltration_zo.py
Labels: Priority:Normal

#1518 Migrate watertap.ui.fsapi to idaes_flowsheet_processor
  .github/workflows/checks.yml
  docs/how_to_guides/how_to_use_ui_api.rst
  docs/technical_reference/ui/index.rst
  requirements-dev.txt
  setup.py
  watertap/flowsheets/RO_with_energy_recovery/RO_with_energy_recovery_ui.py
  watertap/flowsheets/dye_desalination/dye_desalination_ui.py
  watertap/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc_ui.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension_ui.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_ui.py
  watertap/flowsheets/gac/gac_ui.py
  watertap/flowsheets/generic_desalination_train/generic_train_ui.py
  watertap/flowsheets/lsrro/lsrro_ui.py
  watertap/flowsheets/mvc/mvc_single_stage_ui.py
  watertap/flowsheets/nf_dspmde/nf_ui.py
  watertap/flowsheets/oaro/oaro_multi_ui.py
  watertap/flowsheets/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/ui/__init__.py
  watertap/ui/fsapi.py
  watertap/ui/tests/__init__.py
  watertap/ui/tests/test_flowsheet_interfaces.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:High
