Repository watertap-org/watertap, pull requests merged in 2024-09, with the labels that each got.

#1477 Add 0D Property Helper
  watertap/core/membrane_channel0d.py
  watertap/core/tests/test_membrane_channel0d.py
Labels: Priority:High

#1468 Update BSM2-P Costing
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension_ui.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
Labels: Priority:High, iedo, costing

#1490 Add __getattr__ for _BaseDebugSolverWrapper
  watertap/core/plugins/solvers.py
Labels: Priority:Low

#1495 Add citation for the parameter sweep demo.
  tutorials/parameter_sweep_demo.ipynb
Labels: Priority:Normal

#1398 adding LCOW per unit and per flow
  watertap/costing/tests/test_costing_base.py
  watertap/costing/watertap_costing_package.py
Labels: Priority:High, IDAES
