Repository watertap-org/watertap, pull requests merged in 2024-07, with the labels that each got.

#1383 Add LSRRO GUI
  setup.py
  watertap/flowsheets/lsrro/lsrro_ui.png
  watertap/flowsheets/lsrro/lsrro_ui.py
  watertap/unit_models/electrodialysis_1D.py
Labels: Priority:High, ui, 1.0

#1439 Ed UI
  setup.py
  watertap/flowsheets/electrodialysis/electrodialysis_1stack_conc_recirc_ui.py
Labels: Priority:High, ui, 1.0

#1332 Generic desalination treatment train
  docs/_static/flowsheets/generic_treatment_train.png
  docs/technical_reference/flowsheets/generic_desalination_train.rst
  docs/technical_reference/flowsheets/index.rst
  docs/technical_reference/unit_models/generic_desalter.rst
  docs/technical_reference/unit_models/generic_separator.rst
  docs/technical_reference/unit_models/index.rst
  setup.py
  watertap/flowsheets/generic_desalination_train/__init__.py
  watertap/flowsheets/generic_desalination_train/costing/__init__.py
  watertap/flowsheets/generic_desalination_train/costing/desalter_costing.py
  watertap/flowsheets/generic_desalination_train/costing/generic_costing.py
  watertap/flowsheets/generic_desalination_train/costing/separator_costing.py
  watertap/flowsheets/generic_desalination_train/costing/stream_costing.py
  watertap/flowsheets/generic_desalination_train/fig_with_costs.png
  watertap/flowsheets/generic_desalination_train/generic_train.py
  watertap/flowsheets/generic_desalination_train/generic_train_ui.py
  watertap/flowsheets/generic_desalination_train/tests/__init__.py
  watertap/flowsheets/generic_desalination_train/tests/test_generic_train.py
  watertap/flowsheets/generic_desalination_train/unit_operations/__init__.py
  watertap/flowsheets/generic_desalination_train/unit_operations/desalter.py
  watertap/flowsheets/generic_desalination_train/unit_operations/mixer.py
  watertap/flowsheets/generic_desalination_train/unit_operations/separator.py
  watertap/flowsheets/generic_desalination_train/utils/__init__.py
  watertap/flowsheets/generic_desalination_train/utils/scale_utils.py
  watertap/tools/analysis_tools/loop_tool/loop_tool.py
  watertap/unit_models/generic_desalter.py
  watertap/unit_models/generic_separation.py
  watertap/unit_models/tests/test_generic_desalter.py
  watertap/unit_models/tests/test_generic_separator.py
Labels: Priority:High

#1358 add steam heater and condenser
  docs/technical_reference/costing/heat_exchanger.rst
  watertap/costing/unit_models/heat_exchanger.py
  watertap/unit_models/steam_heater_0D.py
  watertap/unit_models/tests/test_steam_heater_0D.py
Labels: Priority:Normal, :cherries: Merge to rel

#1343 MCAS compatibility with ZO models
  watertap/core/tests/test_zero_order_base.py
  watertap/core/tests/test_zero_order_sido.py
  watertap/core/tests/test_zero_order_sido_reactive.py
  watertap/core/util/chemistry.py
  watertap/core/util/tests/test_chemistry.py
  watertap/core/zero_order_base.py
  watertap/core/zero_order_electricity.py
  watertap/core/zero_order_sido.py
  watertap/core/zero_order_sido_reactive.py
  watertap/core/zero_order_siso.py
  watertap/flowsheets/seawater_RO_desalination/seawater_RO_desalination.py
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_asm1_thermo.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_asm2d_thermo.py
  watertap/property_models/unit_specific/activated_sludge/tests/test_modified_asm2d_thermo.py
  watertap/property_models/unit_specific/anaerobic_digestion/tests/test_adm1_thermo.py
  watertap/property_models/unit_specific/anaerobic_digestion/tests/test_adm1_vapor_thermo.py
  watertap/property_models/unit_specific/anaerobic_digestion/tests/test_modified_adm1_thermo.py
  watertap/unit_models/tests/test_uv_aop.py
  watertap/unit_models/uv_aop.py
  watertap/unit_models/zero_order/tests/test_cartridge_filtration_zo.py
  watertap/unit_models/zero_order/tests/test_microfiltration_zo.py
Labels: Priority:Normal, nawi, property_model, :cherries: Merge to rel, zo-model

#1462 Convert enthalpies to base units in crystallizer property package
  watertap/flowsheets/crystallization/sim_simple_crystallizer.py
  watertap/flowsheets/crystallization/tests/test_sim_simple_crystallizer.py
  watertap/property_models/tests/test_cryst_prop_pack.py
  watertap/property_models/unit_specific/cryst_prop_pack.py
  watertap/unit_models/crystallizer.py
  watertap/unit_models/tests/test_crystallizer.py
Labels: :cherries: Merge to rel, 1.0

#1461 OARO remove spiral-wound ModuleType
  docs/technical_reference/unit_models/osmotically_assisted_reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/osmotically_assisted_reverse_osmosis_1D.rst
  watertap/unit_models/osmotically_assisted_reverse_osmosis_base.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_0D.py
  watertap/unit_models/tests/test_osmotically_assisted_reverse_osmosis_1D.py
Labels: Priority:Normal

#1435 ADM1/ASM2d Translator Update
  docs/technical_reference/unit_models/translators/translator_adm1_asm2d.rst
  docs/technical_reference/unit_models/translators/translator_asm2d_adm1.rst
  watertap/flowsheets/electroNP/BSM2_electroNP_no_bioP.py
  watertap/flowsheets/electroNP/electroNP_flowsheet.py
  watertap/flowsheets/electroNP/tests/test_BSM2_electroNP_no_bioP.py
  watertap/flowsheets/electroNP/tests/test_electroNP_flowsheet.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension_ui.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
  watertap/property_models/unit_specific/anaerobic_digestion/modified_adm1_reactions.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm2d.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
  watertap/unit_models/translators/translator_adm1_asm2d.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:High

#1287 Debugging solver wrapper
  watertap/core/plugins/solvers.py
  watertap/core/solvers.py
  watertap/core/util/model_debug_mode.py
  watertap/core/util/tests/test_model_debug_mode.py
Labels: Priority:Normal

#1470 Add doc for debug solver wrapper and cleanup
  docs/how_to_guides/how_to_use_debugging_solver_wrapper.rst
  docs/how_to_guides/index.rst
  watertap/core/plugins/solvers.py
Labels: documentation, Priority:Normal, utility
