Repository watertap-org/watertap, pull requests merged in 2024-01, with the labels that each got.

#1242 Add limiting current density methods to electrodialysis_0D
  docs/technical_reference/unit_models/electrodialysis_0D.rst
  docs/technical_reference/unit_models/electrodialysis_1D.rst
  watertap/unit_models/electrodialysis_0D.py
  watertap/unit_models/tests/test_electrodialysis_0D.py
Labels: Priority:Normal

#1238 GAC model for the UI
  setup.py
  watertap/examples/flowsheets/gac/__init__.py
  watertap/examples/flowsheets/gac/gac.py
  watertap/examples/flowsheets/gac/gac_ui.png
  watertap/examples/flowsheets/gac/gac_ui.py
  watertap/examples/flowsheets/gac/tests/__init__.py
  watertap/examples/flowsheets/gac/tests/test_gac.py
  watertap/ui/fsapi.py
  watertap/ui/tests/test_flowsheet_interfaces.py
Labels: enhancement, Priority:Normal, ui

#1267 Loosen idaes-pse requirement to include 2.3.x stable and 2.4 dev
  setup.py
Labels: :cherries: Merge to rel, PrOMMiS

#1275 Fix Binder IDAES solver configuration and Jupyter documentation
  .binder/postBuild
  docs/how_to_guides/notebooks.rst
Labels: documentation, :cherries: Merge to rel, bugfix, jupyter

#1271 Fix DOF in IX costing function for single use resin and scale pumping power
  docs/technical_reference/unit_models/ion_exchange_0D.rst
  watertap/costing/unit_models/ion_exchange.py
  watertap/examples/flowsheets/ion_exchange/tests/test_ion_exchange_demo.py
  watertap/unit_models/ion_exchange_0D.py
  watertap/unit_models/tests/test_ion_exchange_0D.py
Labels: bug, Priority:Normal

#1276 BSM2 with P extension
  watertap/examples/flowsheets/case_studies/activated_sludge/modified_ASM2D_flowsheet.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/examples/flowsheets/case_studies/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
Labels: Priority:High

#1268 Add method for ParamterSweepTool to change lower/upper bounds, and fix/unfix variables.
  docs/how_to_guides/how_to_use_parameter_sweep.rst
  docs/how_to_guides/how_to_use_parameter_sweep_monte_carlo.rst
  watertap/tools/parameter_sweep/parameter_sweep.py
  watertap/tools/parameter_sweep/parameter_sweep_reader.py
  watertap/tools/parameter_sweep/sampling_types.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep.py
  watertap/tools/parameter_sweep/tests/test_parameter_sweep_reader.py
Labels: Priority:Normal

#1184 Adding stoichiometric reactor to WT
  docs/_static/unit_models/stoichiometric_reactor.png
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/stoichiometric_reactor.rst
  watertap/costing/unit_models/stoichiometric_reactor.py
  watertap/unit_models/stoichiometric_reactor.py
  watertap/unit_models/tests/test_stoichiometric_reactor.py
Labels: Priority:Normal

#1270 Add functionality for input based model options
  watertap/ui/fsapi.py
  watertap/ui/tests/test_fsapi.py
Labels: Priority:High, fsapi
