Repository watertap-org/watertap, pull requests merged in 2025-04, with the labels that each got.

#1561 Update WaterTAP Citation
  CITATION.cff
  README.md
  docs/conf.py
  docs/index.rst
Labels: Priority:Normal

#1567 Add Flowsheet Link to Documentation
  docs/technical_reference/flowsheets/index.rst
Labels: documentation, Priority:Normal

#1569 Update runner images in GitHub Actions workflows
  .github/workflows/checks.yml
Labels: Priority:High

#1570 Add In-Line References to Modified ASM2d
  watertap/property_models/unit_specific/activated_sludge/modified_asm2d_properties.py
Labels: Priority:Normal

#1554 Electrodialysis- Bipolar - 1D
  docs/_static/unit_models/BPEDdiagram.png
  docs/technical_reference/unit_models/electrodialysis_bipolar_1D.rst
  docs/technical_reference/unit_models/index.rst
  watertap/unit_models/electrodialysis_bipolar_1D.py
  watertap/unit_models/tests/test_electrodialysis_bipolar_1D.py
Labels: Priority:Normal
