Repository watertap-org/watertap, pull requests merged in 2025-05, with the labels that each got.

#1574 Documentation import path
  docs/technical_reference/unit_models/aeration_tank.rst
  docs/technical_reference/unit_models/anaerobic_digester.rst
  docs/technical_reference/unit_models/boron_removal.rst
  docs/technical_reference/unit_models/clarifier.rst
  docs/technical_reference/unit_models/coag_floc_model.rst
  docs/technical_reference/unit_models/crystallizer_0D.rst
  docs/technical_reference/unit_models/cstr.rst
  docs/technical_reference/unit_models/cstr_injection.rst
  docs/technical_reference/unit_models/dewatering.rst
  docs/technical_reference/unit_models/electroNP_ZO.rst
  docs/technical_reference/unit_models/electrodialysis_0D.rst
  docs/technical_reference/unit_models/electrodialysis_1D.rst
  docs/technical_reference/unit_models/electrodialysis_bipolar_1D.rst
  docs/technical_reference/unit_models/electrolyzer.rst
  docs/technical_reference/unit_models/energy_recovery_device.rst
  docs/technical_reference/unit_models/gac.rst
  docs/technical_reference/unit_models/generic_desalter.rst
  docs/technical_reference/unit_models/generic_separator.rst
  docs/technical_reference/unit_models/ion_exchange_0D.rst
  docs/technical_reference/unit_models/membrane_distillation_0D.rst
  docs/technical_reference/unit_models/membrane_distillation_1D.rst
  docs/technical_reference/unit_models/mvc.rst
  docs/technical_reference/unit_models/nanofiltration_ZO.rst
  docs/technical_reference/unit_models/nanofiltration_dspmde_0D.rst
  docs/technical_reference/unit_models/osmotically_assisted_reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/osmotically_assisted_reverse_osmosis_1D.rst
  docs/technical_reference/unit_models/pressure_exchanger.rst
  docs/technical_reference/unit_models/pump.rst
  docs/technical_reference/unit_models/reverse_osmosis_0D.rst
  docs/technical_reference/unit_models/reverse_osmosis_1D.rst
  docs/technical_reference/unit_models/steam_ejector.rst
  docs/technical_reference/unit_models/stoichiometric_reactor.rst
  docs/technical_reference/unit_models/thickener.rst
  docs/technical_reference/unit_models/uv_aop.rst
Labels: Priority:Normal

#1578 ZO Flowsheet Pointer
  docs/technical_reference/flowsheets/index.rst
Labels: documentation, Priority:Normal

#1586 Minor Costing Documentation Fixes
  docs/technical_reference/costing/clarifier.rst
  docs/technical_reference/costing/compressor.rst
  docs/technical_reference/costing/costing_base.rst
  docs/technical_reference/costing/crystallizer.rst
  docs/technical_reference/costing/cstr.rst
  docs/technical_reference/costing/dewatering.rst
  docs/technical_reference/costing/electroNP.rst
  docs/technical_reference/costing/electrodialysis.rst
  docs/technical_reference/costing/electrolyzer.rst
  docs/technical_reference/costing/energy_recovery_device.rst
  docs/technical_reference/costing/evaporator.rst
  docs/technical_reference/costing/heat_exchanger.rst
  docs/technical_reference/costing/heater_chiller.rst
  docs/technical_reference/costing/membrane_distillation.rst
  docs/technical_reference/costing/mixer.rst
  docs/technical_reference/costing/multiple_choice_costing_block.rst
  docs/technical_reference/costing/nanofiltration.rst
  docs/technical_reference/costing/osmotically_assisted_reverse_osmosis.rst
  docs/technical_reference/costing/pressure_exchanger.rst
  docs/technical_reference/costing/pump.rst
  docs/technical_reference/costing/reverse_osmosis.rst
  docs/technical_reference/costing/stoichiometric_reactor.rst
  docs/technical_reference/costing/thickener.rst
  docs/technical_reference/costing/util.rst
  docs/technical_reference/costing/uv_aop.rst
  docs/technical_reference/costing/zero_order_costing.rst
Labels: Priority:Normal

#1535 Anaerobic Digester Re-Scaling
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
  watertap/unit_models/anaerobic_digester.py
  watertap/unit_models/tests/test_anaerobic_digester.py
Labels: Priority:Normal, iedo, IDAES

#1588 Dye Desal Base Currency
  watertap/flowsheets/dye_desalination/dye_desalination.py
  watertap/flowsheets/dye_desalination/dye_desalination_global_costing.yaml
  watertap/flowsheets/dye_desalination/tests/test_dye_desalination.py
Labels: Priority:Normal

#1589 Change `electricity_cost` units to be `base_currency`
  watertap/costing/watertap_costing_package.py
  watertap/flowsheets/dye_desalination/tests/test_dye_desalination.py
Labels: Priority:High
