Repository watertap-org/watertap, pull requests merged in 2025-03, with the labels that each got.

#1557 Revise UF_ZO costing defaults
  watertap/data/techno_economic/ultra_filtration.yaml
Labels: Priority:Normal, bugfix

#1558 Update idaes-pse requirement for 2.8.0
  setup.py
Labels: Priority:High

#1559 Update BSM2-P KLa Values
  docs/technical_reference/flowsheets/ASM1.rst
  docs/technical_reference/flowsheets/ASM2d.rst
  docs/technical_reference/flowsheets/extended_BSM2.rst
  watertap/flowsheets/activated_sludge/ASM2D_flowsheet.py
  watertap/flowsheets/activated_sludge/modified_ASM2D_flowsheet.py
  watertap/flowsheets/activated_sludge/tests/test_asm2d_flowsheet.py
  watertap/flowsheets/activated_sludge/tests/test_modified_asm2d_flowsheet.py
  watertap/flowsheets/electroNP/BSM2_electroNP_no_bioP.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension_ui.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
Labels: Priority:Normal
