Repository watertap-org/watertap, pull requests merged in 2025-06, with the labels that each got.

#1543 Clarifier Re-Scaling
  watertap/unit_models/clarifier.py
  watertap/unit_models/tests/test_clarifier.py
Labels: Priority:Normal, iedo, IDAES

#1545 Thickener & Dewaterer Re-Scaling
  watertap/unit_models/dewatering.py
  watertap/unit_models/tests/test_dewatering_unit.py
  watertap/unit_models/tests/test_thickener_unit.py
  watertap/unit_models/thickener.py
Labels: Priority:Normal, iedo, IDAES

#1546 BSM2 Translator Block Re-Scaling
  watertap/unit_models/translators/tests/test_translator_adm1_asm1.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm2d.py
  watertap/unit_models/translators/tests/test_translator_asm1_adm1.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
  watertap/unit_models/translators/translator_adm1_asm1.py
  watertap/unit_models/translators/translator_adm1_asm2d.py
  watertap/unit_models/translators/translator_asm1_adm1.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:Normal, iedo, IDAES

#1563 Reformulate Expr_Ifs in ASM2d-ADM1 Translators
  docs/technical_reference/flowsheets/electrodialysis_1stack_conc_recirc.rst
  watertap/core/util/misc.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
  watertap/unit_models/translators/tests/test_translator_asm2d_adm1.py
  watertap/unit_models/translators/translator_asm2d_adm1.py
Labels: Priority:Normal, IDAES

#1536 Simple OD Nanofiltration model
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/nanofiltration_0D.rst
  watertap/property_models/multicomp_aq_sol_prop_pack.py
  watertap/property_models/tests/test_multicomp_aq_sol_prop_pack.py
  watertap/unit_models/__init__.py
  watertap/unit_models/nanofiltration_0D.py
  watertap/unit_models/nanofiltration_ZO.py
  watertap/unit_models/tests/test_nanofiltration_0D.py
Labels: enhancement, Priority:Normal, oli

#1596 Apply Scalers to BSM2-P
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/BSM2_P_extension_ui.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_BSM2_P_extension.py
  watertap/flowsheets/full_water_resource_recovery_facility/test/test_full_WRRF_with_ASM1_ADM1.py
  watertap/property_models/unit_specific/anaerobic_digestion/modified_adm1_reactions.py
  watertap/unit_models/aeration_tank.py
  watertap/unit_models/translators/tests/test_translator_adm1_asm1.py
Labels: Priority:High
